### ISSUE TITLE
Visibility of the carousel arrows are not updated when image is loaded

### ISSUE THREAD

**Issue by ttamminen** [leandrowd/react-responsive-carousel#104]
The function `updateStatics` should be called when image load is ready. 

Currently, the update function is called, for example, here:

```
        // when the component is rendered we need to calculate
        // the container size to adjust the responsive behaviour
        this.updateStatics();
```

But in our case images have not been loaded yet, so wrong dimensions `outerWidth(this.thumb0);` are being used for the calculation.

I'll create a PR with a fix.

**Comment by leandrowd** [comment]
Hi @ttamminen, thanks for you PR. All your changes are published as 3.1.7 in npm.
