### ISSUE TITLE
Problem with swiping on mobile

### ISSUE THREAD

**Issue by hustlerism** [leandrowd/react-responsive-carousel#118]
When i swiped up it will swipe to the previous slide and when i swiped down it will swipe to the next slide.

Swiping right and left are working as expected. It should not be able to swipe up and down to change the slides.

`	<Carousel emulateTouch={true} showArrows={false} showIndicatiors={false} showStatus={false}>
`

**Comment by leandrowd** [comment]
Hi @hustlerism, I've added support to adding tolerance. The default value is 5(px) which should solve your use case. If you feel it's not enough, use the prop `swipeScrollTolerance` to increase this value. Please update to the latest version and let me know how it goes.

**Comment by hustlerism** [comment]
Hi @leandrowd , the slides tends to wobbles when the page being scrolled vertically. 

Btw, is it possible to stop the slides from dragging (draggable=false?) when we touch and hold it?

**Comment by leandrowd** [comment]
Hi @hustlerism, it's possible but I don't currently have any spare time to dedicate to this project right now. Would you like to fix it and send a PR?

**Comment by leandrowd** [comment]
Hi @hustlerism, the problem that was causing the wobbles is now fixed. Please download the version `3.1.17`.

**Comment by JulianJorgensen** [comment]
I am seeing the same issue as @nadzimo . Great library btw!

**Comment by aniruddhashevle** [comment]
@leandrowd : I'm having the same issue on `3.2.7`.

**Comment by ccpc93js** [comment]
I'm using react-responsive-carousel, I want it to be continuous towards the same direction, and not return towards the opposite direction. anyone Help me? there is any option for this?
