### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by christophediprima** [leandrowd/react-responsive-carousel#12]
Hello,

Thanks for this carousel ! Are you planing to support server side rendering ?

**Comment by leandrowd** [comment]
Hi, 

To be honest I'm running out of time to work on this plugin now but I would accept a PR anytime :)

**Comment by leandrowd** [comment]
I'm closing this issue by lack of activity. If someone has interesting in adding support to server side rendering I will be happy to accept a PR.
