### ISSUE TITLE
Video support???

### ISSUE THREAD

**Issue by anhkhoi** [leandrowd/react-responsive-carousel#122]
I got a message when put a video tag inside Carousel container.
 
`No images found! Can't build the thumb list without images. If you don't need thumbs, set showThumbs={false} in the Carousel. Note that it's not possible to get images rendered inside custom components. More info at https://github.com/leandrowd/react-responsive-carousel/blob/master/TROUBLESHOOTING.md`

**Comment by leandrowd** [comment]
I don't understand what's your question on the issue above.

If you add showThumbs={false} this warning will go away. Alternatively, if you want to add a thumb for your video, you can add an `img` tag inside your `video` tag and it should render the thumb correctly.

`<video><img src="my-image.png' /></video>

**Comment by anhkhoi** [comment]
@leandrowd 
Because I can't load my video on carousel, therefore I created this issue :). That is my mistake, I can make it work now. 

Thank for your support 👍

**Comment by leandrowd** [comment]
You are welcome!

**Comment by serjamie** [comment]
@anhkhoi Did you manage to pause/stop a video when moving to the next slide?

**Comment by Pawani-DeSilva** [comment]
@serjamie Have you found a solution to pause/stop a video when moving to the next slide?

**Comment by evdma** [comment]
Still need a solution to pause/stop a video when moving to the next slide
