### ISSUE TITLE
Is it possible to style arrows?

### ISSUE THREAD

**Issue by shurick81** [leandrowd/react-responsive-carousel#123]
I'd like to change the color of these little triangles for listing slides. But I can't find how they are rendered and how I can apply any css on them.

**Comment by shurick81** [comment]
It's possible to change color and size like this:

```
.contentlist .carousel .control-arrow::before
{
    border-top-width: 20px;
    border-bottom-width: 20px;
}
.contentlist .carousel .control-prev::before
{
    border-right-width: 10px;
    border-right-color: rgba(238,209,47,1);
}
.contentlist .carousel .control-next::before
{
    border-left-width: 10px;
    border-left-color: rgba(238,209,47,1);
}

```

**Comment by leandrowd** [comment]
You should be able to override any css rule used in the carousel if you make your rules more specific than the ones used in the carousel. The code you posted above seems just fine for that. Did it work?

**Comment by shurick81** [comment]
Yes, sorry, this code worked well. It just took for me some time to realize that the arrows are rendered by border styling, though I still think it is a bit tricky and might be better to be documented in your project. Anyway, thanks for the component and your help. This one is not an issue for me and might be closed.
