### ISSUE TITLE
Please put css to cdn

### ISSUE THREAD

**Issue by droganov** [leandrowd/react-responsive-carousel#124]

**Comment by leandrowd** [comment]
Could you elaborate on why you need this? I don't see the point on uploading this css to a cdn as if you are looking for performance, the best you can do is bundling this css with your app code.

**Comment by droganov** [comment]
I use css in js and don't use loaders

**Comment by leandrowd** [comment]
In order to publish to a CDN I would need to do a bunch of changes and I don't have time to invest on it. I still think the best solution would be to have this handled within your project.
