### ISSUE TITLE
Example of getting selected item from onChange event

### ISSUE THREAD

**Issue by shurick81** [leandrowd/react-responsive-carousel#127]
Is there any example of using this method without any additional flux library?

**Comment by leandrowd** [comment]
`onChange` will be called with 2 arguments, the 1st one will be the index of the element in the list of slides and the 2nd will be the element itself.

Check this line: https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L259

**Comment by shurick81** [comment]
Thanks, this worked for me:

```
<Carousel axis="horizontal" selectedItem={this.state.selectedIndex} onChange={(index) => this.onHideExampleButtonClick(index)} showThumbs={false} showStatus={false} infiniteLoop={true} className="carouselblock">
    {contentSlideItems}
</Carousel>
```
