### ISSUE TITLE
Allow ability to disable handleClickItem

### ISSUE THREAD

**Issue by chipit24** [leandrowd/react-responsive-carousel#134]
When you click on a slide, the carousel will move to that slide. I want to control the movement of slides solely through `selectedItem`. 

If I have a "Next Slide" button that increments `selectedItem` *inside* my child slide component, it won't work since the slide will just be reverted to the one I just clicked: https://github.com/leandrowd/react-responsive-carousel/blob/e30446969483fedb07aeab8eac18a083fb694e22/src/components/Carousel.js#L245

Currently, I get around this by passing the following for `onClickItem`:
```
onClickItem = index => {
  // Prevent clicking from changing selectedItem
  if (index !== this.state.selectedItem) {
    setTimeout(() => this.forceUpdate());
  }
}
```

This works because I have the following function passed down for the onChange prop (so `this.state.selectedItem` points to the slide I should be on):
```
onChange = index => {
  if (index !== this.state.selectedItem) {
    this.setState({selectedItem: index});
  }
}
```

**Comment by leandrowd** [comment]
Hi @chipit24, this is a fair request and we can solve it by refactoring the component to export a stateless carousel as well as the controlled one. Let me know if you want to contribute a PR for that, otherwise, I can do it when I have time.

**Comment by leandrowd** [comment]
Hi @chipit24, have a look at the PR https://github.com/leandrowd/react-responsive-carousel/pull/144 where I added an example of usage with external controls. 
I added a fix to the problem that we could still use non-existent indexes for the selected item when using external controls as well.

I will close this issue as what you requested is already possible. Feel free to reopen or create a new one if you have more problems.

Thanks.

**Comment by leandrowd** [comment]
The example is available here: http://react-responsive-carousel.js.org/storybook/?selectedKind=Carousel&selectedStory=with%20external%20controls&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

**Comment by vasupol11** [comment]
I don't understand where you say use a non-existent indexes for the selected item. So i set the index to something random and it would never move because that index doesnt exist?
