### ISSUE TITLE
Test TypeScript definition files

### ISSUE THREAD

**Issue by ttamminen** [leandrowd/react-responsive-carousel#136]
I have created TypeScript definition file that will improve productivity tremendously and decrease the risk of writing bugs.

If someone could test the file by changing their package.json file temporarily:

```
"react-responsive-carousel": "ttamminen/react-responsive-carousel#library-type-definitions",
```

Then run command: `npm install react-responsive-carousel`

When you use the library, you should get autocompletion to all properties.

![image](https://user-images.githubusercontent.com/1038081/26881508-482f12ce-4ba0-11e7-9042-4307ba15fbd3.png)

**Comment by leandrowd** [comment]
Hi @ttamminen, I'm closing this as @DeividasBakanas has submitted a PR with the type definitions and it's already published to npm as 3.1.22.

Thanks.
