### ISSUE TITLE
emulateTouch

### ISSUE THREAD

**Issue by a-amir01** [leandrowd/react-responsive-carousel#139]
Currently, when you enable emulateTouch you have to hold down the mouse and swipe left or right. Is there a way to be able to swipe left or right when you are just hovering over the carousel on the computer?

**Comment by leandrowd** [comment]
It's a trick requirement. IMO, the way you simulate touch in a desktop environment is through drag and drop. Supporting it just based on hover is possible but might offer a bad user experience as you could switch slides just by scrolling down while browsing if the mouse goes over the carousel with some horizontal movement.

Could you give me an example of the use case where this would be applied?

**Comment by a-amir01** [comment]
I was able to do it if I add in the css file

`
.carousel * {
  margin: 0;
  padding: 0;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;

  **overflow-x: auto;**

}
`
Then you can slide through a collection of pictures without having to click. 
But it messes with the like the arrow or dots

**Comment by leandrowd** [comment]
I don't quite get what you need then. For the solution above, seems that you only made the carousel being scrollable, which makes me think if you really need a carousel...

**Comment by leandrowd** [comment]
This is not something I'm planning to implement. If you really want to push it forward, please submit a pull request and let's discuss with an example. I'm closing for now but feel free to reopen if you are interested in contributing.
