### ISSUE TITLE
How to set carousel back to normal when swipe less than `swipeScrollTolerance`

### ISSUE THREAD

**Issue by joshua7v** [leandrowd/react-responsive-carousel#140]
￼for example

the default `swipeScrollTolerance` is 5
if I swipe like this, the carousel just stops here. How to make it back to the initial state.
![1](https://user-images.githubusercontent.com/4159858/27313892-015ff508-5536-11e7-86b5-bc5c0c5b7c6a.png)

**Comment by leandrowd** [comment]
Have you got any errors on your console?

**Comment by joshua7v** [comment]
@leandrowd no, this screenshot was from [demos](http://react-responsive-carousel.js.org/storybook/?selectedKind=Carousel&selectedStory=emulate%20touch&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

in the emulate touch section, 
try to swipe a little (less than swipeScrollTolerance which is default to 5)

**Comment by leandrowd** [comment]
Hey @joshua7v, this bug has been solved and a new version of the component released to npm.

**Comment by RaduCl** [comment]
Hy, i noticed this bug regresed after 3.1.41, ([this commit](https://github.com/leandrowd/react-responsive-carousel/commit/076eabb67975255dde976e904b78ebf3b868f58f))
