### ISSUE TITLE
Add setting to disable based on responsive breakpoint

### ISSUE THREAD

**Issue by davidyeiser** [leandrowd/react-responsive-carousel#146]
First, thanks for writing this; it was very easy to integrate and works as expected.

**My question**:
Are there any plans to integrate a responsive disabling mechanism? That is something like a “disable” boolean that could be activated via `min-width`?

For example:
```
const carouselSettings = {
  responsive: [{
    breakPoint: 768,
    disableCarousel: true
  }]
};
```

**Comment by leandrowd** [comment]
Hi @davidyeiser, I believe that this decision should come from the app rendering the carousel instead. It would be pretty simple to just not render the carousel in case window size is smarter than expected.

**Comment by davidyeiser** [comment]
That makes sense, I ended up using `react-media` to accomplish what I wanted to do.
https://github.com/reacttraining/react-media

Thanks!
