### ISSUE TITLE
Autoplay and stop on hover causes a warning.

### ISSUE THREAD

**Issue by saxation** [leandrowd/react-responsive-carousel#148]
When using autoplay and the stop on hover functionality this can cause setTimeout issues because the autoplay function is not being cleared properly.

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Carousel component.

Related to issue: #142

Reproduce by setting up the carousel with autoplay and stop on hover, then render the page and click the next and previous buttons a couple of times, move mouse away from the carousel or navigate away from the page the carousel is on, this will trigger the setState error as described.

**Comment by leandrowd** [comment]
The fix has been merged
