### ISSUE TITLE
NPM Dependencies

### ISSUE THREAD

**Issue by tayabsoomro** [leandrowd/react-responsive-carousel#152]
Hi, I tried using this on my project. Which entailed installing the 'react-responsive-carousel' through npm and importing it in the file. It did not work. Could you please write a set of instructions to simply get it running in any project so that one does not have to worry about the dependencies. Thank you.

**Comment by leandrowd** [comment]
Instructions are available at https://github.com/leandrowd/react-responsive-carousel/blob/master/README.md

**Comment by wildeyes** [comment]
@leandrowd Hey, wanted to help, but not really sure what do in this issue?

**Comment by leandrowd** [comment]
@tayabsoomro , do you still have questions?

**Comment by tayabsoomro** [comment]
Oh it is sorted out now, thank you.
