### ISSUE TITLE
Failed to calculate Carousel items size initially when items are not images.

### ISSUE THREAD

**Issue by DeividasBakanas** [leandrowd/react-responsive-carousel#153]
Issue causes not fluent carousel sliding (carousel does not move, until touch end or mouse up, then moves to next / previous item).

Possible bug:

Sizes calculation are made by method [`updateSizes`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L230).

Initially, on [`componentWillMount`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L81) method [`setupCarousel`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L109) is called.

This method sets state to [`initialized = true`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L117). 
In the same render cycle `updateSizes` uses this value using [`this.state.initialized`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L231).

Because of using outdated [`this.state.initialized`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L231) value, `updateSizes` skips sizes calculations initially. 

Reproduced issue can be found [here](https://github.com/DeividasBakanas/react-responsive-carousel-issues/blob/master/issue-153).

**Comment by admapop** [comment]
Hi, sorry for the necrobump.

I went around this issue by pushing new state with ComponentDidMount() where i define the itemSize and wrapperSize

**Comment by leandrowd** [comment]
Cleaning up old issues. I believe this has been solved already. Feel free to reopen if needed...
