### ISSUE TITLE
Unexpected items flick in touch devices when Carousel is controlled and not with image items.

### ISSUE THREAD

**Issue by DeividasBakanas** [leandrowd/react-responsive-carousel#154]
This issue can only be reproduced in touch capable devices (touch screens).
Controlled carousel - carousel with onChange and selectedItem props supplied.

Possible bug:

I found that this issue is related to method [`resetPosition`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L332).

This method is called every time [swipe ends](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L288). 

Method [`onSwipeEnd`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L287) is called before metods [`increment`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L355) or [`decrement`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L351) so:
1. Item is swiped by user to a certain position.  
2. `onSwipeEnd` is called and `resetPosition` swipes item to it's initial position.
3. `increment` / `decrement` is called and it swipes item to next position.

This sequence causes unexpected items flick which is very noticeable in touch devices and not that noticeable with emulated touch.

Reproduced issue can be found [here](https://github.com/DeividasBakanas/react-responsive-carousel-issues/tree/master/issue-154).

**Comment by leandrowd** [comment]
Hi @DeividasBakanas , thanks for raising the issue with such a thorough explanation. Unfortunately I won't be able to work on this component anytime soon. Would you be interested in contributing?

**Comment by vTrip** [comment]
Can confirm that removing the line ` _this.resetPosition();` from `Carousel.js` fixes this issue.

**Comment by leandrowd** [comment]
#249 was merged so this should be fixed. Please reopen if there are any issues.

**Comment by driskell** [comment]
Looks like removing resetPosition now leaves the slide askew and mid-swipe if the threshold is not met.

**Comment by driskell** [comment]
Just raised a PR with code we tested 👍 Be great if someone else could also test it on real touch device. It seems to work nicely.
