### ISSUE TITLE
onChange called when Carousel prop selectedItem changed.

### ISSUE THREAD

**Issue by DeividasBakanas** [leandrowd/react-responsive-carousel#155]
Expected behavior:

`onChange` is usually called when some changes were made inside of component to inform parent component about change.

Current behavior:

When parrent component changes `selectedItem` prop `onChange` is called.

Possible bug:

When parrent component changes `selectedItem`, method [`componentWillReceiveProps`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L84) is called. 
If item position has changed it calls method [`moveTo`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L359) which calls [`selectItem`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L390) that invokes [`handleOnChange`](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L392) which is responsible for `onChange` call.

Reproduced issue:

Reproduced issue can be found [here](https://github.com/DeividasBakanas/react-responsive-carousel-issues/tree/master/issue-155).

When button `Change selectedItem` is pressed, state property `SelectedItem` is changed in a parrent component. This property is supplied to `Carousel` prop `selectedItem` so this change will trigger `componentWillReceiveProps` in `Carousel`. Message about triggered `Carousel`'s `onChange` will be printed in browser's console.

**Comment by leandrowd** [comment]
Hi @DeividasBakanas, thanks for raising the issue! I won't have time to fix it anytime soon. Would you like to submit a fix?

**Comment by Tomassito** [comment]
Are you sure? A change is a change. If parent component triggers it then its callback can also know that it was triggered from this level.

**Comment by leandrowd** [comment]
Cleaning up old issues. Feel free to reopen if needed...
