### ISSUE TITLE
Content drawn wrong in IE after Modal

### ISSUE THREAD

**Issue by LeopoldLerch** [leandrowd/react-responsive-carousel#157]
Hy

I am using the Carousel in the following Layout

```
<Carousel
                showThumbs={false}
                className={styles.newsSlider}
                showStatus={false}
                autoPlay
                infiniteLoop
                onClickItem={(index, item) => {
                    this._newsPopUp.setState({
                        url: this.state.newsData[index].linkUrl,
                        visible: true
                    })
                }}>
                {this.state.newsData &&
                    this.state.newsData.slice(0, sliderImages).map((news) => {
                        return <div className={styles.newsSliderContent} >
                            <div className={styles.newsSliderImageDiv} style={{
                                backgroundImage: "url('" + news.imageUrl + "')"
                            }}>
                            </div>
                            <div>

                            </div>
                        </div>
                    })
                }
            </Carousel>
```

Basically it adds Content, including a Image on the left half and text on the right part of the content-div. When clicking on it, a Modal from Office-UI-Fabric is opened which shows the linked Page.

It works fine in all Browsers, just IE (as usual) shows strange behaviour. When I open the Modal on the last Item (all other items work fine) the modal goes up, and until there everything is fine. As soon as the Modal is closed the Carousel is completely messed up. Some slides are empty on the screen. the image has swapped to the right. It seems that some positioning failed here. However as mentioned, this happens only when the modal showing the last page was opend. on the pages before nothing happens.

**Comment by leandrowd** [comment]
Hi @LeopoldLerch, would you be able to publish an example of the problem? You have a very specific situation and I'm afraid it would take too much effort for anyone to setup it and investigate. If you publish an example where it occurs, you have more chances of having this issue solved.

**Comment by LeopoldLerch** [comment]
Will try to. I know this will help, but it´s quite complex. 
Currently i know it has something to do with autoplay and infinite-loop. It occurs only in combination of the 2. If I use only autoplay or only infinite-loop it works.

**Comment by LeopoldLerch** [comment]
Ok, i can get around it when I "pause" the autoplay. But currently there is no built-in Possibility to do this. Currently I am doing 

(this._carousel as any).destroyAutoPlay();

and 

            (this._carousel as any).setupAutoPlay();
            (this._carousel as any).startOnLeave();

in order to get around the mouseenter, autoplay properties. and have to cast the carousel object to any because there are not typings for the functions. 

Would be nice if there were a "nicer" function for pausing instead of the need to destroy and setup the whole autoplay-thing

**Comment by leandrowd** [comment]
Hey @LeopoldLerch , you can change the value of autoplay to false at any time, just update the prop. Don't need to do imperative calls. Please let me know if you still have problems after you try it.

**Comment by LeopoldLerch** [comment]
I tried, but when I change it in the the markup (eg <Carousel
autoplay={this.state.doCarouselAutoPlay} .... ) the component is reloaded
and jumps to the first item (so no pause but reset) and otherwise i can´t
change it because the props are readOnly

btw.
I am using Typescript if that does matter




2017-09-04 13:24 GMT+02:00 Leandro Lemos <notifications@github.com>:

**Comment by leandrowd** [comment]
Something else might be changing. Are you setting a key? Without sharing
the whole code I'll just be able to shoot in the dark :/

**Comment by LeopoldLerch** [comment]
no, i do not set any key

do i have to? (sry for noob-question, i am doing this typescript/react
thing only for the last 4 months)

2017-09-04 13:44 GMT+02:00 Leandro Lemos <notifications@github.com>:

> Something else might be changing. Are you setting a key? Without sharing
> the whole code I'll just be able to shoot in the dark :/
>

**Comment by LeopoldLerch** [comment]
no, even if i apply a key to the carousel itself as well as the divs
inside, it is jumping right back to the first one if I update the props
using a property of the parent element

2017-09-04 13:46 GMT+02:00 Leopold Lerch <leopold.lerch@gmail.com>:

> no, i do not set any key
>
> do i have to? (sry for noob-question, i am doing this typescript/react
> thing only for the last 4 months)
>
> 2017-09-04 13:44 GMT+02:00 Leandro Lemos <notifications@github.com>:
>
>> Something else might be changing. Are you setting a key? Without sharing
>> the whole code I'll just be able to shoot in the dark :/
>>

**Comment by leandrowd** [comment]
You don't always need a key, and if the key changes the component will
reset.

We really need to see some code in order to help you more. I'm happy to
help if you can create a repo with enough code that we can reproduce the
error.

**Comment by leandrowd** [comment]
Hi @LeopoldLerch, I've created a base code pen for the carousel. You can fork it and reproduce your problem there ;) Check it out: https://codepen.io/leandrowd/pen/xLvOPd

**Comment by leandrowd** [comment]
Cleaning up old issues. I believe this has been solved already. Feel free to reopen if needed...
