### ISSUE TITLE
Fix module name in doco

### ISSUE THREAD

**Issue by kaploink** [leandrowd/react-responsive-carousel#16]
Think doco should say
```
var Carousel = require('react-responsive-carousel');
```
not
```
var Carousel = require('./components/Carousel');
```

Hopefully hasn't stopped too many people from using an otherwise great control.  Am picking it over Nuka for greater reliability on IE9.

Perhaps this just applies when using webpack, which by default looks in node_modules for anything without a path.

**Comment by leandrowd** [comment]
Hey dude, thanks for opening the issue. Next time I do any change I will fix it.
