### ISSUE TITLE
Looking for maintaners

### ISSUE THREAD

**Issue by leandrowd** [leandrowd/react-responsive-carousel#160]
Hey everyone, as you can see, I haven't been able to respond to issues as quickly as I would like. Things are pretty busy and I don't have the time to dedicate to this project for now. 

I'm looking for people to help on this. I can help with pull requests, questions and get those interested up to speed in an async way (basically exchanging messages through issues) but I won't be able to contribute any code or do any testing, at least in the coming months.

This component has around 15k downloads per month (from npm), 240+ stars and doesn't need much maintenance, but every now and then there is a bug to fix or a new feature to add or a new piece of documentation to write. 

If you are interested, the easiest way to contribute is by submitting pull requests and answering questions from the community. 

Thanks and regards

**Comment by Charliekenney23** [comment]
I'd love to help out. I'm really trying to find a good OSS project to get some experience out of.

**Comment by bogdanned** [comment]
Would love to help out. Ping me at bogdanned32@gmail.com. Best, Bogdan.

**Comment by leandrowd** [comment]
Just sent an email to you. cc: @Charliekenney23 @bogdanned

**Comment by aarohmankad** [comment]
If you're still looking for maintainers, would love to help out! Just started using this component in production, and it's been a dream to work with.

email: aarohmankad@gmail.com

**Comment by leandrowd** [comment]
Hey guys, thanks for expressing interest in helping with this component. 

We have a few bugs and feature requests on our issues tab. Feel free to jump on any of them and please assign it to yourself so we don't do the work twice. 

Any bugfix or feature added should contain enough tests to prove it's working and prevent regressions.

If you don’t like something or think there is a better way of doing it, please create an issue to justify how it will add value to the users or developers of this component. Usually, a simple pros / cons list will be enough. We can discuss from there.

Feel free to throw in any question or suggestion, I want everyone to feel empowered as an owner of this project.

I've also created a gitter channel (https://gitter.im/react-responsive-carousel/Lobby). I will try to answer messages quickly but I'm afraid it can take a day or 2 sometimes. You can still meet each other there to chat and discuss…

Thanks again and any questions, please let me know.

Cheers,
Leandro

**Comment by Trevomatic** [comment]
Hi @leandrowd I'm interested in helping out on at least one of the bugs and have a potential feature request that I could also implement - fade between images. Is this something you'd be interested in me adding to this project?

**Comment by leandrowd** [comment]
Hi @Trevomatic, that's great. Welcome!

Feel free to work on any of the bugs and suggest any features that would please you. As per your question, fade between images would be a nice addition.

**Comment by menarula** [comment]
Is there a way to add multiple items per slide, thanks

**Comment by georgegillams** [comment]
Hey - After the start of Feb, count me in!

**Comment by leandrowd** [comment]
Hey guys, thanks for showing interest and sorry for my absence here, I'm
really out of time nowadays.

For now, there is a bunch of issues open. Anyone interested could start by
looking at them. I'll only be able to look at the pull requests this
weekend. Everything that's ready will be merged and published.

If you have questions, I'll be able to answer them during the weekend as
well.

Thanks again,
Leandro

**Comment by shafqatdotnet** [comment]
https://github.com/pawelgrzybek/siema

**Comment by driskell** [comment]
I’m happy too - though I have limited time I can still help reviews and testing and the occasional code

**Comment by karthikmunsu** [comment]
Im happie to help and contribute to this project

**Comment by leandrowd** [comment]
Hi everyone, the easiest way to help is to start answering issues or submitting pull requests with fixes. After a while, when you feel comfortable contributing, I can make you an official maintainer. 

I will close this issue as this gives the impression that I'm coming here to answer everyone and the reality is that stuff is sitting here for weeks unanswered.

**Comment by kartikeyb** [comment]
Hi everyone, has anyone worked on RTL support for this carousel?

**Comment by denisknk** [comment]
hi, can you tell me how can i get AutoPlay working right after page has been loaded? because now its autoplaying only after my first click on an arrow? Thank you!

**Comment by karthikmunsu** [comment]
@denisknk you can set autoPlay to true.

**Comment by tsirolnik** [comment]
@kartikeyb I think that a simple solution would be adding something like this - 

Adding the prop direction - 
```js
direction: PropTypes.oneOf(['ltr', 'right']),

// default value
direction: 'ltr'
```

Updating the setPosition function, basically, changing the direction of the translate
```js
setPosition = (position, forceReflow) => {
        const list = ReactDOM.findDOMNode(this.listRef);
        const multiplier = this.props.direction === 'ltr' ? 1 : -1;

        ['WebkitTransform', 'MozTransform', 'MsTransform', 'OTransform', 'transform', 'msTransform'].forEach((prop) => {
            list.style[prop] = CSSTranslate(position * multiplier, this.props.axis);
        });
        if (forceReflow) {
            list.offsetLeft;
        }
    };
```

notice the multiplier that was added

I've try to run it but faced problems which I think that are related to the React version, noted here -  #386

**Comment by makasanas** [comment]
Hello I have a doubt in an animation of fade in and out of slider 

I use following but it is not working.

```
<Carousel enterClass="animated fadeIn faster" exitClass="animated fadeOut faster" exitTimeout={400} axis="vertical" showStatus={false} dynamicHeight={true} centerMode={false} centerSlidePercentage={80} showArrows={false} showIndicators={false} showThumbs={false} infiniteLoop={true}>
                        {items}
                    </Carousel>
```

can anyone please help me out for animating like fade in this link

[](http://react-responsive-carousel-custom-transition.surge.sh/?selectedKind=Carousel&selectedStory=fade&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)
