### ISSUE TITLE
Mobile: need double touch to trigger click onClickItem

### ISSUE THREAD

**Issue by dmoli** [leandrowd/react-responsive-carousel#164]
Hi!

In desktop when I press **one** click, the **onClickItem** is called. It`s ok.

But, in mobile I need double touch to trigger the **onClickItem**... it is normal?

I would like to trigger **onClickItem** only with one touch... is possible?

Thanks!

**Comment by jcroft** [comment]
I am seeing this, too.

**Comment by leandrowd** [comment]
Cleaning up old issues. I believe this has been solved already. Feel free to reopen if needed...
