### ISSUE TITLE
Lazy Loading Images

### ISSUE THREAD

**Issue by aarohmankad** [leandrowd/react-responsive-carousel#165]
Would definitely see a performance improvement if the images are lazy loaded. Thumbnails would probably be have to be disabled.

**Comment by oyeanuj** [comment]
@leandrowd In general, maybe there can be a recommended way to lazy load children that are not in view? Seems like it would be overall efficient?

**Comment by leandrowd** [comment]
You can apply any lazy loading technique you want to the content of the slide as far as the slide is there... As far as the carousel is concerned, if we were to add lazy loading behaviour to the carousel itself, I can see it happening in 2 ways:
1) Use a data-src attribute in the image and adjust the carousel to replace it by an src attribute when the image is at a specific distance (-1 /+1 maybe). Adjust thumbs accordingly.
2) Create a new component to handle only image slides (call it <ImageSlide /> as an example) which implements lazy loading behaiour and works with Thumbs.

I don't really have time to deal with this issue but I would be happy to review any pull requests. Just keep in mind that the carousel is not limited to images, it works with any sort of content like videos, text, etc... It's based on slides, not images.

**Comment by dgrahamlong** [comment]
@aarohmankad Pretty late but you could try mapping the children like so

```
<Carousel>
{children.map((child, index) => {
          if (
            index === selectedItem ||
            index === selectedItem + 1 ||
            index === selectedItem - 1
          ) {
            return child;
          } else return <></>;
        })}
/>
</Carousel>
```

That way only children holding hands with the current index will be rendered and fetched. You want to render the surrounding indices in case the user has slow internet, the next image will be fetched vs having to wait every time they click next.
