### ISSUE TITLE
Possibility to pause autoplay (like with onHover)

### ISSUE THREAD

**Issue by LeopoldLerch** [leandrowd/react-responsive-carousel#166]
Hy

I am opening PopUps when clicking on the content of the slider. However, during the popup is visible, i want to stop the autoplay (cause it is quite confusing when having something moving in the background).

Currently I do not see any property besides using the onMouseEnter property of the state in a off-topic way. So, this might be a feature request.

It would also be nice to give my users the possibility to stop/pause the autoplay (but without resetting it to the first image)

**Comment by LeopoldLerch** [comment]
Hy, just for help/info
removing/readding or changing the value of the "autoplay" property does not work. It either resets the component to display the first or does not start auplay at all. In any case, it is not "pausing" in the current state.

As workaround I do currently the following, which works, but might fail in the future:

`    public stopSlider() {
        if (this._carousel) {
            (this._carousel as any).destroyAutoPlay();
        }

    }

    public startSlider() {
        if (this._carousel) {
            (this._carousel as any).setState({ isMouseEntered: false });
            (this._carousel as any).setupAutoPlay();
        }
    }`

(_carousel is a pointer to the carousel-component). 

Maybe that helps for implementation of a "real" property or function. Cause these are obviously functions that work and do this job, but i don´t think they are intended for that use.

**Comment by antoninlanglade** [comment]
I think you can use : 
```
// stop autoPlay
this._carousel.clearAutoPlay();
// start autoPlay
this._carousel.autoPlay();
```

**Comment by LeopoldLerch** [comment]
no, i think i tried that one

but, i recognize correctly this caused 2 problems:
First, autoplay started again at first slide (and not progress from current)
Second, when "pauseonhover" is activated, when leaving the carousel with
mouse, autoplay is still enabled also. so that is no reliable way to pause
it



2017-10-26 16:04 GMT+02:00 Antonin Langlade <notifications@github.com>:

**Comment by leandrowd** [comment]
If you change the value of the prop `autoPlay` to `false`, it will disable auto play.

**Comment by JayMehta97** [comment]
Hi @leandrowd,

On disabling `autoPlay` by passing `false` it stops the carousel as expected, but once we enable it again by again setting `autoPlay` to `true` it goes to next slide and then stops sliding as if `autoPlay` was disabled.

If `stopOnHover` is enabled then how it stops on mouse hover in desktop, it should also stop when someone clicks on it in mobile device as for mobile devices they won't have mouse input. This behaviour is out of the box in owl-carousel.

Can we get this fix?
