### ISSUE TITLE
dynamicHeight is broken if the initial image is cached

### ISSUE THREAD

**Issue by codeincontext** [leandrowd/react-responsive-carousel#167]
The load event listener doesn't trigger if the image is already cached in the browser, which means that `hasMount` never gets set

https://github.com/leandrowd/react-responsive-carousel/blob/72ac37a914e0bff6dee91c4894876ebb712aac3e/src/components/Carousel.js#L116

**Comment by plonko** [comment]
Could this also be affecting SSR? dynamicHeight works fine if save and get HMR reload, but if I refresh the browser the carousel is just the height of the highest image.

**Comment by torreytsui** [comment]
Hi @codeincontext , @plonko, @leandrowd,

I have the same issue and have dug a little bit. Raised a PR as an attempt to fix it.

Mind to give it a look?

https://github.com/leandrowd/react-responsive-carousel/pull/385

**Comment by kimgysen** [comment]
@torreytsui Is there going to be a follow up? I'm using this caroussel for an art website and the black square is really a no-go when the dynamicHeight doesn't work as expected. Currently the autoHeight works randomly and so will display black spots at random.
