### ISSUE TITLE
Bug using Parameters to drive slideshow and caption

### ISSUE THREAD

**Issue by pdw207** [leandrowd/react-responsive-carousel#17]
The README documents how to pass parameters into the carousel. This appears to work with the left and right sliders but clicking the `control dots` triggers directly a `setState` in`changeItem` and bypass the `OnSelectItem` and `OnChange` props.

**Comment by leandrowd** [comment]
Thanks for letting me know. I will fix it in the next release.

**Comment by leandrowd** [comment]
Issue solved, please refer to npm version 2.0.1. (https://www.npmjs.com/package/react-responsive-carousel)
