### ISSUE TITLE
Forward-Next is not responding...

### ISSUE THREAD

**Issue by sp-** [leandrowd/react-responsive-carousel#170]
While the Prev-Back is working fine... the Forward-Next (and the slide position dots ) are not responding to mouse click. Could this be due to conflict of styling?

**Comment by leandrowd** [comment]
Most likely, if you go to http://react-responsive-carousel.js.org/ you will see that everything works.

**Comment by sp-** [comment]
Thanks for the response. Yes, it was on my side. There were conflicting node_modules directory. I did a fresh "npm install" to resolve the problem.

**Comment by leandrowd** [comment]
👍
