### ISSUE TITLE
Thumbnail width issues and miscalculation of itemSize

### ISSUE THREAD

**Issue by dlong500** [leandrowd/react-responsive-carousel#174]
Can anyone explain why the component uses the first thumbnail's `offsetWidth` when attempting to calculate the "size" of the thumbnail container used for moving between thumbnail images?  I'm having issues where the sizing is all wrong sometimes (I think based on the thumbnail images still being not fully loaded or shrunk yet).

So, for example, when I have three images in the carousel and all three thumbnails are visible, it still shows the "right arrow", and clicking on the arrow (or the second image) moves *all three thumbnails* out of view.  Clicking the right arrow again continues to move them further out of view.  All this is because the position value passed to the `CSSTranslate` function is incorrectly calculated.

What I don't understand is why there is even a need to try to calculate this, because the thumbnail elements are hard-coded in the styling to be 80px wide plus 6px right margin.  If I simply set `this.itemSize` to a hard-coded 86px in the `updateSizes` function of `Thumbs.js` everything appears to work find on my end and I no longer have issues with moving between thumbnails.

Am I missing some other reason why it was done this way?

**Comment by leandrowd** [comment]
Hi @dlong500, 

The styles can be overridden as most users will want to change the look and feel to adjust to their websites/apps. For this reason, it's important to calculate the thumbnail size. One could argue that would be better to use a prop for setting the thumb size and I would agree but unfortunately, I don't have time to implement all the suggestions. If you have a better idea or approach, feel free to submit a PR.

In regards to the problem you mentioned where the "sizing is all wrong sometimes", could you demonstrate it through forking this [codepen](https://codepen.io/leandrowd/pen/xLvOPd)?

**Comment by dlong500** [comment]
Because I've got it integrated into my app right now it might take me a while to boil it down and reproduce on codepen.  The root of the issue may be that I'm using server-side rendering in my react codebase.  I'll try to submit a PR when I get a chance to at least accept the thumbnail size as a prop as a last resort.

Thanks for the feedback.

**Comment by leandrowd** [comment]
Hi @dlong500, I think that most likely you have some css rule that is conflicting with one of the carousel rules. Check for styles applied to tags, or if you have a class with the same name. 

I plan to adopt some sort of scoped styles (css modules, styled-components, not sure which one yet) in the future, which would most likely avoid most css conflicts, but I don't have time right now.

For now, can we consider that your question was answered and close this issue?

**Comment by dlong500** [comment]
It's not CSS rule issues because the problem doesn't seem to occur if I disable server-side rendering, and upon further testing if I resize the browser window after page loads the problem appears to correct itself, so there is definitely some issue with the initial load on server-side rendering where the `itemSize` calculation is being miscalculated.

When I get the chance I will open a PR for the thumbnail size as a prop.

**Comment by dlong500** [comment]
I'm working on a PR for this, but I'd like a little clarification on the build process.

Wouldn't it make more sense to have the build files left out of the repo?  They could potentially be built using the `prepare` run-script before publishing to NPM (and also during an install from a direct git dependency).  That way the repo is less cluttered and you wouldn't have people trying to submit PRs with changes to those files.

**Comment by leandrowd** [comment]
Hi @dlong500, the reason for the dist folder to be published is so we have access to CDNs that can serve GitHub files and use them in codepen and other similar tools

**Comment by dlong500** [comment]
Ok, that's a decent reason.  I've created PR #177 for the thumbWidth property.  Take a look when you get a chance.  Thanks!

**Comment by leandrowd** [comment]
Thanks. Already merged and published as 3.1.26
