### ISSUE TITLE
Aligning the images to center

### ISSUE THREAD

**Issue by sasankjonna** [leandrowd/react-responsive-carousel#175]
Hi there

Here is the pen link : https://codepen.io/sasankj/pen/boNpyW

I reduced the width and set it o 700px.
Now I need to align the carousel to center of my page. It is currently left aligned.
I tried playing with styles with no luck.

Any quick way to fix it?

Thanks
SJ

**Comment by leandrowd** [comment]
Hi @sasankjonna, you can add your own custom css. I've changed your example, have a look here: https://codepen.io/anon/pen/wrBJgR

**Comment by leandrowd** [comment]
Hi @sasankjonna, I believe your question was answered so I'm closing this issue. Feel free to reopen if you find it relevant.

**Comment by sasankjonna** [comment]
Hey, Yes thanks...I was able to work with it.
