### ISSUE TITLE
Possibility of moving CDN functionality to unpkg

### ISSUE THREAD

**Issue by dlong500** [leandrowd/react-responsive-carousel#178]
In another issue you mentioned the reason the lib folder is committed to the repo is for CDN purposes (for use with codepen, etc).

I understand that, but I thought I'd at least mention an alternative specifically designed for exactly the purpose of service as a CDN for npm published content:
[unpkg](https://unpkg.com/)

`unpkg` automatically allows any content on npm to be loaded as if it were a CDN, including allowing specifying versions or tags, so it is actually much more flexible than just referencing files directly from the repo.  It's been around for a while and even Facebook is directing users to use it for react itself.

No pressure, but doing things that way would remove the need to keep any generated files in the repo.

**Comment by leandrowd** [comment]
Hi @dlong500 , if you are keen on pursuing this change, please go for it...

**Comment by dlong500** [comment]
Just to clarify, are you wanting a PR for this?

The only steps I see necessary are:
1. Taking any links that point directly to github and pointing them to unpkg
2. Adding the lib folder to .gitignore

Interestingly, I see that the codepen demo is actually already using pkgzip.com (which looks similar to unpkg).  However, unless I'm missing something the main documentation site (http://react-responsive-carousel.js.org) is not coming from this repo, so that would need to be updated as well.

Finally, one additional step that would help developers trying to test out features in forks or branches would be to utillize the new `prepare` npm script, as that would allow someone to `npm install` or `yarn add` directly from a git URL and have the build run as part of the installation so it would be functionally equivalent to installing directly from the npm repository.

**Comment by dlong500** [comment]
Ah, I realized the http://react-responsive-carousel.js.org URL is just pointing to this repo and the content is coming from /src/index.html.  So that should be relatively easy to update as well.

**Comment by leandrowd** [comment]
Hi @dlong500 , I'm not able to dedicate time to this component at the moment. I'm only merging or replying to issues from my mobile when possible. The only time I've spent on this from a computer recently was to publish the PR contributed by other members to npm. I'm purely relying on contributions ATM! 

I thank you for the suggestion. When things change I might be able to do it myself. No ETA promised though.
