### ISSUE TITLE
Uncaught Error: Element ref was specified as a string (carouselWrapper)

### ISSUE THREAD

**Issue by sachinkaria** [leandrowd/react-responsive-carousel#183]
Hey,

Currently trying to install and run the carousel with Node 6.11.3, React 16.0.0 and react-dom 16.0.0 and running in to the following error:

`react-dom.development.js:65 Uncaught Error: Element ref was specified as a string (carouselWrapper) but no owner was set. You may have multiple copies of React loaded.`

At the moment simply configured the carousel in the most basic form below:

```
import React, { Component } from 'react';
import { Carousel as Slider } from 'react-responsive-carousel';


class Carousel extends Component {
  render() {
    return (
      <Slider>
        <div>
          <p>Legend 1</p>
        </div>
        <div>
          <p>Legend 2</p>
        </div>
        <div>
          <p>Legend 3</p>
        </div>
      </Slider>
    );
  }
}

export default Carousel;
```

**Comment by leandrowd** [comment]
Hi @sachinkaria,  You can try setting an alias to your local copy of react while you wait for an update of this library.
