### ISSUE TITLE
Webpack BabiliPlugin: ERROR in unknown: Invalid typeof value

### ISSUE THREAD

**Issue by valorloff** [leandrowd/react-responsive-carousel#186]
Hi!
Upon attempt production build with:
```
,
    plugins: [
        new webpack.DefinePlugin({
            "process.env": {
                NODE_ENV: JSON.stringify("production")
            }
        }),
        new BabiliPlugin()
    ]
```
webpack crash with:
`ERROR in unknown: Invalid typeof value`
This does not happen if i remove the Carousel

**Comment by leandrowd** [comment]
Hi @valorloff, if you find the solution, could you please submit a PR? I won't have time to investigate.

**Comment by CaptainN** [comment]
I'm getting a similar issue. Were you able to figure out what causes this?

**Comment by leandrowd** [comment]
Cleaning up old issues. Feel free to reopen if needed...

**Comment by didnotwant** [comment]
@valorloff, @CaptainN: I know it’s pretty old but I encountered strictly related problem while working with Sentry and I described some details (and a workaround to that) in an issue: https://github.com/getsentry/sentry-javascript/issues/3336
I’m not sure if you still need it but maybe there’s any person who can save some time and nerves.
