### ISSUE TITLE
Next image overflowing/overlapping viewport

### ISSUE THREAD

**Issue by AndrewBrough** [leandrowd/react-responsive-carousel#189]
This is hardly noticable if the carousel has only a handful of slides, but there is an overlap of the next image that gets larger the farther down the list of items the carousel is displaying.

e.g.
item 6 in carousel
![capture2](https://user-images.githubusercontent.com/5230219/32229579-88724ac8-be27-11e7-9787-2eb12f1db979.PNG)

vs. item 60~
![capture](https://user-images.githubusercontent.com/5230219/32229507-5a8bc83c-be27-11e7-8dc6-e30dea01debb.PNG)

I'm assuming this is a floating point rounding error.

using
react 15.6.1
react-responsive-carousel 3.1.27

**Comment by leandrowd** [comment]
Hi @AndrewBrough, 

Thanks for raising the issue.

Could you also give more context of the problem? Is it happening in every browser?

I won't have time to fix it anytime soon but I would be able to review and merge PRs if you are keen on fixing it yourself.

**Comment by AndrewBrough** [comment]
I'll take a look at it if I have the time this week.

I also need to do more browser testing but it happens in chrome latest.

**Comment by leandrowd** [comment]
Hey @AndrewBrough, I'm testing at http://react-responsive-carousel.js.org/ and it seems to be ok. Can you please check if you get the same problem there?

**Comment by leandrowd** [comment]
Cleaning up old issues and I believe this has been solved already. Feel free to reopen if needed.
