### ISSUE TITLE
centerSlideMode and centerSlidePercentage are missing from index.d.ts

### ISSUE THREAD

**Issue by 29er** [leandrowd/react-responsive-carousel#195]
after banging my head wondering why I was getting TS errors on this, I noticed centerMode and centerSlidePercentage are missing from the CarouselProps interface.
there could be others too. please update these. thanks

**Comment by leandrowd** [comment]
cc @khanhfumaster

**Comment by tsekityam** [comment]
This should be fixed by #208. However, I would like to know when will be a release contains this fix. I would like to use these properties in my project.
