### ISSUE TITLE
Don't use absolute path in css

### ISSUE THREAD

**Issue by yesmeck** [leandrowd/react-responsive-carousel#20]
https://github.com/leandrowd/react-responsive-carousel/blob/master/src%2Fstyles%2F_icons.scss#L21-L25

These absolute path will break when `styles` folder is not under root path.

**Comment by leandrowd** [comment]
Each project will have different requirements for where to place the files. It should be solved within the project. I can't see anyway to be flexible enough and support any kind of folder structure from the plugin.

Please, let me know your thoughts.

**Comment by leandrowd** [comment]
Closing the issue. If you have a suggestion feel free to re-open it.
