### ISSUE TITLE
Arrow keys don't work in IE11/Edge

### ISSUE THREAD

**Issue by jzeltman** [leandrowd/react-responsive-carousel#200]
https://www.pgatour.com/photogallery1.html link to reproduce

Arrow key navigation works as expected on chrome, firefox, safari, opera, but doesn't work at all on IE11 nor edge.

**Comment by leandrowd** [comment]
Hey @jzeltman, thanks for raising this.
I can't fix this problem right now. The fastest way to get it to work would be you submitting a PR. I can review and release if you do.
