### ISSUE TITLE
How to change slide from within function on child item in carousel?

### ISSUE THREAD

**Issue by yeezysallonyoursofa** [leandrowd/react-responsive-carousel#202]
Is there a way to do this code below? Or a way to specify the starting slide so I can use setState to change which slide to go to?

```
<Carousel>
 <div onClick={()=>{this.goToSlide(2)}> Slide 1 </div>
 <div onClick={()=>{this.goToSlide(3)}> Slide 2 </div>
...
</Carousel>
```

**Comment by leandrowd** [comment]
Hey @yeezysallonyoursofa, you need to explicitly pass a prop `selectedItem` and your function needs to cause an update of the prop. Hope it helps...
