### ISSUE TITLE
axis 'vertical' and horizontal issue

### ISSUE THREAD

**Issue by theshahzaib5** [leandrowd/react-responsive-carousel#203]
On applying vertical to axis it change the direction of big images but didn't change the direction of thumbnails which is wrong in case of vertical thumbnails should be on right or left, or might be there is an option to adjust thumbnail on left or right

**Comment by leandrowd** [comment]
That could be a good addition. Contributions welcome.

**Comment by wal-shahzaib** [comment]
OK :) thanks :)
