### ISSUE TITLE
Does This Work With React v16?

### ISSUE THREAD

**Issue by dschinkel** [leandrowd/react-responsive-carousel#205]
Has anyone used this successfully over React v16?  Did you have any issues on that version of React with this?  Just checking before I try to play with it.

also is there already a way to configure this to work like react-slick where you have right and left arrows to navigate the carousel?  react-slick is not compatible with React 16 so I'm looking for an alternative carousel.

**Comment by leandrowd** [comment]
I haven't tested it myself but I don't see why it wouldn't work. This component is open source so if you test and find a problem, feel free to submit a pull request.

**Comment by dschinkel** [comment]
thanks.  Do you know if the arrow clicking here (right and left arrows) is out of box or I have to code my own?  Looks like we need to code our own but it's be nice to just grab the code for the ` onChange={onChange}` that you have here but can't find the source: http://react-responsive-carousel.js.org

**Comment by leandrowd** [comment]
If you have everything setup correctly you will get a fully functional carousel out of the box. If you want to create your own UI elements, you will need to change props of the carousel. Look for "external controls" at the storybook examples...

**Comment by rm-hull** [comment]
I have been using it with React 16.2.0, and haven't seen any issues yet

**Comment by dbvrac** [comment]
I'm not getting it to work with react 16.8.6. I'm using the [electron-react-boilerplate](https://electron-react-boilerplate.js.org/) as a starting point, with Material-UI v4.x. The error I'm getting in my IDE is in the import statement 
`Cannot resolve symbol 'Carousel'`
- Node 10.16.0
- Yarn 1.16.0
