### ISSUE TITLE
Thumbs not displayed for Video Embed + Video does not Stop when sliding to next image/ video

### ISSUE THREAD

**Issue by kdgit1** [leandrowd/react-responsive-carousel#206]
1. Thumbs for a video include do not display, whereas those for images do show correctly
2. Video(s) playing / audio does not stop when sliding to next  image or video. Is there an easy fix for it ?

Thank you.

**Comment by leandrowd** [comment]
There is no way to extract a thumbnail from a video at the moment. Your need to stop/play videos using the onChange handler. This component only provides the slide behaviour and would be too overkill to try and support this sort of thing or of the box. You can add an image next to the video to be used as thumb of you want or you can disable thumbs.

**Comment by kdgit1** [comment]
Thanks for your quick response - will looks into it as suggested.
However - stopping playing of the video is mostly a  standard behavior for a component of this nature and would be nice to have it as default here as well.

**Comment by stonecold123** [comment]
@leandrowd 
Yes, I'm also looking for a method to override thumbs for video content.

**Comment by leandrowd** [comment]
Hey guys, this is not possible at the moment. I think we could create a parameter to pass down the thumb for each slide. If any of you are keen on trying it I'll happily review the code and publish it.

**Comment by marquez138** [comment]
> 1. Thumbs for a video include do not display, whereas those for images do show correctly
> 2. Video(s) playing / audio does not stop when sliding to next  image or video. Is there an easy fix for it ?
> 
> Thank you.

Hi were you able to figure out a fix for the video restarting on slide change?

**Comment by sylvainfraissenet** [comment]
Hi, 
Same issue.
I've tried a workarround saw in closed issues : 
                                    <video width="100%" height="100%"  controls>
                                    <img src="/Images1/video_preview.png"/>
                                         <source src={item} type="video/mp4"/>
                                    </video>
And the thumbnail does not appear..
any idea ?
Thanks

**Comment by sylvainfraissenet** [comment]
<video width="100%" height="100%"  controls>
                                    <img src="#/>
                                        
                                    </video>

**Comment by leandrowd** [comment]
I know it has been a while since this request was open but now we finally support this. Check it out if still useful: https://github.com/leandrowd/react-responsive-carousel/blob/master/stories/index.js#L458

**Comment by bhamlefty** [comment]
> I know it has been a while since this request was open but now we finally support this. Check it out if still useful: https://github.com/leandrowd/react-responsive-carousel/blob/master/stories/index.js#L458

I am getting a 404 for the link you provided.
