### ISSUE TITLE
Transition with high resolution images

### ISSUE THREAD

**Issue by devlemire** [leandrowd/react-responsive-carousel#209]
I'm noticing that the higher the resolution of images you use, the more noticeable lag there is with the transition. Especially on the last transition when it has to cycle through all the images to get back to the first one. Has any one else noticed this? I'm using images that are 4460 x 2973 pixels.

**Comment by leandrowd** [comment]
Sorry to ask but why would you use an image this big? 

Anyway, the carousel uses css transition combined with translate3d so it should be quick. 

Out of curiosity, how many images are you using? 

I've created an example at https://www.webpackbin.com/bins/-L46ElXd7aNJcIGyKLq- and seems to work fine. Could you copy this example and publish one where I can see the problem? Thanks

**Comment by devlemire** [comment]
Images with that resolution look crisp and make the carousel that much better. I was using 15 high resolution pictures at the time.

Here's how I'm using the library in my code base:

```
// Carousel
import { Carousel as ResponsiveCarousel } from 'react-responsive-carousel';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
// Images
import images from '../../assets/HomeCarousel';

<ResponsiveCarousel showArrows={true}
                                      infiniteLoop={true}
                                      autoPlay={true}
                                      showStatus={false}
                                      showThumbs={false}
                                      interval={ 10000 }
                                      className="Carousel">
  {
    images.map( ( image, index ) => (
      <div key={ `image-${ index }` } className="Carousel__image-container">
        <img src={ image } alt="" />
      </div>
    ))
  }
</ResponsiveCarousel>
```

**Comment by devlemire** [comment]
I tried to your webpackbin example but it kept throwing an error message at me no matter how many times I tried to refresh it. Sorry :/

**Comment by leandrowd** [comment]
Just be sure you are not wasting your pixels. Check if the resolution you
are using is ok for the web and avoid resizing images in the browser.
