### ISSUE TITLE
Thumbnails do not update with images when state changes. 

### ISSUE THREAD

**Issue by paulgasbarra** [leandrowd/react-responsive-carousel#213]
I am polling an endpoint for new images using a setInterval() function. 

Every interval I set the state of a responses array. 

```javascript
 render(){
    return (
      <Carousel
        selectedItem={this.state.selectedItem}
        onClickThumb={this._onClickThumb.bind(this)}
      >
        {
          this.state.responses.map(function(url){
              return <img src={url} key={url} />
            }
          )
        }
      </Carousel>
    )
  }
}
```
When I get a new image, the image is present in  "ul.control-dots" but not in the thumbs.

The thumbs do not update along with the changing images. 

 Is there a way to refresh the thumbs when I add or remove images?

**Comment by koonfaixie** [comment]
How I solved this was by adding another condition to componentDidUpdate;
if the children changes, invoke setupThumbs

if ((!prevProps.children && this.props.children && !this.state.initialized ) || prevProps.children != this.props.children) {
                this.setupThumbs();
            }

**Comment by driskell** [comment]
I will try a PR to address this shortly. I just noticed some glitching with the arrows taking a second render to appear so will try clean everything nicely and also expose updateSizes so there’s an API to hit if the carousel dimensions needs updating.

**Comment by justin22** [comment]
Weirdly, this issue still happens for me.
The slider images gets updated, but not the thumbs. I have gone through the [PR](https://github.com/leandrowd/react-responsive-carousel/pull/229), but couldn't find the solution.
```
<Carousel 
  showArrows={true}
  showStatus={false}
  showThumbs={true}
  showIndicators={false}
  swipeable={true}
  infiniteLoop={false}
  useKeyboardArrows={true}
>
  {
    this.props.images.map((value, index) => {
      return (
       <div key={index}>
         <img 
           key={index}
           src={value.image} 
         />
      </div>            
     )
   })
  }
</Carousel>
```
