### ISSUE TITLE
destroyCarousel method does not work correctly when the component mounts only briefly

### ISSUE THREAD

**Issue by garrettlr** [leandrowd/react-responsive-carousel#217]
Hi,

We're using RRC in production to create a carousel on our landing page, which redirects logged in users to our web app immediately. In this particular case there's not enough time passing for this.state.initialized to be set, leading to endless attempts to set State while the carousel is unmounted. 

Is there a reason to check this value before destroying? If so, consider changing it to an instance variable (this.initialized), which will not suffer from the same asynchronicity issues that state values must deal with. I believe this is generally considered a best practice for dealing with things such as timers, which I believe to be the driving issue behind this bug (autoPlay).

I will submit a PR addressing this shortly. 

![screen shot 2018-02-06 at 4 00 56 pm](https://user-images.githubusercontent.com/27841188/35891001-fb93a8a4-0b56-11e8-826a-1ddbb9b166be.png)

![screen shot 2018-02-06 at 4 02 04 pm](https://user-images.githubusercontent.com/27841188/35891030-1edd763c-0b57-11e8-8d61-5cc64340b2ff.png)

**Comment by leandrowd** [comment]
That'd be great! Waiting for your PR.

**Comment by leandrowd** [comment]
Is this still an issue?
