### ISSUE TITLE
Codepen not working

### ISSUE THREAD

**Issue by JonathanWbn** [leandrowd/react-responsive-carousel#218]
Since the Codepen is broken as of now, I suggest replacing it with a CodeSandbox.

I created one [here](https://codesandbox.io/s/ll1r746xnz), that seems to work just fine.

Maybe @leandrowd you want to create your own, but it literally only takes 2 minutes.

**Comment by leandrowd** [comment]
Thanks for setting it up @JonathanWbn. I've forked and updated the README with my link. https://codesandbox.io/s/lp602ljjj7
