### ISSUE TITLE
Should accept any kind of children, not only images

### ISSUE THREAD

**Issue by mping** [leandrowd/react-responsive-carousel#22]
It would be great if we could pass any kind of children instead of only images

**Comment by oyeanuj** [comment]
+1 to this, this would allow for immense flexibility in use-cases.

**Comment by leandrowd** [comment]
Thanks for raising it, I'll fix it as soon as I find some free time... Cheers.

**Comment by leandrowd** [comment]
This feature has been implemented in the latest version. Please update your npm package :)
