### ISSUE TITLE
Import styles error: react-responsive-carousel/lib/styles/carousel.css or carousel.min.css

### ISSUE THREAD

**Issue by AnoushS** [leandrowd/react-responsive-carousel#220]
ERROR in ./node_modules/react-responsive-carousel/lib/styles/carousel.css
Module parse failed: Unexpected token (10:0)
You may need an appropriate loader to handle this file type.
|       COLOURS
| ********************************************/
| .carousel .control-arrow, .carousel.carousel-slider .control-arrow {
|   -webkit-transition: all 0.25s ease-in;
|   -moz-transition: all 0.25s ease-in;

**Comment by leandrowd** [comment]
Hi @AnoushS, 

Are you using webpack to build your app? The error message you got means that you haven't configured your bundler to load css properly. You can find one example of how to do at https://github.com/leandrowd/demo-react-responsive-carousel-es6/blob/master/index.js

Also, look at https://github.com/webpack-contrib/css-loader

Let me know how it goes.

**Comment by AnoushS** [comment]
I did include "css-loader" and "style-loader" and finally, I was able to use it. Thank you!)

**Comment by Tapudp** [comment]
I'm using Next.js so can someone please tell me how will I be able to add those css and style loaders?

**Comment by jbergeron03** [comment]
Hey @Tapudp 

This is working for me:

```
const withSass = require("@zeit/next-sass");
const withCSS = require("@zeit/next-css");

module.exports = withSass(withCSS());
```

**Comment by MarlonAEC** [comment]
> I did include "css-loader" and "style-loader" and finally, I was able to use it. Thank you!)

how did you do it??? how did you configure webpack... I'm getting the same issue here... :(

**Comment by sailor95** [comment]
@MarlonAEC firstly npm install `style-loader` & `css-loader`, then within your `webpack.config.js`

```js

module: {
  ..., // other configc
  rules: [
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
    }
  ]
}

```

**Comment by gsambrotta** [comment]
> I'm using Next.js so can someone please tell me how will I be able to add those css and style loaders?
> 
> My `next.config.js` file includes the following code:
> 
> ```js
> const withSass = require('@zeit/next-sass');
> 
> module.exports = withSass({
>   webpack: config => {
>     // Fixes npm packages that depend on `fs` module
>     config.node = {
>       fs: 'empty'
>     };
> 
>     return config;
>   }
> });
> ```

Probably not relevant for you anymore but for others ending up here from Nextjs.


I included styles in my Carousel component in a Next.js app like this:
`import 'style-loader!css-loader!react-responsive-carousel/lib/styles/carousel.css'`

**Comment by Priyanka-L-K** [comment]
where can i locate webpack.config.js ?

> @MarlonAEC firstly npm install `style-loader` & `css-loader`, then within your `webpack.config.js`
> 
> ```js
> module: {
>   ..., // other configc
>   rules: [
>       {
>         test: /\.css$/,
>         use: ['style-loader', 'css-loader']
>     }
>   ]
> }
> ```

where can i locate webpack.config.js ?
