### ISSUE TITLE
Possible to add more than 1 image per page in slide

### ISSUE THREAD

**Issue by camillecamahort** [leandrowd/react-responsive-carousel#221]
Is it possible to add more than 1 image per page for the carousel? I am using thumbnails and would need 4 on each page. thank you!

**Comment by leandrowd** [comment]
Hi @camillecamahort, this is not a supported use case at the moment. You might be able to achieve similar behaviour by passing centerMode = true and centerSlidePercentage = 25 but I've never tested and I'm not sure if it will work as expected. 

If you do want to implement it properly, I would be happy to review and merge the pull request.

**Comment by leandrowd** [comment]
Can this be closed @camillecamahort ?
