### ISSUE TITLE
conflict with react materialcss overlapping css class defined in react-responsive-carousel 

### ISSUE THREAD

**Issue by kkbeheramca** [leandrowd/react-responsive-carousel#223]
anybody has any idea how to change the class name set in carousel to something else let's  say "carousel-react" in order to put css class names not to conflict with react-materializecss that having same carousel feature and taking css precedence.

**Comment by leandrowd** [comment]
Hi @kkbeheramca, at this moment, there is no easy way to change it. You could send a PR changing it to something like react-responsive-carousel and I would merge it for you.

The real question is, why are you kidding carousel styles from material CSS if you are not using them?

**Comment by kkbeheramca** [comment]
i changed the class name to "react-responsive-carousel" from "carousel" in cssClasses.js like below
exports.default = {
    CAROUSEL: function CAROUSEL(isSlider) {
        return (0, _classnames2.default)({
            "react-responsive-carousel": true,
            "carousel-slider": isSlider
        });
    },


then replace all .carousel classes in  carousel.min.css and carousel.css to get it working as unique class for your library.
i understand your question why to add matierial css carousel if not using , but sometimes exisitng projects have already added those modules , hence i am not going to tampered them removing it . better solution to make it uniquely identifies class name as the name you given  "react-responsive-carousel", this it will not overlap or make conflict with any other modules.

**Comment by leandrowd** [comment]
Can this be closed?
