### ISSUE TITLE
Possible to add multiple images as an array to src in 1 div?

### ISSUE THREAD

**Issue by vatsal28** [leandrowd/react-responsive-carousel#224]
I want to import all the images from a folder and then put them as an array. I want something likethe following example:
```
    const images = importAll(require.context('./', false, /\.(png|jpe?g|svg)$/));
class DemoCarousel extends Component {
    render() {
        return (
            <Carousel className = "Carousel" infiniteLoop={true} showThumbs={false} showStatus={false}>
                <div>
                    <img src={images} />
                </div>
            </Carousel>
        );
    }
}

```

But this is not working. How will I achieve this?
Any help is appreciated !

**Comment by leandrowd** [comment]
You could iterate on the images object to create a list of slides.

Depending on the number of images it might be very slow.

What's your use case?

**Comment by vatsal28** [comment]
Thanks for the quick reply!
There would be a certain number of images uploaded in a folder and I have to import and preview (with scrolling) all of them in this component.

How do I iterate on the images object to create that list?
Sorry for the silly questions, I'm new to react and JS as well.
