### ISSUE TITLE
How do I access the selectedItem state?

### ISSUE THREAD

**Issue by vatsal28** [leandrowd/react-responsive-carousel#225]
I want to trigger a function based on the "selectedItem" state  of the Carousel element.
For example:

Whenever I click on the left or right arrow, the "selectedItem" state changes accordingly (0,1,2, etc. ) and I want to access that number in the state. How do I achieve that?

**Comment by leandrowd** [comment]
You can use the onChange handler. Check the docs and the storybook for examples. It's all on the readme :)

**Comment by vatsal28** [comment]
The storybook link is giving me a 404 error :/

**Comment by leandrowd** [comment]
Oh, thanks for letting me know. I'll check what's happening tomorrow when I'm on a computer. For now, check https://github.com/leandrowd/react-responsive-carousel/blob/master/stories/index.js#L59 for reference.

**Comment by vatsal28** [comment]
This worked to some extent. This is the code:

```
class DemoCarousel extends Component {
constructor(props){
    super(props);
    this.state = {currentSlide:0};
}
updateCurrentSlide = (index) => {
        const { currentSlide } = this.state;

        if (currentSlide !== index) {
            this.setState({
                currentSlide: index
            });
        }
}
    render() {
        return (
            <Carousel className = "Carousel" infiniteLoop={true} showThumbs={false} showStatus={true} onChange={this.updateCurrentSlide}>
                 {images.map((singleImage, i) => <img src={singleImage} key={i} />)}
            </Carousel>
        );
    }
}

```


But when I'm clicking on the "next" arrow, it goes back to first image instead of the next one. It is cycling only through 2 images even though there are 8.

**Comment by vatsal28** [comment]
Figured it out . Thanks!

**Comment by leandrowd** [comment]
I republished the storybooks and they seem to be fine now :)

**Comment by vatsal28** [comment]
Thanks!

**Comment by Calicorio** [comment]
Hi @vatsal28 , I'm having the same problem as you had : "when I'm clicking on the "next" arrow, it goes back to first image instead of the next one. It is cycling only through 2 images even though there are 8". How did you solve it?

**Comment by rubangarmon** [comment]
Hi @vatsal28  and @Calicorio what did you do for solving it?

**Comment by rubangarmon** [comment]
onChange() method is being called twice when I update any state property. It only calls the first 2 slices. I need to capture the event for updating styles on next slide.

**Comment by zxpectre** [comment]
> Hi @vatsal28 and @Calicorio what did you do for solving it?

Any news? please I'm dying against the same issue here

**Comment by zxpectre** [comment]
I solved it. 
Hope it helps somebody.
The bug goes away when controlling it externally. 
```

const ExternalControlledCarousel = (props)=>{
  //This wrapper not only allows more controll,but also fixes an uggly bug where native next and prev buttons don't work well on more than 2 items
  const {onChange,children} = props;
  const [values, setValues] = React.useState({
    currentSlide:0,
  });

  const next = () => {
      setValues({ ...values, currentSlide: values.currentSlide+1 });
  }
  const prev = () => {
      setValues({ ...values, currentSlide: values.currentSlide-1 });
  }
  const update = (index,component) => {
    if (onChange)
      onChange(index,component);
    if (values.currentSlide !== index){
      setValues({ ...values, currentSlide: index });
    }
  }

  return (
    <Carousel  {...props} selectedItem={values.currentSlide} onChange={update}>
        { children }
    </Carousel>
  );
}
```

**Comment by Calicorio** [comment]
> Hi @vatsal28 and @Calicorio what did you do for solving it?

Since it is a doubt I had more than a year ago I can't remember how I solved it, but it seems that @zxpectre has found a solution :)
