### ISSUE TITLE
Can't see arrows next to thumbnail imgs

### ISSUE THREAD

**Issue by DaltheCow** [leandrowd/react-responsive-carousel#227]
Looking in the css and stuff and can't figure out why the arrows next to the thumbnails won't show up

**Comment by leandrowd** [comment]
Did you try to simulate your problem with https://codesandbox.io/s/lp602ljjj7 ?

**Comment by DaltheCow** [comment]
yeah they don't show up there either. It is just an invisible box with cursor:pointer and when inspect I can easily find it and the ::before that makes the arrow but it doesn't naturally show up like the arrows around the main image. If you open the sandbox do you see the arrows by the thumbnail images? They don't show up for my friend and I both.

I was just playing with it and when I change the color of the border-left: on the arrows from white to something darker they become visible

**Comment by leandrowd** [comment]
The arrows are white so if your background is also white then you wouldn't see them.
You can add a custom css like the one below to override it: 

```
.carousel .control-prev.control-arrow:before,
.carousel .control-next.control-arrow:before {
    border-right: 8px solid #000;
}
```

**Comment by driskell** [comment]
@leandrowd I noticed the demo pages and `gulp` page are white background so they're not visible there. Is it perhaps something to change, maybe to a light grey so they still work for dark backgrounds? It threw me a little in testing :)

**Comment by DaltheCow** [comment]
Thank you! I don't know how I didn't realize that. I guess I was working with a white background so I never bothered changing it. Even when I changed the border color it didn't click that the reason it didn't show before was because of a same color background. Cool good to know it is just from the arrow color.

**Comment by leandrowd** [comment]
Any reason for reopening this one?

**Comment by DaltheCow** [comment]
I'm sorry, I am not sure if I did that intentionally, I can't remember why I would have reopened it.

**Comment by kritarth2121** [comment]
The answer is add this , The arrows are white so if your background is also white then you wouldn't see them.
Completely agreeing with @leandrowd 
.carousel .control-prev.control-arrow:before
{
    border-right: 8px solid #000;
}

.carousel .control-next.control-arrow:before
{
    border-left: 8px solid #000;
}
