### ISSUE TITLE
Mobile scrolling is jerky

### ISSUE THREAD

**Issue by mrjonanderson** [leandrowd/react-responsive-carousel#231]
![skip](https://user-images.githubusercontent.com/29313711/38118078-53540744-336d-11e8-9bcc-f4aa47334789.gif)

The mobile scrolling is a bit jerky on mobile web, as it goes back to the start of the slide before completing the slide.  Here is how I initialize the Carousel, and I have also included carousel.global.css in the project. The scrolling is not jerky when done through the keyboard on the desktop, only for swipe. Let me know if I am doing something wrong, or missed including something. Thank you, Jon 
` <Carousel
              showThumbs={ false }
              showArrows={ false }
              showIndicators={ true }
              selectedItem={ selectedItem }
              useKeyboardArrows={ true }
              infiniteLoop={ true }
              onChange={ (val) => this.selectItem(val) }>

  selectItem(val) {
    const { selectedItem } = this.state;
    if (selectedItem !== val) {
      this.setState({
          selectedItem: val
      });
    }
  }
`

**Comment by leandrowd** [comment]
If you remove your onChange handler, will it work fine?

**Comment by mrjonanderson** [comment]
That works perfectly fine for me. Can't believe I didn't try that. Thank you so much for the quick response.
