### ISSUE TITLE
Conditional slide rendering

### ISSUE THREAD

**Issue by locborgtus** [leandrowd/react-responsive-carousel#235]
Consider the follow code, mostly from the README. I added a condition render for the first slide.

I will get either a type error in Code Sandbox, or I will get an empty slide on my local clone.

What is the best way to conditionally rendering slides within the carousel?

```js
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { Carousel } from 'react-responsive-carousel';

class DemoCarousel extends Component {
    render() {
        return (
            <Carousel>
                {false ? 
                 (<div>
                  <img src="http://lorempixel.com/output/cats-q-c-640-480-1.jpg" />
                  <p className="legend">Legend 0</p>
                  </div>) : null
                }
                <div>
                    <img src="assets/1.jpeg" />
                    <p className="legend">Legend 1</p>
                </div>
                <div>
                    <img src="assets/2.jpeg" />
                    <p className="legend">Legend 2</p>
                </div>
                <div>
                    <img src="assets/3.jpeg" />
                    <p className="legend">Legend 3</p>
                </div>
            </Carousel>
        );
    }
});
```

**Comment by leandrowd** [comment]
If you filter out the null values, it should just work...

The problem you have now is probably because some setup methods rely on
index 0 to bootstrap the carousel.

**Comment by leandrowd** [comment]
Did filtering the null values out solve the problem?

**Comment by dineshgm4u** [comment]
I am facing the same issue and would like to know if this was ever resolved? can you elaborate what you mean by filtering the null values?

**Comment by nok91** [comment]
I'm facing the same issue too, can you please explain more in detail...
Thanks

**Comment by MichaelWheldon** [comment]
One of your slides is returning null, which will still add a blank slide. You need to filter out (remove) this value before returning. A quick and dirty way off the top of my head would be to:

- move all your slides into an array and wrap it in a function which removes all null values (lodash's _.compact would be handy here, but however you like 🤷‍♂), then map over that array to return each slide. Something like this:

```
const images = _.**compact**([img1: {src: 'foo', legend: 'bar'}, **yourCondition** && img2: {src: 'foo', legend: 'bar'}, img3: {src: 'foo', legend: 'bar'}]);
const slides = _.map(images, (slide, index) => <div><img src={slide.src} /><p>{slide.legend}</p></div>);
...
return {slides}
```

**Comment by UPLukeet** [comment]
Was this ever fixed?
