### ISSUE TITLE
Control arrowNext and arrowPrev not updating properly

### ISSUE THREAD

**Issue by thehendrix** [leandrowd/react-responsive-carousel#236]
If I have a function which returns 1 array containing 3 div tags and 1 div tag together in the carousel, there will be 4 dots and 4 slides loaded correctly. But, the arrowNext and arrowPrev will think there are only 2 slides in the Carousel instead of 4.

`populateDivs() {`
` const arr = [src1, src2, src3];`

 ` return arr.map(source => (`
    `<div>{source}</div>`
  `);`
`}`

`<Carousel`
   `infiniteLoop`
   `showStatus={false}`
   `showThumbs={false}`
` >`
      `<div>stuff</div>`
      `{this.populateDivs()}`
`</Carousel>`

If I load only `{this.populateDivs()}` into the Carousel, the arrow controls will see 3 divs which is correct.

**Comment by leandrowd** [comment]
Hi @thehendrix, this sounds like a weird bug to be happening. Could you prepare an example using our sandbox (https://codesandbox.io/s/lp602ljjj7)? Send us the link, please.
