### ISSUE TITLE
regression in 3.1.35 broke dynamicHeight

### ISSUE THREAD

**Issue by stipsan** [leandrowd/react-responsive-carousel#237]
This happens on the storybook here: http://react-responsive-carousel.js.org/storybook/?selectedKind=Carousel&selectedStory=dynamic%20height%20images&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

It happens because the check is started inside render: https://github.com/leandrowd/react-responsive-carousel/blob/8e3b26ea1d094d2848cdacf0a247452bdc2dc772/src/components/Carousel.js#L605-L606

Proposed solution is to move the `this.state.hasMount` check two lines up https://github.com/leandrowd/react-responsive-carousel/blob/8e3b26ea1d094d2848cdacf0a247452bdc2dc772/src/components/Carousel.js#L465

I can do a PR later if nobody beats me to it (probably next week, I have to follow up on a few PRs on projects I maintain already) 😃

**Comment by driskell** [comment]
Ah thanks. This may be my fault, apologies. The adjustments made mean flicker is reduced so renders happen quicker and that likely related. I’ll take a look soon I’ll let you know when I start so we don’t overlap :)

**Comment by stipsan** [comment]
Cool, no worries 😄

**Comment by leandrowd** [comment]
Could someone confirm if this issue is still valid with the latest release?

**Comment by stipsan** [comment]
Confirmed fixed 👍

**Comment by leandrowd** [comment]
Cool, thanks. Closing this...
