### ISSUE TITLE
Should be Zoom functionality as well

### ISSUE THREAD

**Issue by omvaishnav** [leandrowd/react-responsive-carousel#239]
Thanks for this carousel. This plugin is awesome and has many customization options as well. It would be a bonus if you can add zoom functionality as well so if user tap on the image, the image can zoom and the user can pan it (it would be a very useful feature for any production company to show their products with a zooming functionality).

**Comment by leandrowd** [comment]
Thanks for opening this ticket @omvaishnav. 
I don't think it fits well as part of this component because not every carousel needs this behaviour. 
However, it should be pretty straightforward for you to add this behaviour to your app if you pass an `onClick` handler to the carousel.
