### ISSUE TITLE
Check for the window object on the server side

### ISSUE THREAD

**Issue by bmamouri** [leandrowd/react-responsive-carousel#24]
The component cannot be rendered on the service side, because the file `has3d.js` read a property of `window` object that does not exist on the server.

Solving the problem is easy, we just need to check if the window object exist at the first place:

    if (window && !window.getComputedStyle) {
        return false;
    }

**Comment by leandrowd** [comment]
Thanks for that, I will have a look as soon as I find some free time!

**Comment by leandrowd** [comment]
Thanks for raising this issue. It has been fixed on the latest version :)
