### ISSUE TITLE
Navigate Previous not rendering corect when a dynamic array of children is used

### ISSUE THREAD

**Issue by RaduCl** [leandrowd/react-responsive-carousel#242]
Hello,
i noticed the prev action is not working when i dynamically update the children array(i am doing this because of a caching system i need to use) so basically i start with two items and increase the children array as i navigate. The issue i found happens when i start the carousel with the last item and navigate prev (i start with `[src1, src2] / selectedItem: 1` then i when i navigate prev i increase the sources array at the head like so `[src0, src1, src2] / selectedItem: 1` selectedItem prop stays 1 but the state updates selectedItem:0  thus jumping to src0 instead of src1 ).
i think the issues is solved by 
```
componentWillReceiveProps (nextProps) {
        if (nextProps.selectedItem !== this.state.selectedItem) {
            this.updateSizes();
        }

        this.moveTo(nextProps.selectedItem);
   
       if (nextProps.autoPlay !== this.props.autoPlay) {
            if (nextProps.autoPlay) {
                this.setupAutoPlay();
            } else {
                this.destroyAutoPlay();
            }
        }
    }
```
pls advice. if you need i can make a pull request with this

**Comment by leandrowd** [comment]
The carousel needs to know the total number of slides in order to function properly. What you can do to make it work with your caching system is to render divs with a fake image and change the src of the image as you need. Do you think this would work for you?

**Comment by RaduCl** [comment]
This issue can be closed. I fixed it another way: by mapping the sources array and returning null for the images that i don't want to be rendered yet. This way the sources elements number does not vary and i get improved perf.
