### ISSUE TITLE
Would like user to have ability to right click and save slideshow images

### ISSUE THREAD

**Issue by violetcrumble** [leandrowd/react-responsive-carousel#243]
Is there a way to enable the browser menu with "Open Image in new Tab", "Save Image As" and those other options? 

I've tried playing with the image's z-index, in case another element was overlapping, but it didn't seem to make a difference. If anyone has ideas of things to try, I would love to see this feature, or even try to implement a change myself. 

What you currently get in a react-responsive-carousel:
![screen shot 2018-05-15 at 11 46 28 am](https://user-images.githubusercontent.com/867105/40068110-d105df7c-5835-11e8-8024-1b42003d4eae.png)

Desired browser menu:
![screen shot 2018-05-15 at 11 47 26 am](https://user-images.githubusercontent.com/867105/40068112-d2fe6664-5835-11e8-9d9d-4d1d2c84f3a2.png)

**Comment by leandrowd** [comment]
Yes, you can add a css rule enabling pointer-events for images. Something like:
```
.carousel .slide img {
      pointer-events: all;
}
```

**Comment by violetcrumble** [comment]
So easy and obvious, but I didn't think of it. Thank you! Probably too simple to consider adding to the carousel as a parameter a developer could pass in.
