### ISSUE TITLE
using multiple carousel in a page with scroll bar

### ISSUE THREAD

**Issue by viveknandhangelella** [leandrowd/react-responsive-carousel#244]
I am using multiple carousels in a page that has scroll when I scroll to and fro then images are rerendering can you please Help

**Comment by leandrowd** [comment]
Could you try to simulate your problem on our codesandbox and share a link here? Use https://codesandbox.io/s/lp602ljjj7 as base.

**Comment by jaredshaunsmith** [comment]
Having this issue as well - as soon as you scroll up or down on the page the carousel resets to the first slide

**Comment by Brudhu** [comment]
I have the same issue described by @jaredshaunsmith, which I think it's different than the one on this issue.
The carousel goes back to the image as soon as the page scrolls up or down.

**Comment by jaredshaunsmith** [comment]
@Brudhu We found a fix for our issue related to a greater component re-rendering issue - see this link: https://medium.com/@ryanflorence/react-context-and-re-renders-react-take-the-wheel-cd1d20663647

replacing `React.Component` with `React.PureComponent` makes the component only re-render when the props/state change and fixed the carousel sliding back to slide 1 on any scroll activity
