### ISSUE TITLE
(mobile only) slide transition restarts from beginning after an unfinished drag/drop gesture

### ISSUE THREAD

**Issue by rondonjon** [leandrowd/react-responsive-carousel#245]
_This applies only to mobile devices and to browsers which have been set to mobile emulation through the developer tools._

**Expected result:** when a user drags a slide from right to left and drops / lets go of the slide before the slide is completely moved to the left, the slider finishes the transition on its own.

**Actual result:** the slider recognizes the incomplete transition, and completes it transition, but before doing so, it resets the position of the slide to where the drag began: This "jump" obstructs the user experience.

**Video example here:** https://ufile.io/v23m2 (.mp4, 1.2 MB)

**Comment by leandrowd** [comment]
Hi @rondonjon, thanks for raising the issue. To be honest, I won't have time to solve this any time soon so I would appreciate if you or anyone else could help. I would happily review and merge any pull request. 

Thanks

**Comment by rondonjon** [comment]
OK, I think I found the problem:

```
        _this.onSwipeEnd = function () {
            //_this.resetPosition(true);     <-- remove this line
            _this.setState({
                swiping: false
            });
            _this.autoPlay();
        };
```

`resetPosition()` calculates a wrong position and "jumps" there before the next `render()` happens and fixes it. The jump is visible and leads to the described effect.

```
{at: "setPosition", newValue: "translate3d(-29.142857142857146%,0,0)"} Carousel.js:271
{at: "setPosition", newValue: "translate3d(-29.42857142857143%,0,0)"} Carousel.js:215
resetPosition() Carousel.js:263
{currentPosition: "0%"} Carousel.js:271
{at: "setPosition", newValue: "translate3d(0%,0,0)"} Carousel.js:594          <-------
<... some time later ...>
{at: "render", transformProp: "translate3d(-100%,0,0)"} Carousel.js:594        <-------
{at: "render", transformProp: "translate3d(-100%,0,0)"}
```

Surprisingly, browsers in desktop mode will make the same mistake, BUT they call `render()` immediately afterwards. Fun fact: the first `render()` call also applies the same wrong value, but another `render()` call follows and fixes it. Since all three calls (`resetPosition()`, `render()`, `render()`) happen in a series, only the (correct) values from the last one get visible:

```
{at: "setPosition", newValue: "translate3d(-26.880222841225628%,0,0)"} Carousel.js:215 
resetPosition() Carousel.js:263
{currentPosition: "0%"} Carousel.js:271
{at: "setPosition", newValue: "translate3d(0%,0,0)"} Carousel.js:594    <------ wrong, but invisible
{at: "render", transformProp: "translate3d(0%,0,0)"} Carousel.js:594    <------ wrong, but invisible
{at: "render", transformProp: "translate3d(-100%,0,0)"} Carousel.js:594    <------ visible
{at: "render", transformProp: "translate3d(-100%,0,0)"} Carousel.js:594
```

Removing `resetPosition` entirely solved the problem for me.

Nevertheless, I would only consider this as a quick fix. I don't know what causes the `render()` calls, and there may be no guarantee for them to even occur in all cases. So the real fix could be to (1.) solve the wrong position calculation and (2.) move the position into the React `state` to avoid further glitches on rerenders.

**Comment by rondonjon** [comment]
Pull Request:
https://github.com/leandrowd/react-responsive-carousel/pull/249
