### ISSUE TITLE
Recommended accessibility updates

### ISSUE THREAD

**Issue by mikeriley131** [leandrowd/react-responsive-carousel#246]
I'm using [react-a11y](https://github.com/reactjs/react-a11y) in my project that I have this package installed in and it's kicking off a few warnings for the carousel.

> Thumbs You have a click handler on a non-interactive element but no `tabIndex` DOM property. The element will not be navigable or interactive by keyboard users.

Recommended fix: https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Thumbs.js#L249
```
const thumbProps = {
  key: index,
  ref: e => this.setThumbsRef(e, index),
  className: itemClass,
  onClick: this.handleClickItem.bind(this, index, this.props.children[index])
  role='button'
  tabIndex={0}
};
```

> Carousel You have a click handler on a non-interactive element but no `tabIndex` DOM property. The element will not be navigable or interactive by keyboard users.

Recommended fix: https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.js#L496
```
const slideProps = {
  ref: (e) => this.setItemsRef(e, index),
  key: 'itemKey' + index,
  className: klass.ITEM(true, index === this.state.selectedItem),
  onClick: this.handleClickItem.bind(this, index, item)
  role='button'
  tabIndex={0}
};
```

Let me know if you'd like me to submit a PR.

**Comment by leandrowd** [comment]
Yeah, a PR would be great!
