### ISSUE TITLE
Carousel is being restarted unintentionally

### ISSUE THREAD

**Issue by Jordanh1996** [leandrowd/react-responsive-carousel#251]
Hello.
I have a component that holds the carousel and when the the parent of the parent of the carousel state changes the carousel returns to the first image...
the hierarchy is as follows Gallery > GallerySlider > Carousel.
when Gallery state changes Carousel is being reset.
I really have no idea how to start to fix such a thing

**Comment by Jordanh1996** [comment]
I fixed it by taking the Carousel out of the Gallery components and placing it in the entire page.
I still don't understand why this issue would start in the first place and why cant i nest the Carousel in the gallery components =/

**Comment by driskell** [comment]
It could be the Gallery is rerendering causing a new Carousel to be created rather than updating it. Is it a public component?

**Comment by Jordanh1996** [comment]
I am not sure what a public component is but I suppose you are right, its what I thought as well, therefore I extracted the carousel into its own component so it wont be affected by re renders caused by the same shared class.
I think this behaviour is not good and should be fixed. Thanks

**Comment by driskell** [comment]
I meant is it open source public so it can be looked at - is there a link to it and do you have example code which reproduces your problem?.

It does seem at the moment a problem with the Gallery component, not Carousel.
