### ISSUE TITLE
infinite scrolling to the right / left

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [leandrowd/react-responsive-carousel#252]
**Current behavior**

If you are on the last item and you slide to the next item (which is technically the first item). It would scroll all the way from the end going back to the first item.

**Wanted behavior**

Scroll seemlessly, so it must simulate an infinite scroll.

**Comment by NamitYadav** [comment]
Is there an ETA on this much wanted feature?

**Comment by etcetera8** [comment]
If no ones working on this, I don't mind taking it on and pr'ing it.

**Comment by mmohamedbasith** [comment]
this is not yet fixed ,, scroll should go from left to right in infinate loop

**Comment by Herohtar** [comment]
This is the one thing that's holding me back from using this. Everything looks great until you get to the last image, nice smooth transitions... then suddenly a jarring sudden scroll all the way back to the start. It really should be a continuous loop.

**Comment by aprilmintacpineda** [comment]
check this out: https://github.com/aprilmintacpineda/inferno-carousel

**Comment by aprilmintacpineda** [comment]
Check this out: https://aprilmintacpineda.github.io/inferno-carousel/

**Comment by aprilmintacpineda** [comment]
https://github.com/aprilmintacpineda/react-carousel

**Comment by McSam94** [comment]
is there any update on this matter?
