### ISSUE TITLE
onItemClick doesn't work when you only have 1 item

### ISSUE THREAD

**Issue by l3roken** [leandrowd/react-responsive-carousel#256]
We often only have 1 event schedule and would like the ability to click on that item.  For some reason the code was written to prevent clicks if there is only 1 item:

```javascript
if (_react.Children.count(_this.props.children) <= 1) {
                return;
            }
```

**Comment by trekinbami** [comment]
I have the same issue. Why was this done? It even has a test devoted to this behaviour.

**Comment by 422158** [comment]
lol:D .... any progress on this one?

**Comment by jerryzhao0423** [comment]
Same problem. Is there anyone can help with this? Or is there a reason why it's prevented when only 1 item?

**Comment by lucaswhitman** [comment]
Still an issue afaik.

**Comment by lucaswhitman** [comment]
considering there haven't been releases in a bit maybe the bot should be turned off?
