### ISSUE TITLE
card into a carousal is not working properly

### ISSUE THREAD

**Issue by mukesh2295** [leandrowd/react-responsive-carousel#258]
As I want to make carousal of cards and  the problem is here I am just getting the header of the card, not the whole card

" <Carousel  autoPlay={false}
                  useKeyboardArrows={true}
                  dynamicHeight={true}
                  centerSlidePercentage={80}
                  infiniteLoop={true}
                  showThumbs={false}
                  showStatus={false}
                  width = {500}
                  height = {400}>
<div>
<Card>
<CardHeader` className = "Tweeter_header">
			        <div className = "CardHeader_logo">
			        <a href = "https://twitter.com/duckduckgo"><img style = {{float:'left' }} src = {DuckDuckGo_logo}  className="DuckDuckgoLogo" /></a>
			        <div className = "card_left"><a href="https://twitter.com/duckduckgo" className="tweeterCardName">DuckDuckGo</a>
		            <img src={Twitter_verified} className="tw_card__verified" aria-hidden="true" /> 
		            <a href="https://twitter.com/duckduckgo" className="tw_card_username">@DuckDuckGo</a></div>
		            <img src = {Twitter_logo}  className="twitter_Logo" /> 
		            </div>
			    </CardHeader>
<CardBody  className = "card1_text">
              <CardText>While Google says they donot read your email, 
                <a className="tweet_ur_username" href="https://twitter.com/dmac1" data-screen-name="dmac1" rel="nofollow">@dmac1 </a> 
                 reports that third-party developers still can and sometimes do: <a href="https://t.co/xwml7fdQh6"></a> (paywall).
              </CardText>
              <CardText>
                Summary (non-paywall) by <a className="tweet-url username" href="https://twitter.com/richardjnieva" data-screen-name="richardjnieva" rel="nofollow">
                @richardjnieva</a>:  <a href="https://t.co/EDH2eACccz" title="https://www.cnet.com/news/third-party-gmail-apps-reportedly-let-employees-read-peoples-emails/" rel="nofollow">
                cnet.com/news/third-par...</a>
              </CardText>
<CardFooter className = "tw_card_link"> 
                <a href="https://twitter.com/intent/tweet?in_reply_to=1017404966552498176" data-wrapped="true" className="tw_card_reply" aria-label="Reply to this tweet" title="Reply to this tweet">
                <img src= {Twitter_reply} aria-hidden="true"/>
                </a>
                <a href="https://twitter.com/intent/retweet?tweet_id=1017404966552498176" data-wrapped="true" className="tw-card__link tw-card__action js-tweet-action" aria-label="Retweet button" title="Retweet button">
                <img src= {Twitter_retweet} aria-hidden="true"/></a>
                <a href="https://twitter.com/intent/like?tweet_id=1017404966552498176" data-wrapped="true" className="tw-card__link tw-card__action js-tweet-action" aria-label="Like button" title="Like button">
                <img src= {Twitter_like} aria-hidden="true"/></a>
                <a href="https://twitter.com/duckduckgo/status/1017404966552498176" className="tw-card__date tw-card__link t-bold"  >
                <time style ={{float:'right' , color: '#333' , textDecoration: 'none'}}>Thu Jul 12</time> </a>
            </CardFooter>
          </CardBody>
        </Card>
</div>
</Carousal> 

> " @leandrowd i know it can be noob question but still help  me out

**Comment by mukesh2295** [comment]
another example on the same issue 
"<Carousel
    autoPlay={false}
    useKeyboardArrows={true}
    dynamicHeight={true}
    centerSlidePercentage={80}
    infiniteLoop={true}
    showThumbs={false}
    showStatus={false}
  >
    <div>
      <Card>
        <CardHeader style={{ backgroundColor: "white" }}>
          <h1>Hello </h1>
        </CardHeader>

        <CardBody style={{ backgroundColor: "white" }}>
          <img height = "auto" src="http://lorempixel.com/output/cats-q-c-640-480-2.jpg" />
        </CardBody>
        <CardFooter style={{ backgroundColor: "white" }}>
          <p>Hello world </p>
        </CardFooter>
      </Card>
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-2.jpg" />
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-3.jpg" />
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-4.jpg" />
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-5.jpg" />
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-6.jpg" />
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-7.jpg" />
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-8.jpg" />
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-9.jpg" />
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-10.jpg" />
      <p className="legend">Legend 10</p>
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-11.jpg" />
      <p className="legend">Legend 11</p>
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-12.jpg" />
      <p className="legend">Legend 12</p>
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-11.jpg" />
      <p className="legend">Legend 13</p>
    </div>
    <div>
      <img src="http://lorempixel.com/output/cats-q-c-640-480-11.jpg" />
      <p className="legend">Legend 14</p>
    </div>
  </Carousel>

> "

**Comment by inspirecharles** [comment]
Same here,
I'd like to use this package as a carousel of cards.
But this doesn't seem to support cards

**Comment by leandrowd** [comment]
can you reproduce your issue using https://codesandbox.io/s/lp602ljjj7 ?
