### ISSUE TITLE
Cannot find module 'react-easy-swipe' Error

### ISSUE THREAD

**Issue by etshi** [leandrowd/react-responsive-carousel#26]
Getting the following error `Cannot find module 'react-easy-swipe' from '.../node_modules/react-responsive-carousel/components'`

Do I have to manage the `react-easy-swipe` package installation ?

**Comment by leandrowd** [comment]
Ops, my fault. I missed this dependency in the distributed package. It's fixed now, please use 3.0.4. 

Thanks for raising it.

**Comment by etshi** [comment]
No problem thanks for the cool carousel
