### ISSUE TITLE
Requesting some new features

### ISSUE THREAD

**Issue by nicubarbaros** [leandrowd/react-responsive-carousel#269]
Hey there. 

This little module is amazing, does exactly what it says. I would love to request some features. 

1. Custom components for Dots
2. Custom components for Arrows. (Thanks)

**Comment by leandrowd** [comment]
https://github.com/leandrowd/react-responsive-carousel/pull/257

**Comment by leandrowd** [comment]
There is another issue tracking this request https://github.com/leandrowd/react-responsive-carousel/issues/232. I will close as dupicated.
