### ISSUE TITLE
port conflict in Windows 7.

### ISSUE THREAD

**Issue by vganesh** [leandrowd/react-responsive-carousel#277]
Hi, 
On windows 7, the command '**npm start**' fails with error message Error: listen EACCES 127.0.0.1:**8000**. 
Port 8000 is not available in Windows 7. 
The command 'npm start -- --port=9337' also fails with the same error message. 

What is the correct way to pass a different available port for gulp from command line? This may be a gulp question but I am running into it while testing this app on my Windows 7 laptop. 

Thanks a lot for the help. 

Cheers,

**Comment by sezna** [comment]
Have you tried navigating to your firewall settings and ensuring they are correct?
