### ISSUE TITLE
how to create custom next and prev button in react-responsive-carousel i am having this issus

### ISSUE THREAD

**Issue by muhammadsarim555** [leandrowd/react-responsive-carousel#278]

**Comment by sezna** [comment]
I do not believe this is currently a feature. You can add it and submit a PR if you want it.

**Comment by sezna** [comment]
This is a duplicate of #232

**Comment by leandrowd** [comment]
You can implement your own controls... Check this example: https://github.com/leandrowd/react-responsive-carousel/blob/master/stories/index.js#L59

**Comment by sudokzt** [comment]
@leandrowd  Thank you for good idea!
