### ISSUE TITLE
has3d.js error

### ISSUE THREAD

**Issue by americaru** [leandrowd/react-responsive-carousel#28]
Uncaught TypeError: Cannot read property 'insertBerore' of null
Uncaught TypeError: Cannot read property 'removeChild' of null

errors on acces in document body

https://github.com/leandrowd/react-responsive-carousel/blob/323f530ec1a9ced089eca3d2c962b17ae818d715/lib/has3d.js

**Comment by leandrowd** [comment]
Hi @americaru, can you give some more context?

How this error happened? By this message seems that you were trying to render it server side. AFAIK it was working fine but if you have an issue we can investigate. If you have a fix feel free to submit a Pull Request.

**Comment by leandrowd** [comment]
@americaru, can you confirm it's still an issue for you? Otherwise I'm going to close as invalid.

**Comment by leandrowd** [comment]
Closing as invalid. If the error persist please reopen.
