### ISSUE TITLE
Carousel position resets when parent component's timer interval is triggered

### ISSUE THREAD

**Issue by alexpreynolds** [leandrowd/react-responsive-carousel#280]
I have a `<Carousel>` instance that is embedded in a parent component's `render` method.

```
render() {
  return (
    <div>
      <Carousel>
        ...
      </Carousel>
    </div>
  )
}
```

The parent component's `componentDidMount()` method contains a `setInterval()` call that runs every five seconds (for example).

```
componentDidMount() {
  this.myRefreshInterval = setInterval(() => { ... }, 5000)
}
```

The carousel's `selectedItem` property is reset to zero every five seconds, when the parent component's `myRefreshInterval` interval is triggered.

**Comment by spamforhope** [comment]
had the same problem when updating parent component MobX state.
Carousel position sets to start when updating state for other component.

**Comment by tenacious-joy** [comment]
Is there a solution for it?

**Comment by spamforhope** [comment]
@tenacious-joy I've created logic where I store current slide Index and set it to Carousel activeSlide props every time. It works, but it's not a solution.

**Comment by lukevandekieft** [comment]
I am having this same issue with an addEventListener function in the parent, the carousel resets whenever the listener changes state.  My biggest problem with this is actually that the control dots retain original focus after the Carousel resets which leads to undesirable UI situations.

For now I'll control activeSlide in my own state like others are suggesting.

**Comment by lukevandekieft** [comment]
Was able to get this working, thanks for the suggestion spamforhope! For anyone trying to control carousel position in parent state here's what I used:

Carousel:
```
<Carousel onChange={this.props.changeCarousel} selectedItem={this.props.carouselPosition}>
```

Parent Component:
```
  state = {
    carouselPosition: 0,
  }

  changeCarousel = index => {
    this.setState({carouselPosition: index});
  }
```
