### ISSUE TITLE
after change props not set new values in Thumbs

### ISSUE THREAD

**Issue by fedorovmichael** [leandrowd/react-responsive-carousel#281]
Hi,
After change props not set new values in Thumbs and show new image in Slide and in Thumbs stay old images.
The issue happen because the 'componentWillReceiveProps' call function this.getImage() and this.getImage() get images from this.props.children that has old images.

How can I resolve this issue?
Thanks

**Comment by danielpopovic** [comment]
Hi,
I have the same behavior. When I set image for the first time, it's working fine, but when a load new images it's not working.
I set the image like this:
`<img src={"data:image/png;base64," + this.props.store.Images[i].Content} key={i} />`

Can you help me with this?
Thanks
