### ISSUE TITLE
Youtube controls not accessible (bullets seem to be on top)

### ISSUE THREAD

**Issue by donatoaz** [leandrowd/react-responsive-carousel#283]
Hi y'all! I seem to be running into an issue in which the bullets that control navigation between slides are atop of the youtube controls (pause, volume, etc) and I can't click them. I've recorded the gif below showcasing what is happening.

I think this is happening because `.carousel .control-dots` has a `width: 100%;` 
https://github.com/leandrowd/react-responsive-carousel/blob/fa166d36f9074ccbcf7ba3d5893e736b7592501e/src/components/_carousel.scss#L232

![bug_report](https://thumbs.gfycat.com/EminentBlandAsiaticlesserfreshwaterclam-size_restricted.gif)

**Comment by leandrowd** [comment]
Can this be closed now?
