### ISSUE TITLE
check some condition/perform action before slide?

### ISSUE THREAD

**Issue by dmccarty** [leandrowd/react-responsive-carousel#295]
More of a question - is there any way to conditionally to allow a selectedItem change? i.e. before the slide changes check for some condition and if it fails prevent the transition?

Thanks

**Comment by leandrowd** [comment]
You can implement your own controls for the carousel and then implement the check or any other special behaviour you want. Check this example: https://github.com/leandrowd/react-responsive-carousel/blob/master/stories/index.js#L59
