### ISSUE TITLE
RTL support for right to left language for arabic user

### ISSUE THREAD

**Issue by kartikeyb** [leandrowd/react-responsive-carousel#296]

**Comment by alinavaie** [comment]
Add a style class that includes **direction: 'initial'** to the Carousel component.

**Comment by yarivShamash** [comment]
I also experianced this issue and tried @alinavaie 's solution but it did not work. I see the carousel but not the content. when changing the direction back to 'ltr' it woks fine.
Can you help out?

**Comment by EmanuelBenHamo** [comment]
I found a way to make this component RTL (if by RTL you mean that swiping the images will be from right to left):

   <Carousel
      selectedItem={length(allMedia) - 1}
    >
      {mapIndexed(createImage())(reverse(allMedia))}
    </Carousel>

basically the idea is to set the selectedItem prop to the last index of your images array + reverse the order of the images in the array.

in this way the images will be in the correct order and swiping will be from right to left.

**Comment by wasiqkhan** [comment]
> Add a style class that includes **direction: 'initial'** to the Carousel component. It works for both directions.

this works fine for me. I added the style class to the parent div of the Carousel component.
