### ISSUE TITLE
to reverse the direction of default slide (from left to right)

### ISSUE THREAD

**Issue by vibhor1994** [leandrowd/react-responsive-carousel#299]
I am using this in my react front end. I want to reverse the default scroll direction (right to left) to the left to right. and update the indicators respectively from last to first.

**Comment by tiggem1993** [comment]
Same problem with us. Please Help.
1. In case of right to left swipe, previous slide will appear instead of next slide.
2. In case of left to right swipe, next slide will appear instead of previous slide.

**Comment by amyordre** [comment]
@tiggem1993 Having the same issue here too. Have you found the issue/solution yet?

**Comment by Maggistro** [comment]
@tiggem1993 @amyordre  Looks this behaviour got introduced with https://github.com/leandrowd/react-responsive-carousel/commit/1b3712e39b35d17f1d4f96fa0a5801db53771bb7#diff-47f9a611545f9ac1e92bcfa0131e590b. If you check out version 3.1.43 swiping works as intended.

**Comment by amyordre** [comment]
@Maggistro Thank you so much! Fixed the issue!

**Comment by vojvodics** [comment]
had the same issue, just updated to 3.1.47, and it looks like it is fixed...
