### ISSUE TITLE
Dead links in README

### ISSUE THREAD

**Issue by GerardVee** [leandrowd/react-responsive-carousel#300]
Under Demo, the "cool demos" link leads to a 404, as well as "Demos" under Important links. They both lead to a storybook url that is needed to see important demos.

**Comment by warriorpostman** [comment]
@GerardVee Thanks for catching these dead links. In another issue, someone pointed out that the link to the CodeSandbox link also was pointing to a sandbox that doesn't use the latest version of the library and made it difficult for someone to demonstrate a bug (https://github.com/leandrowd/react-responsive-carousel/issues/303)

Later this evening, I'm going to open a PR that fixes the links the best I know how.

**Comment by leandrowd** [comment]
Fixed -> http://react-responsive-carousel.js.org/storybook
