### ISSUE TITLE
Throw warning asynchronous tasks in the componentWillUnmount method

### ISSUE THREAD

**Issue by gearintellix** [leandrowd/react-responsive-carousel#305]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Carousel (created by StorialCarousel)
    in StorialCarousel (created by Section1)
    in div (created by Section1)
    in div (created by Section1)

**Comment by ashishjain3456** [comment]
Try this soln, its a trick but works:
https://stackoverflow.com/a/50504281/349206

**Comment by ErikParso** [comment]
I got a same error message. I am not even executing setState function.

**Comment by manoj-mass** [comment]
Getting the same error.

![image](https://user-images.githubusercontent.com/26952806/86517012-0db0d380-be43-11ea-8046-a9993287f3c2.png)

**Comment by dluc** [comment]
please fix! thanks

**Comment by IryArkhy** [comment]
I've got the same error. Any updates on this issue?
