### ISSUE TITLE
Swipe is in oposite direction 

### ISSUE THREAD

**Issue by shabeeb-sap** [leandrowd/react-responsive-carousel#309]
When i am trying to swipe left its going backward instead of forward.

it would be grate if you can fix it

**Comment by nicolaburetta** [comment]
Same problem only in production env. I don't know why, but in development environment it's all ok, while in production env when I swipe from the left to the right, it goes forward and vice versa.
I currently use the 3.1.43 version.

**Comment by sovanjana** [comment]
I'm getting the same issue in **development env** also. I am using **v3.1.43** and it works perfectly but after an **npm install** it starts showing this issue.

**Comment by nicolaburetta** [comment]
Maybe this can temporarily help: I solved removing the "^" char before the version number in package.json dependencies.
Now I have:
"react-responsive-carousel": "3.1.43"
instead of
"react-responsive-carousel": "^3.1.43"
and it works well also in production env.

**Comment by TheBrown** [comment]
> Maybe this can temporarily help: I solved removing the "^" char before the version number in package.json dependencies.
> Now I have:
> "react-responsive-carousel": "3.1.43"
> instead of
> "react-responsive-carousel": "^3.1.43"
> and it works well also in production env.

Thank you so much

**Comment by leandrowd** [comment]
The fix was published as 3.1.47.
