### ISSUE TITLE
stoppropagation and preventDefault is not working on next-prev arrow click 

### ISSUE THREAD

**Issue by mrjosshi** [leandrowd/react-responsive-carousel#310]
I want to use stoppropagation and preventDefault on arrow click but onChange return value of slide only so how can i trigger event of button Please help
TIA

**Comment by anilljoshi** [comment]
any update here

**Comment by hashim-rana-hub** [comment]
@mrjosshi 
mrjosshi 

it provides custom navigation arrows using the renderArrowPrev and renderArrowNext props. 

`  const customArrow = (direction, onClickHandler) => (
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation();
                onClickHandler();
              }}
           
            >
      {direction === 'prev' ? <ChevronLeft /> : <ChevronRight />}
    </button>
  );`
`      <Carousel  renderArrowPrev={(onClickHandler, hasPrev) =>
            hasPrev ? customArrow('prev', onClickHandler) : null
          } 
          />`
