### ISSUE TITLE
Black fill is visible during transition when using dynamicHeight and flexbox

### ISSUE THREAD

**Issue by remjx** [leandrowd/react-responsive-carousel#312]
In the transition from a wide image to the tall image, a black fill is visible.

https://codesandbox.io/s/j328w994l3

In lieu of a quick solution, as a workaround, is there a way to set this background fill color?

Thanks!

**Comment by leandrowd** [comment]
Hi @markjackson02, your example doesn't show the black fill. Have you tried using images instead of background?

**Comment by markjackson02** [comment]
@leandrowd sorry for the late response. Here is an updated sandbox: https://codesandbox.io/s/v85v7rpn05

**Comment by blacksmoke26** [comment]
Any progress?

**Comment by Gu4etl** [comment]
@blacksmoke26 @markjackson02 
If I correctly understood.
You may just rewrite the style of background for this selector
`.carousel .slide`

This code is rewriting the fill color to yellow.
`.carousel .slide{ background: yellow; }`

**Comment by Aeonstrife** [comment]
> 
> 
> @blacksmoke26 @markjackson02
> If I correctly understood.
> You may just rewrite the style of background for this selector
> `.carousel .slide`
> 
> This code is rewriting the fill color to yellow.
> `.carousel .slide{ background: yellow; }`

I changed` .carousel .slide{ background: black; } ` to` .carousel .slide{ background: yellow; } `in carousel.min.css but I am still getting black bars

**Comment by Gu4etl** [comment]
@Aeonstrife Try to open
https://codesandbox.io/s/v85v7rpn05
change code in overrides.css
![Screenshot 2019-08-03 at 14 08 49](https://user-images.githubusercontent.com/52911165/62411192-407d9680-b5f8-11e9-9e96-f48438537791.png)

**Comment by markjackson02** [comment]
I propose that we add background color as a prop unless there is a cleaner solution?

**Comment by talentlessguy** [comment]
> I propose that we add background color as a prop unless there is a cleaner solution?

yes it would be nicer than overriding css classes

**Comment by Denny966** [comment]
Not sure why the default background color is black, imo, it shouldn't be set to anything

**Comment by markjackson02** [comment]
@Gu4etl's solution works. It looks like this https://github.com/leandrowd/react-responsive-carousel/blob/8593f0e2c7039fb502c25e80a0616dd8a532f9ec/src/components/_carousel.scss#L201 is where the black background is being set on .slide class

Does everyone agree it would make sense to add a prop for background color?

**Comment by pmourer** [comment]
making it undefined by default with an option to provide would be great

**Comment by snjay** [comment]
+1 it should be transparent by default with the ability to change it via a prop

**Comment by ChasinHues** [comment]
Agreed, I think having a black background by default is unnecessarily opinionated.

+1 for slides having no background by default, and having the ability to modify the background of slides via a prop.

In case this helps anyone, the workaround I've opted for is using `renderItem`:

```
<Carousel
    renderItem={item => <div style={{ background: "white" }}>{item}</div>}
>
``` 

Alternatively, you could just override the background set on `.carousel .slide`.

**Comment by ChasinHues** [comment]
@leandrowd what are your thoughts on this issue and the solutions provided?

**Comment by Akbarshox** [comment]
HI. Please remove that black background color.

**Comment by phoenixbeats01** [comment]
Any progress? Why has this not been implemented.

**Comment by remjx** [comment]
bump

**Comment by Denny966** [comment]
Still an issue, should not be closed yet!
