### ISSUE TITLE
'autoPlay' and 'stopOnHover' don't work without images?

### ISSUE THREAD

**Issue by wildpow** [leandrowd/react-responsive-carousel#317]
I'm trying to make a carousel of user reviews. Everything works just fine besides 'autoPlay' and 'stopOnHover'. If I click the next arrow then auto play and my custom interval starts. Just wanted to know if this NPM package is only attended for images or I'm I missing something in my set up?

"dependencies": {
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-responsive-carousel": "^3.1.47",
    "react-scripts": "2.1.3",
    "styled-components": "^4.1.3",
    "styled-normalize": "^8.0.6"
  },

```
 <Carousel
      infiniteLoop
      autoPlay
      showThumbs={false}
      interval={6000}
      stopOnHover
      showStatus={false}
 >
  {data.map(i => (
          <div key={i.reviewId}>
            <p>{i.comments}</p>
            {`${i.reviewer.firstName} ${i.reviewer.lastName}`}
          </div>
        ))}
</Carousel>
```

**Comment by Jinitshah0803** [comment]
I am also having the same issue can anyone please suggest

**Comment by matheusmazeto** [comment]
Do this verification on render {data.length > 0 &&  <Carousel />}
