### ISSUE TITLE
autoPlay doesn't work when start (SP webpart)

### ISSUE THREAD

**Issue by EGBravo** [leandrowd/react-responsive-carousel#321]
First of all, I've already checked this issue: https://github.com/leandrowd/react-responsive-carousel/issues/298

My problem is basically the same, autoPlay starts only when I click on an arrow. I'm using this component in a Sharepoint webpart with the following configurations:

showThumbs={false} 
onClickItem={this.click_item} 
showStatus={false} 
autoPlay={true} 
interval={2000} 
infiniteLoop={true} 
dynamicHeight={true} 

Edit: I tried v3.1.46 and v3.1.47 and didn't worked, but v3.1.33 did

**Comment by liuweiming1997** [comment]
I have the same problem & not work with stopOnHover

**Comment by liuweiming1997** [comment]
also I want to know how to play to first page if autoPlay gone to the end. `ie endpage -> 1`

**Comment by Sujithkumara** [comment]
I have the same issue where the carousel does not start rotating on page load. Is this fixed ? What's the workaround for this?

**Comment by webmuch** [comment]
Same issue here. Any update on this?

**Comment by deepalijain1** [comment]
I am also facing the same issue. autoplay not working even in latest release which is 3.1.49 and yes, autoplay works in version 3.1.33 but when it comes to the last slide, it flips to the first one , scrolling backwards, navigating all the slides in between, which is not a very good user experience. Not sure, how it is working fine in Demos. :( Am I missing something here? please advise.

**Comment by govinddk4444** [comment]
I am also facing the same issue. Any workaround?

**Comment by govinddk4444** [comment]
downgrading to 3.1.33 worked fine for me

**Comment by Sujithkumara** [comment]
As a workaround I resolved the issue by writing a jquery click event on the page load method.

**Comment by bhashmitha** [comment]
Even I had the same issue my package version was 3.1.49 , I then downgraded to 3.1.46 still the issue was not fixed. I get the data from API and then map it inside the Carousel . So I put a condition like until I get the data from api I'm not going to render the Carousel and it looks something like this,
 {this.state.banners.length > 0 ? (
          <Carousel
            showArrows={false}
            showIndicators={true}
            showThumbs={false}
            showStatus={false}
            autoPlay={true}
            interval={2000}
            infiniteLoop={true}
            swipeable={true}
          >
          //Here I mapped the data and displayed the image. 
          </Carousel>
        ) : null}
And it fixed for me.

**Comment by louiscb** [comment]
@bhashmitha thank you sir!

**Comment by nabinbhusal80** [comment]
@EGBravo the problem occurs when you initialize the Carousel with no children. So don't init the Carousel unless you have children. It will solve the problem. You don't need to downgrade or anything like that.

**Comment by matheusmazeto** [comment]
Thanks @bhashmitha and @nabinbhusal80

**Comment by rardoz** [comment]
setting the key of carousel to item.length works too

**Comment by codexive-zech** [comment]
Thanks, @bhashmitha your solution helped out.

**Comment by manan999** [comment]
Thanks @rardoz , your solution helped me without downgrading or any of that
