### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by nicubarbaros** [leandrowd/react-responsive-carousel#322]
Seems like somehow the `this.itemsRef` is undefined or null.

The error is on this line
` const firstItem = this.itemsRef[0];` in `updateSizes` function in `Carousel.js` compoenent.

Version: `"react-responsive-carousel": "^3.1.42"`

**Comment by ErikCohen-natgeo** [comment]
@nicubarbaros had the same issue, was able to fix it by mounting the component only when the request for the image was completed.

**Comment by pierfrancesco** [comment]
Inside `lib/components/Carousel.js`, at line 574, I'm trying this:
`this.updateSizes = function() {
    if (!_this5.state.initialized || _this5.itemsRef === undefined) {
    return;
}`

Seems that error disappears and the carousel still works.
