### ISSUE TITLE
Jest not running with `npm run test`

### ISSUE THREAD

**Issue by pdw207** [leandrowd/react-responsive-carousel#33]
I am having trouble getting jest to run and I think that possibly the `scriptPreprocessor` `6to5-jest` is not being called properly but not sure how to fix it.

<img width="841" alt="screen shot 2016-03-11 at 10 08 02 am" src="https://cloud.githubusercontent.com/assets/4714249/13705962/2e76e328-e771-11e5-9a82-fa06ed2ab710.png">

**Comment by leandrowd** [comment]
Hi @pdw207, you can run using --harmony flag for now. I will update the modules when I get some spare time. We are still using 6to5, it's a shame lol.

**Comment by leandrowd** [comment]
If you use node 0.10.36 it will work. Try with nvm.

**Comment by pdw207** [comment]
Thanks!
