### ISSUE TITLE
spinner before carousel image load 

### ISSUE THREAD

**Issue by abhijithvijayan** [leandrowd/react-responsive-carousel#333]
is it currently possible to include a react spinner before the image gets loaded completely.

**Comment by fparent** [comment]
Agreed that would be very useful

**Comment by nicubarbaros** [comment]
As an alternative way. You can make your component to do this. 
Do a component that will render the loader before displaying an image. Thats what I did. ))

**Comment by abhijithvijayan** [comment]
@nicubarbaros but for how long? we cant know if the images are fully loaded right?

**Comment by nicubarbaros** [comment]
@abhijithvijayan Yes we can. (If we talk about DOM).

If we talk about `react` here is how I am doing.

```
componentDidMount() {
    this.fetchImage(imageUrl);
  }

fetchImage = src => {
    const image = new Image();
    image.onload = () => this.setState({ currentImage: this.loadingImage.src, loading: false });
    image.src = src;
  };

```

What is this does is creating an ghost image object in memory and when the `onLoad` callback gets called we know it is ready for the DOM and then we set the url to the image. Until that while is loading we can show a loader.
