### ISSUE TITLE
Swiping issue when using infiniteLoop and centerMode

### ISSUE THREAD

**Issue by mraymond** [leandrowd/react-responsive-carousel#334]
When using infiniteLoop and centerMode together, the animation seems to cycle through the entire carousel rather than smoothly transition to the slide. This occurs when swiping from first to second, first to last, and last to first.

[Code Sandbox Example](https://codesandbox.io/s/pmkj02vlom)

**Comment by jota12x** [comment]
It happened to me today as well. Any plans for a patch?

**Comment by blimpmason** [comment]
I'm having the same issue!

**Comment by yacula** [comment]
Same issue for me...

**Comment by NogaMan** [comment]
Same

**Comment by OlivierGo123** [comment]
This issue still persists for me. Does anyone have a solution to this?

**Comment by sowhatdoido** [comment]
same :(
