### ISSUE TITLE
Carousel without img tag return Error

### ISSUE THREAD

**Issue by Fahime** [leandrowd/react-responsive-carousel#335]
Hi,
When I use Carousel from (https://www.npmjs.com/package/react-responsive-carousel) link. I use it without img tag and I only need some div and text for each item like below. I got  this error: 
>  TypeError: this.state.images is null
What's the problem?     
 < Carousel>
      < div className="w-100">
                < div className={day}>
                  {item.day}
                < /div>
                < div>
                  {item.date}
                < /div>
          < /div> ...........
  </ Carousel>

**Comment by yyh1102** [comment]
some problem, have you fix it？

**Comment by ivansenic** [comment]
Using `showThumbs={false}` solves this error.

**Comment by leandrowd** [comment]
This has been fixed on the latest version. Please update.
