### ISSUE TITLE
Fix StrictMode warnings

### ISSUE THREAD

**Issue by aralroca** [leandrowd/react-responsive-carousel#337]
Using React.StrictMode is throwing these warning:

First:

```
findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ReactSwipe which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

    in ul (created by ReactSwipe)
    in ReactSwipe (created by Carousel)
```

Second:

```
Unsafe lifecycle methods were found within a strict-mode tree:
...
componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps 
```

The first one I guess that is better to report directly to ReactSwipe repo, however the second one can be fixed here replacing the deprecated `componentWillReceiveProps` to `componentDidUpdate`, `getDerivedStateFromProps` or `useEffect` hook, to allow Concurrent mode in the future.

**Comment by aralroca** [comment]
I also reported in ReactSwipe: https://github.com/voronianski/react-swipe/issues/159

**Comment by jleider** [comment]
Also reported as https://github.com/leandrowd/react-responsive-carousel/issues/454

**Comment by jleider** [comment]
This is still an issue.

**Comment by jleider** [comment]
I think this was fixed with https://github.com/leandrowd/react-responsive-carousel/pull/656 and can be closed.
