### ISSUE TITLE
Display Multiple Images within a Single Slide.

### ISSUE THREAD

**Issue by C-CG** [leandrowd/react-responsive-carousel#339]
Hi, firstly great library it has been very useful. I was wondering if it is possible to display multiple images within a single slide? Currently it will only take the first image into account and discard the others.

**Comment by C-CG** [comment]
Even tried adding both of the Images to a class and returning it that way, it still only displays whatever imag e is first.

**Comment by C-CG** [comment]
Any updates? It's somewhat urgent.

**Comment by C-CG** [comment]
The slides themselves are only able to render one image, meaning that any div after it (even if they are both children of the main parent div) cannot be rendered. Has anyone found a fix to this? Having multiple child div's is fine, but when an Image is involved it takes priority only rendering itself. Thanks

**Comment by Boris-Scharinger** [comment]
I would need to have the same requirement - for a logo scroll bar...Thanks!

**Comment by mercteil** [comment]
Same here.

**Comment by dimisus** [comment]
Exactly the feature I am missing
