### ISSUE TITLE
Making carousel fill up whole screen as background slideshow

### ISSUE THREAD

**Issue by louiscb** [leandrowd/react-responsive-carousel#341]
I'm attempting to use this repo in order to create a background slideshow for the home page of a website.

I'd like all the same functionality but for the images to fill the entire screen, and for their to be other HTML elemnts sitting on top of them like navigation bars, titles etc.

I've been trying to do this but struggling a bit and couldn't find any examples in the documentation.

**Comment by MichaelWheldon** [comment]
This sounds more like a styling question than something related to this package.

Just as a quick "solution" for your problem, apply the following to the carousel:

- height: 100vh, width: 100vw, position: fixed, top: 0, left: 0
- everything else should then sit on top of this element. how you achieve that is up to you

**Comment by louiscb** [comment]
Thanks
