### ISSUE TITLE
Cannot cycle through slides when a "Click" EventHandler is active.

### ISSUE THREAD

**Issue by dharnen** [leandrowd/react-responsive-carousel#353]
I'm experiencing an issue where if I have a "click" event handler on the same page as a carousel it won't allow me to move to a slide other than the initial one. If I try to swipe, use the side arrow buttons, or click on one of the thumbnails it quickly reverts back to the first slide. Anyone else experience this or have an idea how to work around this?

Thanks

**Comment by caseykey** [comment]
I am having the same issue when using the onClickItem prop.
