### ISSUE TITLE
componentWillReceiveProps is marked as deprecated

### ISSUE THREAD

**Issue by drbeat** [leandrowd/react-responsive-carousel#355]
https://github.com/leandrowd/react-responsive-carousel/blob/efcf86acdffc9ef929aff524eb17da8dd0890a36/src/components/Carousel.js#L94

With React 16.9 the lifecycle function "componentWillReceiveProps" is marked as deprecated will be even removed in React 17.

As you can read here https://fb.me/react-async-component-lifecycle-hooks

But there is a new lifecycle function
```
  static getDerivedStateFromProps(props, state) {
    // ...
  }
```

Are there any plans to update the library soon?

**Comment by MoonDevJS** [comment]
@drbeat Same problem for me, thank you for opening this issue.

In the files Carousel.js and Thumbs.js (like specified in the error message below) I renamed `componentWillxxx` in `UNSAFE_componentWillxxx`, without success...

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: Carousel, Thumbs

**Comment by drbeat** [comment]
As I have pointed out the correct way to change this is to replace "componentWillxxx" with "static getDerivedStateFromProps".

**Comment by leandrowd** [comment]
Thanks for raising the issue @drbeat. I won't have time to work on this anytime soon. Would you be able to submit a Pull Request with the required changes? Cheers

**Comment by shawnpyates** [comment]
I'd be interested in helping with this, but @leandrowd , could you help me understand why `componentWillReceiveProps` was implemented in the first place? This method was generally used for when props update (from a parent component, connected store, etc.), but glancing at the code I can't see anywhere where these props could be updated after they're initialized.

In terms of `getDerivedStateFromProps`, in most cases it's considered to be [a bit on the overkill side](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html). If we just want to keep to keep state in sync with props, there are generally simpler ways to do it.

**Comment by leandrowd** [comment]
Not a good idea to ask for context on this implementation as it has been written over 4 years ago so sorry but I can't help. I would need to investigate possible solutions but I'm short on time to be honest. 

I'm happy to review any pull requests and publish the package on my next available spare time. Other than that, unfortunately, you are on your own.
