### ISSUE TITLE
Maintainers?

### ISSUE THREAD

**Issue by sezna** [leandrowd/react-responsive-carousel#357]
@leandrowd  would you like to call for some maintainers to help you out? This library is clearly used by many, and I'd be willing to help you sift through the issues and PRs. I'm sure others would as well.

**Comment by leandrowd** [comment]
Yes, please! 

I left a note about it on the README a while back (https://github.com/leandrowd/react-responsive-carousel#help-wanted)

I will still be reviewing work and pressing the merge button but raising issues and PR's is totally up to the community atm.

**Comment by leandrowd** [comment]
You are now a collaborator :)

**Comment by sezna** [comment]
Thanks!
