### ISSUE TITLE
Vertical scroll on on mobile affects changes the slide 

### ISSUE THREAD

**Issue by AnushHakobyan** [leandrowd/react-responsive-carousel#358]
Hi all.
I want to submit an issue.
When carousel is opened on a mobile, on android/chrome for example, vertical swiping on mobile screen causes carousel slide to be changed: swiped to next or prev.

**Comment by jiferent** [comment]
The same thing happen is want to do up/down scroll, it will register as left/right as well.

**Comment by Marguelgtz** [comment]
Having the same issue .

**Comment by amarklars** [comment]
I have this problem as well.

**Comment by sathya1690** [comment]
I am also having the same issue..

**Comment by DenisCangemi** [comment]
Same here

**Comment by swedenSnow** [comment]
Same. Also getting an err: 
react-swipe.js:226 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted. ¯\_(ツ)_/¯

**Comment by KieranO547** [comment]
To anyone having this issue, I've submitted a PR to the [`react-easy-swipe`](https://github.com/leandrowd/react-easy-swipe/pull/48) repo (also managed by leandrowd) to fix the error message mentioned by @swedenSnow, so you can look at that if you want it to stop spitting out the error, but if you want to stop the vertical swipes from switching the panels there is a prop on the carousel `swipeScrollTolerance` which takes a number (default is 5) to affect the sensitivity of scrolls till a swipe is created (my testing found 30 to be a good value, YMMV).

**Comment by ovidiudinu** [comment]
Hello, 
I think that the transform CSS property should not happen if the swipe is kind of up and down...I've set the `swipeScrollTolerance` to 100...which indeed is preventing the slide switch from happening on touch end. The problem is that while touch move is active and you're swiping up or down but not perfectly up or down...the next or previous slide still show up a little until you release the touch.

So I think as long as the intent of the touch is up/down the transition should not even begin. You are probably checking the `swipeScrollTolerance` only on touch end....but by then the transform CSS property already happened.

**Comment by MindfulMe** [comment]
same

**Comment by MindfulMe** [comment]
swipeable={false} since nothing else helps.

**Comment by ghariosk** [comment]
I am encountering the same issue. As a temporary fix, I am using the following:
```javascript
let [swipeable, setSwipeable] = useState(true);
```
```javascript

useEffect(() => {
        if (images.length) {
            function disableScroll() {
                let carousel = document.querySelector('.carousel');

                let startPos;
                let endPos;
                let isScrolling = 1;

                function touchMove(e) {
                    if (
                        e.targetTouches.length > 1 ||
                        (e.scale && e.scale !== 1) ||
                        !startPos
                    )
                        return;

                    var touch = e.targetTouches[0];

                    endPos = {
                        x: touch.pageX - startPos.x,
                        y: touch.pageY - startPos.y
                    };
                    isScrolling =
                        Math.abs(endPos.x) <= Math.abs(endPos.y)
                            ? 1
                            : 0; //When isScrolling is 1, it means vertical sliding and 0 is horizontal sliding
                    if (isScrolling && swipeable) {
                        setSwipeable(false);
                    }
                }

                function touchEnd() {
                    setSwipeable(true);
                    carousel.removeEventListener(
                        'touchmove',
                        touchMove
                    );
                }

                function touchStart(e) {
                    var touch = e.targetTouches[0]; //The touches array object gets all the touches on the screen, taking the first touch
                    startPos = {
                        x: touch.pageX,
                        y: touch.pageY
                    };

                    carousel.addEventListener('touchmove', touchMove);
                }

                carousel.addEventListener('touchstart', touchStart);
                carousel.addEventListener('touchend', touchEnd);
            }


            disableScroll();
        }
    }, [images, swipeable]);
```

```javascript
{!!images.length && (
 <Carousel
      swipeable={swipeable}
      showThumbs={false}
      swipeScrollTolerance={30}
 >
     {images.map(renderImage)}
</Carousel>
)}

```
 It does make the scroll lag but works quite well on the production build in iOS. Not tested on Android

**Comment by wulinjie122** [comment]
Same problem

**Comment by fidelusp** [comment]
same :)

**Comment by franciscobaaldev** [comment]
You can use `preventMovementUntilSwipeScrollTolerance` prop with `swipeScrollTolerance={100}`.

**Comment by dakicnikola** [comment]
@ghariosk Thank you for the script. 
I encountered an issue when swipable set to false, touchEnd function won't call, and it causes next swipe to be disabled.
I modified the script a little to fix that issue, and also made it less laggy.

`
  const [ swipeEnabled, setSwipeEnabled ] = useState(true)
  const [ touchEventsSet, setTouchEventsSet ] = useState(false)
  const swipeScrollTolerance = 30

  useEffect(() => {
    if (images.length) {
      const disableScroll = () => {
        let carousel = document.querySelector('.carousel')

        let startPos
        let endPos
        let isScrolling
        let passedSwipeScrollTolerance = false

        function touchMove(e) {
          if (
            e.targetTouches.length > 1 ||
            ( e.scale && e.scale !== 1 ) ||
            !startPos
          ) {
            return
          }

          if (!passedSwipeScrollTolerance && swipeEnabled) {
            const touch = e.targetTouches[ 0 ]
            endPos = {
              x: Math.abs(touch.pageX - startPos.x),
              y: Math.abs(touch.pageY - startPos.y),
            }
            passedSwipeScrollTolerance = endPos.x > swipeScrollTolerance

            isScrolling = endPos.x < endPos.y //When isScrolling it means vertical sliding
            if (isScrolling) {
              setSwipeEnabled(false)
            }
          }
        }

        function touchEnd() {
          setSwipeEnabled(true)
          passedSwipeScrollTolerance = false
          carousel.removeEventListener('touchmove', touchMove)
        }

        function touchStart(e) {
          const touch = e.targetTouches[ 0 ] //The touches array object gets all the touches on the screen, taking the first touch
          startPos = {
            x: touch.pageX,
            y: touch.pageY,
          }

          carousel.addEventListener('touchmove', touchMove)
        }

        if (!touchEventsSet) {
          carousel.addEventListener('touchstart', touchStart)
          carousel.addEventListener('touchend', touchEnd)
          setTouchEventsSet(true)
        }

        if (!swipeEnabled) {
          setSwipeEnabled(true)
          passedSwipeScrollTolerance = false
        }
      }

      disableScroll()
    }
  }, [ images, swipeEnabled ])`

**Comment by abhijeetvermayash** [comment]
I am still not able to solve this issue, can someone help me out here?

**Comment by edwardvinobox** [comment]
> You can use `preventMovementUntilSwipeScrollTolerance` prop with `swipeScrollTolerance={100}`.

This actually works like a charm. 
Thank you.

**Comment by amerzur** [comment]
same problem

**Comment by ducduan** [comment]
> You can use `preventMovementUntilSwipeScrollTolerance` prop with `swipeScrollTolerance={100}`.

I did this, it work.
But if you set `infiniteLoop` on.
Then when just did a small swipe (less than 100) by start touching on the left of the first item. It'll scroll 1 round and back to the item.
It should do nothing in this case.

Thanks for all your helps if you faced this issue.

**Comment by FruitBro** [comment]
Is this issue fixed?

**Comment by BhavyaCodes** [comment]
> You can use `preventMovementUntilSwipeScrollTolerance` prop with `swipeScrollTolerance={100}`.

worked for me, thanks!

**Comment by steamapunk** [comment]
> You can use `preventMovementUntilSwipeScrollTolerance` prop with `swipeScrollTolerance={100}`.

This worked for me too!! Thank you!

**Comment by bayonmbayo** [comment]
I have the same problem, I can't disable the vertical swipe so that the user can scroll the webpage very well

**Comment by paramkeshkamat** [comment]
> `preventMovementUntilSwipeScrollTolerance`

@ducduan Thanks for the solution it is working for me.
