### ISSUE TITLE
Accessibility in ul, li & div 

### ISSUE THREAD

**Issue by helabenkhalfallah** [leandrowd/react-responsive-carousel#359]
Hello,

Is there a way to add aria accessibility (label, group, hidden, ...) in ul, li & div childs of Carousel ? 

```javascript
<div class="carousel carousel-slider" style="width: 100%;">
<button type="button" class="control-arrow control-prev control-disabled"></button>
<ul class="slider animated" style="transform: translate3d(0%, 0px, 0px); transition-duration: 350ms;">
<li class="slide selected"><div aria-label="carrousel-li-label">
```

I tried : 

```javascript
const elements = React.Children.toArray(props.children)
  let ariaElements = null
  if (elements && elements.length) {
    ariaElements = elements.map(element => React.cloneElement(element, {
      'aria-label': 'carrousel-li-label',
    }))
  }
  return (
    <div ref={ref}>
      <Carousel
        showArrows
        showThumbs={false}
      >
        {ariaElements}
      </Carousel>
    </div>
  )
```

But this add props only inside li.
I tried also to use refs but we cannot modify props inside refs because props are readonly.
Is there a way to do ?
I don't want to manipulate DOM (React is declarative).

Thanks :)

**Comment by sezna** [comment]
What version are you using? It seems #352  introduced the ability to customize aria labels.

**Comment by sezna** [comment]
@helabenkhalfallah I'm closing this for now, but if #352 did not solve your problem, feel free to reopen it.
