### ISSUE TITLE
Manual links changing position to 0

### ISSUE THREAD

**Issue by sercaninaler** [leandrowd/react-responsive-carousel#36]
When I add some links(to open a modal window) in the carousel, clicking those links are changing the position of carousel to 0(first one). How can I prevent this?

`
<a href="#" onClick={this.openModal.bind(this)}>link</a>
`

**Comment by leandrowd** [comment]
Hi @sercaninaler, you can pass a handler to `onClickItem` in the Carousel tag or call e.preventDefault() inside your `openModal` method. Please let me know how it goes.

**Comment by sercaninaler** [comment]
Hi again, I tried all, didn't work. But I realised when I update the state in my method, normally the Carousel was resetting. So now, I am trying to fix the problem by passing 'selectedItem' prop. Soon I will let you know if this will help me. Thank you so much!

**Comment by sercaninaler** [comment]
selectedItem prop helped me to position the slider as i wanted. Thank you so much for great module!
