### ISSUE TITLE
Ignored attempt to cancel a touchmove event with cancelable=false

### ISSUE THREAD

**Issue by fedorov66** [leandrowd/react-responsive-carousel#363]
When I swiping screen and touchmove to carousel image I have exception:

react-swipe.js:234 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
_handleSwipeMove @ react-swipe.js:234

**Comment by sezna** [comment]
Can you share a minimal example of your code that could have caused this error? This is not enough information to go on.

**Comment by artemas** [comment]
@sezna it appears in chrome dev tools if i scroll page with swipe on carousel

**Comment by atmoyxic** [comment]
@artemas did you solve this? i also encountered this in version ^3.1.51
```
<Carousel showArrows={false} showIndicators={false} showThumbs={false} statusFormatter={this.statusFormatter}>
    {activity.cover_images.map((item, index) => {
        return (
            <div key={index}>
                {item.UrlList[0] ? <img src={item.UrlList[0]} /> : null}
            </div>
        )
    })}
</Carousel>

**Comment by MickaelNeves** [comment]
Still having this issue in version ^3.2.7
