### ISSUE TITLE
While swiping, iOS devices make it possible to scroll in other directions

### ISSUE THREAD

**Issue by willedanielsson** [leandrowd/react-responsive-carousel#365]
If you use an iOS device on Chrome and Safari and start swiping, while holding the down the finger you can also then start scrolling down on the website. This seems to be a general "bugg" on iOS devices and preventDefault() does not fix it. Does anyone else have the same problem?

**Comment by sezna** [comment]
Have you found a solution for this? Would you consider it a bug in the carousel or in iOS?

**Comment by willedanielsson** [comment]
Fixed in https://github.com/leandrowd/react-responsive-carousel/pull/366

**Comment by willedanielsson** [comment]
2
