### ISSUE TITLE
autoplay working just after first click on an arrow

### ISSUE THREAD

**Issue by denisknk** [leandrowd/react-responsive-carousel#367]
hi, can you tell me how can i get AutoPlay working right after page has been loaded? because now its autoplaying only after my first click on an arrow? Thank you!

**Comment by hiradyazdan** [comment]
@denisknk have you found a solution for this? I am experiencing a similar issue which is replicable in the project [examples](http://react-responsive-carousel.js.org/storybook/?path=/story/02-advanced--with-external-controls) as well:

Once toggle `autoplay` to `false` and then toggle back to `true`, unless you hover over the slides/main slide or select next/prev slides (i.e. onClick), it won't reset back to `autoplay`. May be I am missing something in the implementation of the carousel, but couldn't find out what though!
