### ISSUE TITLE
Swipe does not work in the provided codesandbox

### ISSUE THREAD

**Issue by arhoy** [leandrowd/react-responsive-carousel#374]
Not sure if this is an issue, but I cannot seem to get swipeable to function.
Checked out the provided codepen sample and that is not swiping either.

https://codesandbox.io/s/lp602ljjj7

**Comment by leandrowd** [comment]
Touch gestures will only work on a mobile device, or if you enable it through the prop `emulateTouch`. Please let me know if you still have issues and provide more details like browser and device type. Thanks
