### ISSUE TITLE
Is there a way to easily hide the main image and show only the thumbnails?

### ISSUE THREAD

**Issue by dgeorgy007** [leandrowd/react-responsive-carousel#378]
Thanks

**Comment by mkorevec** [comment]
You could set a CSS override as follows, this will hide the main image but you will still have the little thumbnails.

`.slider-wrapper {
  display: none;
}`

**Comment by sezna** [comment]
I don’t think this is in the scope of the carousel as a whole — @dgeorgy007 if the above solution works for you I would like to close the issue. Does it solve your use case?
