### ISSUE TITLE
Auto-play support?

### ISSUE THREAD

**Issue by jccode** [leandrowd/react-responsive-carousel#38]
Is it possible to add auto-play functionality support? 
THANKS A LOT!

**Comment by leandrowd** [comment]
@pdw207 is working on it: https://github.com/leandrowd/react-responsive-carousel/pull/32

**Comment by leandrowd** [comment]
This issue is still open, PRs welcome!

**Comment by leandrowd** [comment]
Finally implemented. Available on npm@3.0.21. https://www.npmjs.com/package/react-responsive-carousel
