### ISSUE TITLE
Include CSS file using html tag

### ISSUE THREAD

**Issue by RosarioAleCali** [leandrowd/react-responsive-carousel#380]
Looking at the npm page, it suggests to include the css file in the index.html using a link tag.
The example suggests the following:
`
// Using html tag:
// <link rel="stylesheet" href="<NODE_MODULES_FOLDER>/react-responsive-carousel/lib/styles/carousel.min.css"/>
`
I am using this code in index.html:
`
<link
      rel="stylesheet"
      type="text/css"
      href="../node_modules/react-responsive-carousel/lib/styles/carousel.min.css"
/>
`
When I am loading the page, I am getting the following error on the console:
The stylesheet http://localhost:3000/node_modules/react-responsive-carousel/lib/styles/carousel.min.css was not loaded because its MIME type, “text/html”, is not “text/css”.

How can I solve this issue?

**Comment by mkorevec** [comment]
Your `node_modules` is probably not exposed as a public directory, so no route would work, you can move the style file and reference it from your public/asset folder.

However better and smarter way is to add something like [webpack](https://webpack.js.org/) which will allow you to easily with update of the package and build with the latest CSS.

**Comment by sezna** [comment]
@RosarioAleCali  Does this answer your question? And in general, do we feel like a documentation change here is needed?
