### ISSUE TITLE
How to go to Slide Index?

### ISSUE THREAD

**Issue by yofret** [leandrowd/react-responsive-carousel#384]
Hi Guys!! First of all thanks for this awesome component, my question is. 
Is there a method in the library, that allows you to go to an specific slide?

I would like to create my own custom thumbnail vertically on the left side, when you click on one of the elements the slider should react to it.

**Comment by abaker-cid** [comment]
You can set the "selectedItem" property of the Carousel element to a value in your state. e.g.
<Carousel selectedItem={this.state.currentSlide} />

and then in code: onThumbnailClick = (index) => { this.setState({ currentSlide: index }); }

Something like that should work.

**Comment by sezna** [comment]
@yofret did this solve your issue?
