### ISSUE TITLE
NPM vs Github version and installing from Github

### ISSUE THREAD

**Issue by web2style** [leandrowd/react-responsive-carousel#39]
I have two question, might be related so placing them together here.

1) NPM version is 3.0.10 and 1.0.2 here at github in package.json. Why are they different?
2) I forked the repo: https://github.com/web2style/react-responsive-carousel. Installing it from github like this: `"react-responsive-carousel": "git://github.com/web2style/react-responsive-carousel",` does nothing. `npm install` finishes without errors, but the package in `node_modules` just doesn't appear.

**Comment by leandrowd** [comment]
Hi @web2style, this project is a bit old and needs to be cleaned and tidied up. If you go to the folder `/lib` you will find the version you want. I'm not updating the main package.json only the one within `/lib`.

It also is the reason you can't install from the root. Try from `/lib`.

Let me know if it helps.

I'm currently not able to spend time on this project. Let me know if you are keen on helping.

**Comment by web2style** [comment]
Why keeping 2 versions at the same time? This means I made my pull request to a wrong file: `src/components/Carousel.js` instead of `lib/components/Carousel.js`. This is absurd.

**Comment by leandrowd** [comment]
No, you did it right. `/lib` contain generated files. The npm package is the `lib` folder.

**Comment by web2style** [comment]
Got it. But how then I can use the latest master version from github if `lib/components/Carousel.js` doesn't include my changes?

**Comment by leandrowd** [comment]
Just run `gulp package` and it will generate the files for you.

https://github.com/leandrowd/react-responsive-carousel#generating-the-package-for-npm

**Comment by web2style** [comment]
Thanks for quick answers. Hm, but how can this be done automatically upon `npm install`? There's no postinstall script in package.json.

**Comment by leandrowd** [comment]
That can't be done automatically. `gulp package` is only for local development. What you need is the package to be published again. I will publish when I have some spare time.

For now, you can use it locally.

**Comment by leandrowd** [comment]
Hi @web2style, your previous PR were published to npm. Check version 3.0.11.

I've updated the node version needed for the build as well. If you use 0.10.36 through nvm it should be fine.

Thanks for your contributions and feedbacks.
