### ISSUE TITLE
Carousel items don't render on server side with the newest Next (9.2.0)

### ISSUE THREAD

**Issue by kgabryje** [leandrowd/react-responsive-carousel#392]
I'm using the lib with Next.js and SSR enabled. It worked fine for me on 9.1.4 version, but after updating Next to 9.2.0 carousel items don't render on the first page load. After navigating to another page and coming back, so that the carousel renders on client side, the items appear. What's strange is that setting `ssr` prop to false doesn't fix the issue.

**Comment by tikpage** [comment]
I have same issue and fixed by:

`import "react-responsive-carousel/lib/styles/carousel.min.css";`

**Comment by Memo28** [comment]
> I have same issue and fixed by:
> 
> `import "react-responsive-carousel/lib/styles/carousel.min.css";`

I added that line on the _app.js and is not working either. I'm working with  "next": "9.3.5" and     "react-responsive-carousel": "^3.2.4"

**Comment by leandrowd** [comment]
Any update on this? 

To import a css you need to ensure you have a css loader configured.

**Comment by bkyam** [comment]
I'm on nextjs 9.3.4 and there are no issues. Not sure if you can upgrade.
