### ISSUE TITLE
Custom indicators when dots occupy too much space

### ISSUE THREAD

**Issue by pedroRelvas** [leandrowd/react-responsive-carousel#393]
Hi. Someone here managed a way to custom the indicators when there are too many dots on the picture? Like this:
![toomanydots](https://user-images.githubusercontent.com/43316469/73000446-c5ec4180-3df8-11ea-91b5-0b2d2810920c.PNG)
Any help will be appreciated.

**Comment by bouncydragon** [comment]
I think CSS can override it? thou I'm currently working on it, do you have any solution?

**Comment by pedroRelvas** [comment]
I've tried for some hours back then but didn't find any solution. Maybe in the future, I will try again...

**Comment by stephanieder** [comment]
Is there a possibility to put the dots under the slides, not on them ? (like thumbs which are under, but with the dots ?)

**Comment by leandrowd** [comment]
You can use css do customize the style but I would disable the indicators if I had as many images as you do.

**Comment by Ibs11** [comment]
try the below code , hope it helps :

//for styling purpose
const indicatorStyles = { 
  top: 'calc(50% - 5px)',
  background: 'white', 
  width: 6,
  height: 6, 
  display: 'inline-block',  
  borderRadius : '25px',
  margin: '0 2px' ,
  flexDirection: 'column', 
  overflow:'hidden',

};   



//carousel custom indicator
<Carousel className="" showThumbs={false}  infiniteLoop    
             renderIndicator={(onClickHandler, isSelected, index, label) => { 
                 if (isSelected) {
                     return ( 
                         <li onClick={(event) => event.stopPropagation()}
                             style={{ ...indicatorStyles, background: '#000' }}
                             aria-label={`Selected: ${label} ${index + 1}`}
                             title={`Selected: ${label} ${index + 1}`}
                         /> 
                     );
                 }else if( index<4){
                 return (  
                    <span className="" onClick={(event) => event.stopPropagation()} > 
                       <li
                         style={indicatorStyles}
                         onClick={onClickHandler}
                         onKeyDown={onClickHandler}
                         value={index}
                         key={index}
                         role="button"
                         tabIndex={0}
                         title={`${label} ${index + 1}`}
                         aria-label={`${label} ${index + 1}`}
                       />
                     </span>  
                 ) 
                  } ;
             }}
              >{imagesList} </Carousel>

**Comment by Ibs11** [comment]
try the below code - indicator length is reduced based on  index value , hope it helps :

//for styling purpose
const indicatorStyles = {
top: 'calc(50% - 5px)',
background: 'white',
width: 6,
height: 6,
display: 'inline-block',
borderRadius : '25px',
margin: '0 2px' ,
flexDirection: 'column',
overflow:'hidden',

};

//carousel custom indicator
<Carousel     showThumbs={false}      infiniteLoop   renderIndicator={(onClickHandler, isSelected, index, label) => {
if (isSelected) {
return (
<li onClick={(event) => event.stopPropagation()}
style={{ ...indicatorStyles, background: '#000' }}
aria-label={Selected: ${label} ${index + 1}}
title={Selected: ${label} ${index + 1}}
/>
);
}else if( index<4){
return (
<span className="" onClick={(event) => event.stopPropagation()} >
<li
style={indicatorStyles}
onClick={onClickHandler}
onKeyDown={onClickHandler}
value={index}
key={index}
role="button"
tabIndex={0}
title={${label} ${index + 1}}
aria-label={${label} ${index + 1}}
/>

)
} ;
}}
>{imagesList}</Carousel>

**Comment by Ibs11** [comment]
try the below code - indicator length is reduced based on index value , hope it helps :

//for styling purpose
const indicatorStyles = {
top: 'calc(50% - 5px)',
background: 'white',
width: 6,
height: 6,
display: 'inline-block',
borderRadius : '25px',
margin: '0 2px' ,
flexDirection: 'column',
overflow:'hidden',

};

//carousel custom indicator
<Carousel showThumbs={false} infiniteLoop renderIndicator={(onClickHandler, isSelected, index, label) => {
if (isSelected) {
return (

event.stopPropagation()} style={{ ...indicatorStyles, background: '#000' }} aria-label={Selected: ${label} ${index + 1}} title={Selected: ${label} ${index + 1}} /> ); }else if( index<4){ return ( event.stopPropagation()} >
)
} ;
}}

{imagesList}

</Carousel>

**Comment by Ibs11** [comment]
try the below code - indicator length is reduced based on index value , hope it helps :

//for styling purpose
const indicatorStyles = {
top: 'calc(50% - 5px)',
background: 'white',
width: 6,
height: 6,
display: 'inline-block',
borderRadius : '25px',
margin: '0 2px' ,
flexDirection: 'column',
overflow:'hidden', 
};

//carousel custom indicator
<Carousel showThumbs={false} infiniteLoop renderIndicator={(onClickHandler, isSelected, index, label) => {
if (isSelected) {
return ( 
event.stopPropagation()} style={{ ...indicatorStyles, background: '#000' }} aria-label={Selected: ${label} ${index + 1}} title={Selected: ${label} ${index + 1}} /> ); }else if( index<4){ return ( event.stopPropagation()} >
)
} ;
}}     {imagesList}   </Carousel>

**Comment by Ibs11** [comment]
try the below code - indicator length is reduced based on index value , hope it helps :

//for styling purpose
const indicatorStyles = {
top: 'calc(50% - 5px)',
background: 'white',
width: 6,
height: 6,
display: 'inline-block',
borderRadius : '25px',
margin: '0 2px' ,
flexDirection: 'row'
};

//carousel custom indicator
<Carousel showThumbs={false} infiniteLoop renderIndicator={(onClickHandler, isSelected, index, label) => {
if (isSelected) {
return (
event.stopPropagation()} style={{ ...indicatorStyles, background: '#000' }} aria-label={Selected: ${label} ${index + 1}} title={Selected: ${label} ${index + 1}} /> ); }else if( index<4){ return ( event.stopPropagation()} >
)
} ;
}} {imagesList}   </Carousel>
//............. end tag
