### ISSUE TITLE
Is there a way to specify custom slide transform css property

### ISSUE THREAD

**Issue by himajadhulipudi17** [leandrowd/react-responsive-carousel#396]
I am trying to make the slides centered using centermode and centerpercentage but the slide is not centered. i guess the slide width and the fact that I am trying to center first and last cards is disturbing the slide transformation. Is there a way to override the slide tranform property or way o specify custom tranform percentage instead of taking default (-100%).

**Comment by al13bash** [comment]
I'm looking for a solution for this issue as well.

**Comment by GabrielmLinassi** [comment]
I had to override the transform prop to manually handle the vertical translation in order to keep the slide centered. This is the way I did:

```
.slider {
    @media ${devices.tablet} {
      transform: ${({ index }) => {
        const yTranslation = index === 0 ? 0 : (80 + 99 * (index - 1)) * -1
        return `translate3d(0px, ${yTranslation}%, 0px) !important`
      }};
    }
  }
```
