### ISSUE TITLE
Interval time per slide instead of one overall interval

### ISSUE THREAD

**Issue by rickygipson** [leandrowd/react-responsive-carousel#398]
I need to set a different interval for each slide instead of one overall interval time. Is this possible?

**Comment by oliver-daniel** [comment]
Sorry for the total necro, but you could probably overwrite the slide's autoplay logic (as is done [here](https://react-responsive-carousel.js.org/storybook/?path=/story/02-advanced--with-external-controls)) and use client-side `setTimeout()`s to trigger an increment after the correct interval.
