### ISSUE TITLE
onClickItem returns carousel to first item

### ISSUE THREAD

**Issue by mwnciau** [leandrowd/react-responsive-carousel#400]
When an onClickItem event handler is specified to the carousel, whenever an item is clicked, the carousel returns to the first item. Using a limited bit of debugging, it looks like the selectedItem state variable isn't updated when the carousel changes:

`const onClickItem = function(i, item){
	app.setModal(item);
	console.log(i, this.selectedItem);
};`

This returns "1 0" (or "n 0") whenever the first slide isn't active.

The relevant code is in src/components/Carousel.js, lines 335 to 339. If the two numbers above don't match, the active slide is set to this.state.selectedItem, which happens to always be 0. Happy to provide more information if needed.

**Comment by fcandi** [comment]
I have the same problem, this should be fixed. thx  🙏

**Comment by nmorales1991** [comment]
same problem here

**Comment by marko-ignjatovic** [comment]
@mwnciau could you please share a little bit more of your code? It's strange but it seems like it works for me.

**Comment by Sativanakbc** [comment]
I also face the same problem!

**Comment by Sativanakbc** [comment]
I also face the same problem!

**Comment by Sativanakbc** [comment]
@marko-ignjatovic my code: 
`{proponents.map((item, i) => (
        <>
          <div>
            <i className="chicon-options-2" onClick={() => handOptions(i)} />
            <img src={user} alt={item.name} />
            <p>{item.name}</p>
            <span>
              {new Intl.NumberFormat('pt-BR', {
                style: 'currency',
                currency: 'BRL',
                minimumFractionDigits: 2,
              }).format(item.monthlyIncome)}
            </span>
            {optionsOpen === i && (
              <Options handler={handOptions}>
                <button type="button" onClick={() => editBuyer(item, i)}>
                  <i className="chicon-edit" />
                  Editar
                </button>
                {optionsOpen !== 0 && (
                  <button
                    type="button"
                    onClick={() => {
                      handConfirmation(true);
                      handItemSelected(item);
                      handIndiceSelected(i);
                    }}
                  >
                    <i className="chicon-trash" />
                    Excluir
                  </button>
                )}
              </Options>
            )}
          </div>
        </>
      ))}`

when the user clicks on the i tag, if he has already scrolled the slide, he is automatically taken to the first card

**Comment by Sativanakbc** [comment]
> @mwnciau could you please share a little bit more of your code? It's strange but it seems like it works for me.



> @marko-ignjatovic my code:
> `{proponents.map((item, i) => ( <> <div> <i className="chicon-options-2" onClick={() => handOptions(i)} /> <img src={user} alt={item.name} /> <p>{item.name}</p> <span> {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', minimumFractionDigits: 2, }).format(item.monthlyIncome)} </span> {optionsOpen === i && ( <Options handler={handOptions}> <button type="button" onClick={() => editBuyer(item, i)}> <i className="chicon-edit" /> Editar </button> {optionsOpen !== 0 && ( <button type="button" onClick={() => { handConfirmation(true); handItemSelected(item); handIndiceSelected(i); }} > <i className="chicon-trash" /> Excluir </button> )} </Options> )} </div> </> ))}`
> 
> when the user clicks on the i tag, if he has already scrolled the slide, he is automatically taken to the first card
