### ISSUE TITLE
Images in carousel are not displaying in Production Mode (only in dev)

### ISSUE THREAD

**Issue by kirilchristov** [leandrowd/react-responsive-carousel#401]
I used create react app and the carousel works just fine in dev mode. 
When I run the production though, it's not showing the images in Chrome, just Safari (which is weird). On Safari I have other issues with the opacity though, but it's not such a big deal. In chrome you can follow the link and open the image. No errors in the console too. 

Here is a link to the repo: https://github.com/kirilchristov/wonderful
![Screen Shot 2020-03-05 at 00 49 53](https://user-images.githubusercontent.com/25394481/75964076-71b69180-5e7b-11ea-910d-b7e1d121a158.png)

**Comment by kirilchristov** [comment]
"Problem" solved. I was using % values (like 100%) which was later translated into 1%. So I started using integer values (0.5/1) and everything works just fine.

**Comment by daveteu** [comment]
what was this 100% u talking about about? opacity? Suddenly I'm getting the same problem, when i click to a page, and then back, and the opacity is 0
