### ISSUE TITLE
Infinite option has multiple selected items

### ISSUE THREAD

**Issue by SunburnedGoose** [leandrowd/react-responsive-carousel#416]
![image](https://user-images.githubusercontent.com/984608/78642967-2841d380-7879-11ea-9c85-355546bfc9f5.png)

The carousel has the 'infinite' option selected, the list will have multiple selected items when the first or last item is selected.

This behavior causes an issue with my implementation because it is rendering video when selected.  I can hear audio from both running videos in the selected LI elements.

The expected behavior is only the LI that is in view would be selected.

**Comment by leandrowd** [comment]
So, the way infinite loop works is by repeating the first and the last items hence you getting 2 selected items. 

The issue you have with 2 videos playing at the same time is something different, though. The carousel doesn't control your videos. It's up to you to play or pause them so when moving to a different slide, you can use the `onChange` handler to play/stop the video.

**Comment by leandrowd** [comment]
You got me with a bit of spare time so here it goes, I added support for better managing videos. Check this example where I can play/stop videos and also extract thumbnails: https://github.com/leandrowd/react-responsive-carousel/blob/master/stories/index.js#L458

**Comment by SunburnedGoose** [comment]
My goal is to only have the center item have playing video content, and the rest of the items have static images, even the repeated ones for the infinite loop.

I'm getting isSelected=true in the repeating elements when I have infiniteLoop turned on as expected. Trying out onChange tells me the index and element, and when I set my state with the index, it will turn on the videos in the repeated elements because they are reusing the same model data.

The only way I can know if the model is in a repeated element is if I check the DOM to see if it is the first or last sibling which is not preferred. It would be helpful if there was a property similar to isSelected called something like isRepeatedElement that would let me manage the behavior of the content in those elements.
