### ISSUE TITLE
componentWillReceiveProps is marked as deprecated - Thumbs

### ISSUE THREAD

**Issue by adambreznicky** [leandrowd/react-responsive-carousel#418]
PR #394 resolved use of componentWillReceiveProps in Carousel component but didn't address use of the lifecycle function within Thumbs component. Console warning still remain when thumbnails are enabled on Carousel.

https://github.com/leandrowd/react-responsive-carousel/blob/9cef73e24b36a5998ea6fe45c5e5e3942211535e/lib/components/Thumbs.js#L70

With React 16.9 the lifecycle function "componentWillReceiveProps" is marked as deprecated will be even removed in React 17.

**Comment by leandrowd** [comment]
This method was marked as UNSAFE until a proper solution is implemented. Get the latest version to stop the warning.
