### ISSUE TITLE
How to use different images for Thumbs and Carousel

### ISSUE THREAD

**Issue by Petrik626** [leandrowd/react-responsive-carousel#432]
Hello. Could you provide information about how to use different images for Thumbs and Carousel?
Also, Have I chance using separately Thumbs component and Carousel component?

**Comment by leandrowd** [comment]
To use different thumbs, use the prop **renderThumbs**, check this example: https://github.com/leandrowd/react-responsive-carousel/blob/master/stories/02-advanced.js#L74

To show only the carousel, without the **Thumbs**, pass a prop **showThumbs={false}**.

**Comment by Petrik626** [comment]
@leandrowd Thanks for a quick answer. But I have an issue. Can I use "renderThumbs" prop in version "3.1.50"? I am passing a render function, but it looks like this is not working. Also, I can not use version 3.2.4 because it has an issue with determining the end of images in the carousel

**Comment by leandrowd** [comment]
Only available in 3.2.4. Could you raise an issue with an example about the problem you reported with determining the end of the images?

**Comment by Petrik626** [comment]
@leandrowd Yes, sure. I will collect and provide you information soon
