### ISSUE TITLE
build error for 3.2.4

### ISSUE THREAD

**Issue by Liuminke1996** [leandrowd/react-responsive-carousel#433]
└─ react-responsive-carousel@3.2.4
Done in 2.99s.
yarn run v1.19.1
warning package.json: No license field
$ roadhog build
Creating an optimized production build...
Failed to compile.

home.b4c058e459aa941b788d.js from UglifyJs
SyntaxError: Unexpected token punc «,», expected punc «:» [./~/react-responsive-carousel/lib/cjs/components/Thumbs.js:94,0]

error Command failed with exit code 1.

but v3.155 build success 
└─ react-responsive-carousel@3.1.55
info All dependencies
└─ react-responsive-carousel@3.1.55
Done in 6.68s.
PS E:\code\troy-eye-ui> yarn build
yarn run v1.19.1
warning package.json: No license field
$ roadhog build
Creating an optimized production build...
⚠️ ⚠️ ⚠️  It\'s not recommended to use webpack.config.js, since roadhog\'s major or minor version upgrades may result in incompatibility. If you insist on doing so, please be careful of t
he compatibility after upgrading roadhog.

Compiled successfully in 54.5s.

File sizes after gzip:

**Comment by leandrowd** [comment]
I never used **roadhog** but this seems to be related as the bundler not understanding common js... Maybe you are missing a loader. Ping us if you find a solution...
