### ISSUE TITLE
A problem with the arrows , need little help , thanks !

### ISSUE THREAD

**Issue by Gil-Porsansky** [leandrowd/react-responsive-carousel#434]
Hi , the carousel works great , but suddenly the left and right arrows jumped to top of the carousel
i didn't changed nothing in the code 

see image : 
![image](https://user-images.githubusercontent.com/53540411/80281018-e5a14780-8710-11ea-8ac9-9a19d81b0684.png)

my carousel : 
`  <Carousel showArrows={true} infiniteLoop={true} showStatus={false} autoPlay={true} interval={3000} transitionTime={1200} emulateTouch={true}>
            <div className={styles.item}>
                <img src={img1} alt="livingroom" />
            </div>
            <div className={styles.item}>
                <img src={img1} alt="livingroom" />
            </div>
        </Carousel>`

**Comment by leandrowd** [comment]
Looks like it's missing the styles,  check if you have the right path being imported and the right loader

**Comment by Gil-Porsansky** [comment]
thanks for the response i will check as soon as possible and i let you know
