### ISSUE TITLE
Change the height of the carousel depending on screen size

### ISSUE THREAD

**Issue by veronicapc92** [leandrowd/react-responsive-carousel#436]
Hi,

Is it possible to change the height of the carousel depending on the screen size? Like some sort of styling where I can set: height: 80vh or a media query. If so, how can I do this?

Apologies if this has already been explained somewhere else, I can't seem to find the list of features anymore (I believe it was available in npmjs.com when I first discovered this package).

Many thanks!

**Comment by leandrowd** [comment]
Hey @veronicapc92 , you can copy and modify the styles or just add a new css override.

**Comment by veronicapc92** [comment]
Thanks @leandrowd !
