### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by Petrik626** [leandrowd/react-responsive-carousel#437]
Hi. Could you please provide information about using lazy loading images on react-responsive-carousel. If lazy loading is possible could you please provide examples of using?

**Comment by Mulder90** [comment]
Hi,
I was looking for this feature and a very quick solution could be something like this:

```
<Carousel
  renderThumbs={() =>
    images.map(({ source, caption }, index) => (
      <LazyLoadImg src={source} alt={caption} key={index} />
    ))
  }
  >
  {images.map(({ source, caption }, index) => (
    <div key={index}>
      <LazyLoadImg src={source} alt={caption} />
    </div>
  ))}
</Carousel>
```

where `LazyLoadImg` could be done very very quickly with https://addyosmani.com/blog/lazy-loading/ (otherwise you need to implement the logic with some data attribute and `IntersectionObserver`:

```
const LazyLoadImg = (props) => {
  return <img {...props} loading="lazy" />;
};
```

I hope it could help :)

**Comment by dgrahamlong** [comment]
@Petrik626 You could try mapping the children like so 

```
<Carousel>
{children.map((child, index) => {
          if (
            index === selectedItem ||
            index === selectedItem + 1 ||
            index === selectedItem - 1
          ) {
            return child;
          } else return <></>;
        })}
/>
</Carousel>
```
That way only children holding hands with the current index will be rendered and fetched. You want to render the surrounding indices in case the user has slow internet, the next image will be fetched vs having to wait every time they click next.
