### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by dgwyer** [leandrowd/react-responsive-carousel#438]
I've been checking out a few different React image sliders. This one looks very good. I'm just wondering if you plan to add support for fullscreen at any point?

e.g. similar to this. https://www.linxtion.com/demo/react-image-gallery/

**Comment by leandrowd** [comment]
It's very straightforward to implement full screen support if you use the onClick handler provided and provide your own css. We try no to bake everything in to keep is lightweight.

**Comment by dgwyer** [comment]
Thanks for the quick reply.
