### ISSUE TITLE
IE11 compatability issue

### ISSUE THREAD

**Issue by erikarenhill** [leandrowd/react-responsive-carousel#439]
I'm running a react-project built with webpack and there is 1 line that breaks IE11 due to ES6 features being used (dynamic property name)

https://github.com/leandrowd/react-responsive-carousel/blob/master/src/cssClasses.ts#L7

The above line is the only thing that I found that needs to be fixed to have it work in IE11. 

Would you consider a PR if I add one for it? That way we can have IE11 supported without transpiling the component locally to ES5 before building.

**Comment by leandrowd** [comment]
Sure, send the pr and we will get it through...

**Comment by erikarenhill** [comment]
> Sure, send the pr and we will get it through...

Looking a bit more into this I notice the babelrc actually exclude IE11 explicitly, if the component should support IE11 (what's your take on this?) maybe it's just easier to include it to get the transpilation done if more ES6 features are used in the future.

Because it would feel quite cumbersome to do a PR with a code change to support IE11 when babel is configured to ignore IE11 in any future other code changes.

**Comment by ludem** [comment]
Hi, I got an error on IE11 because of the following lines in Thumbs.js, where shorthand property names (ES2015) are used (not supported in IE11):

 _this.setState(function (_state, props) {
        return {
          itemSize,
          visibleItems,
          firstItem: showArrows ? _this.getFirstItem(props.selectedItem) : 0,
          lastPosition,
          showArrows
        };
      });

**Comment by leandrowd** [comment]
Feel free to submit the PR adding the Babel config for ie11.

**Comment by leandrowd** [comment]
Babel config has been changed and a new version published. Could you please update and confirm that your problem is resolved? thanks

**Comment by ludem** [comment]
Unfortunately my problem is not resolved with the new version. I got the same error above in development mode, while in production the following line breaks:

`m=function(e){return v()({"carousel-root":!0,[e]:!!e})}`

[e] is a computed property name, not supported in IE11

**Comment by erikarenhill** [comment]
> Unfortunately my problem is not resolved with the new version. I got the same error above in development mode, while in production the following line breaks:
> 
> `m=function(e){return v()({"carousel-root":!0,[e]:!!e})}`
> 
> [e] is a computed property name, not supported in IE11

This is the same issue as I reported in the first post, I could solve this locally by changing the babelrc, will try again with this new one
