### ISSUE TITLE
Allow render props as custom status, instead of only string

### ISSUE THREAD

**Issue by GeorgeWL** [leandrowd/react-responsive-carousel#445]
# Use Case:
want 
```jsx 
<div className='imageCount>
      <i className='icon-camera'  />
      <p>{`${current} / ${total}`}</p>
 </div>
```

as the status of the carousel, but with current behaviour this isn't possible, except by using css to absolute position said icon inline with where the library currently places the status indicator string.

**Comment by Seeila** [comment]
I second that, I don't like the fact that we have to use the external controls just to be able to style de status. In my case, I only needed to add a span inside of the paragraph.
```
<p className="carousel-status">
    {current} <span className="carousel-status__devider></span> {total}
</p>
```

**Comment by GeorgeWL** [comment]
Not stale

**Comment by GeorgeWL** [comment]
not stale

**Comment by GeorgeWL** [comment]
not stale

**Comment by kes3583** [comment]
I also  need that statusFormatter allow React Node not only string.

**Comment by GeorgeWL** [comment]
not stale

**Comment by GeorgeWL** [comment]
Not stale

**Comment by lucasdoloh0v** [comment]
Not stale

**Comment by GeorgeWL** [comment]
Reopen

**Comment by GeorgeWL** [comment]
> Not stale

there's been zero updates to this is 2 years, it's fair to say it's a dead project, I'd suggest switching which module you use, or forking and fixing yourself

**Comment by GeorgeWL** [comment]
> Not stale

there's been zero updates to this in module in 2 years, it's fair to say it's a dead project, I'd suggest switching which module you use, or forking and fixing yourself

@lucasdoloh0v
