### ISSUE TITLE
Thumbnails. Erroneous determination of the end of images in thumbnails

### ISSUE THREAD

**Issue by Petrik626** [leandrowd/react-responsive-carousel#451]
Hello everyone. Did someone face the issue of erroneously determining the end of images in the thumbnail section? 
Because of this, the left / right arrows in the thumbnail section are disabled and there is no way to scroll the thumbnail ribbon

**Comment by wvha** [comment]
https://github.com/leandrowd/react-responsive-carousel/issues/353#issuecomment-575444848

Adding in 'selectedItem' as a prop to the carousel solved this issue for me and I'm able to navigate the thumbnail ribbon now.
