### ISSUE TITLE
Weird swipeScrollTolerance when infiniteLoop

### ISSUE THREAD

**Issue by bsurai** [leandrowd/react-responsive-carousel#455]
The case:
* a carousel has 9 children
* the issue appears when you try swipe a bit from the initialBoundary slide to the finalBoundary slide
* the correct behavior is a slider should return to initial position
* but the slider goes through all slides and after that returns to the initial slide.

The solution is very simple:
there is a code [here](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.tsx#L506)
```js
const hasMoved = Math.abs(axisDelta) > this.props.swipeScrollTolerance;
```
we should move that code up (to 494th row) and as result it should look as 
```js
let position = currentPosition + 100 / (this.state.itemSize / handledDelta);
const hasMoved = Math.abs(axisDelta) > this.props.swipeScrollTolerance;

if (this.props.infiniteLoop && hasMoved) {
  // When allowing infinite loop, if we slide left from position 0 we reveal the cloned last slide that appears before it
  // if we slide even further we need to jump to other side so it can continue - and vice versa for the last slide
if (this.state.selectedItem === 0 && position > -100) {
   position -= childrenLength * 100;
 } else if (this.state.selectedItem === childrenLength - 1 && position < -childrenLength * 100) {
   position += childrenLength * 100;
 }
}
```

**Comment by GregBoss** [comment]
ConfirmedI encountered the same problem

**Comment by GregBoss** [comment]
Confirmed
I encountered the same problem. Pls fix this in next update
