### ISSUE TITLE
Is there a way to center first and last slides using centerMode

### ISSUE THREAD

**Issue by robinll** [leandrowd/react-responsive-carousel#457]
I'm using this plugin and if I don't use an infiniteLoop, the first and last slides are not centered.  Is there a way to make them centered?

**Comment by al13bash** [comment]
Have similar issue. Is there any solution?

**Comment by robinll** [comment]
I never figured it out.  I decided to use a different npm module.

**Comment by trinonsense** [comment]
i tricked with `infiniteLoop` then hide the first and last child with opacity `0`

**Comment by Igorinni** [comment]
Tell me, did you manage to solve this problem?

**Comment by robinll** [comment]
It's been a while, but I think I managed to solve the issue using
centerMode and centerSlidePercentage.  For example, if the
centerSlidePercentage is set to 90 then there is 5% of the total width on
either side of the center slide to work with.
