### ISSUE TITLE
Is it possible to render thumbs when the carousel children are gatsby-image components?

### ISSUE THREAD

**Issue by josub** [leandrowd/react-responsive-carousel#460]
When using the [gatsby-image component ](https://www.gatsbyjs.org/packages/gatsby-image)instead of an `<img> `element the html is a `<div> `containing another `<div>` and then image source in a `<picture>` element that is a sibling, and not a child, to the prev `<div>`.

Is there any way to config the react-responsive-carousel with the renderThumbs parameter to grab the image source with this element structure from the picture element srcset use that to generate thumbs?

See below for the html that is rendered from the gatsby-image component.

```
<li class="slide">
  <div class=" gatsby-image-wrapper" style="position: relative; overflow: hidden;">
    <div style="width: 100%; padding-bottom: 100%;"></div>
    <picture>
      <source srcset="/static/882188fcdsadda.jpg 225w,">
    </picture>
    <noscript>
      <picture>
      <source srcset="/static/882188fcdsadda.jpg 225w," />
      </picture>
    </noscript>
  </div>
</li>
```

**Comment by jasonbcox** [comment]
I ran into this same issue. The thumbnail rendering assumes it's looking for `img` elements in certain places. This works in basic cases, but not when complex wrappers are needed (for example, `StaticImage` from `gatsby-plugin-image`).

I've authored #617 in an attempt to allow you to customize what element type is selected to use for the thumbnails.

**Comment by jasonbcox** [comment]
#617 was rejected since a potential solution for this already exists. While I'm using `gatsby-plugin-image`, I imagine a similar solution will work for you:
```
const MatchStaticImage = (children) => {
  return children;  // just return the list of the entire image components
}
<Carousel renderThumbs={MatchStaticImage}>
  <StaticImage src="myimage.png" />
</Carousel>
```

**Comment by conor-gaughan** [comment]
Hey @jasonbcox when I use `<StaticImage src="myimage.png" />` the main image in the carousel loads but the thumbs still aren't generating. Are they populating for you?

**Comment by jasonbcox** [comment]
The thumbs populate for me, ya.

I have had issues with images >300kb though, so check that. It may be related to this: https://github.com/gatsbyjs/gatsby/issues/32671 or some other interplay between `gatsby-plugin-image` and `react-responsive-carousel`.

**Comment by conor-gaughan** [comment]
Ah interesting, thank you for sharing. Good to know it's supposed to work `StaticImage` but maybe my images are too large. I am going to try to pull it in via graphql and see if that works but I think I saw an issue with that as well. Appreciated!
