### ISSUE TITLE
isSelected is set on DOM elements like the li so react throws an error

### ISSUE THREAD

**Issue by mr365** [leandrowd/react-responsive-carousel#462]
![Screenshot 2020-06-23 at 3 07 22 AM](https://user-images.githubusercontent.com/3664865/85337998-2e059780-b4ff-11ea-81a4-4f143f5b9dc7.png)

**Comment by rkumar1904** [comment]
I'm also having the same problem, unable to understand what is causing the problem. someone, please look into this issue! 🙏
