### ISSUE TITLE
thumbnail selector hidden at the end of the slides

### ISSUE THREAD

**Issue by beblank** [leandrowd/react-responsive-carousel#463]
sometime the selector (black box) is hidden at the end of the slides
lets say i have 10 slides
when selector slide to the 6th image its hidden then when it slide to 7th image it will show the selector

**Comment by mallikaverma** [comment]
The last Image is getting hidden always in the thumbnail carousel. I have used this carousel and showed only 5 thumbnails in first look but now when someone tries to change slide after 5 element thumbnail carousel is not sliding. Previously it was working fine.
