### ISSUE TITLE
updateSizes function fails when mounting again

### ISSUE THREAD

**Issue by travelrus** [leandrowd/react-responsive-carousel#464]
Hey, it is already known issue. Was described here:
https://github.com/leandrowd/react-responsive-carousel/issues/102

Seems like it reproduces again in 3.2.7

I'm not very expirienced in this but maybe it does make sense to relapce the line

`var itemSize = isHorizontal ? firstItem.clientWidth : firstItem.clientHeight;` 

by line

`var itemSize = firstItem ? isHorizontal ? firstItem.clientWidth : firstItem.clientHeight : 0;`

**Comment by paulussimanjuntak** [comment]
yeah, I got this error too, did you already solve it? @travelrus
