### ISSUE TITLE
Add ability to go to any slide 

### ISSUE THREAD

**Issue by vinayagg** [leandrowd/react-responsive-carousel#467]
I have a requirement to add multiple buttons on a slide that can go to random slides.
The issue is 

- if I am on slide1 and try to go to slide3, it will show sliding to slide2 and then sliding to slide3. Slide 2 visualization is unnecessary. Also it is a problem if I go from slide1 to slide20.

- What I need is that when I click on the button, visually it seems to just transition to "next" or "previous" slide, but in reality, I can specify the slide number it is really going to.

Is there a way to do this?

**Comment by robpaveza** [comment]
This would be a nice to have; it'd enable us to choose a different thumbnail gallery, for instance.

**Comment by vinayagg** [comment]
@leandrowd We are having little trouble undertsanding the architecture and how to do it right.
If you can guide us the right way to do this, we can do it and contribute code back. Everyone wins. What do you think?

To be clear about our requirement - we are using this slider for a full screen presentation. So user cannot see what is next. We have some buttons on each slide that can be configured to go to any other slide with a "swipe forward" or "Swipe backwards" transition.

Lets say we have 10 slides, slide 1 has buttons that can go to slide 2 (swipe forward animation), slide 5 (swipe forward animation without showing sides 2,3,4), slide 10 (slide backwards animation)

When a button is pressed, we know what should be next or previous slide, we reorder the slides as needed. However this reordering is triggering a state change and triggers a re-rendering. This causes a whole lot of other  issues.

I hope that is clear. Would you guide us how to fix this issue?

**Comment by leandrowd** [comment]
Hey @vinayagg , the carousel was not built with this in mind. As a carousel, it puts all the items one after another and go from a to b passing through what is in the way, and that's it! To accomplish what you want, it would probably require a bit of refactoring. I'm only keeping the lights on at this moment, merging any contributions and releasing, and discussing approaches on PR's but I don't have any spare time schedule to spend on this component. Contributions are completely up to the community. 

If you want to try your hand on it, I'm glad to discuss your solution once you have one in mind but no promises or time commitment from my side, I will get to it when I can.

**Comment by blainegarrett** [comment]
You can specify the slide target position via the prop: 

```
selectedItem={activeSlideIndex}
```

I have the active initial slide controlled by the parent component's state. Works well.

**Comment by GabrielmLinassi** [comment]
> You can specify the slide target position via the prop:
> 
> ```
> selectedItem={activeSlideIndex}
> ```
> 
> I have the active initial slide controlled by the parent component's state. Works well.

OP is looking for a way to do it without the sliding effect. This does go to the specified index, however it's sliding to it.
