### ISSUE TITLE
emulateTouch trigger click event when swipe

### ISSUE THREAD

**Issue by xzysun** [leandrowd/react-responsive-carousel#468]
When use emulateTouch with swipeable on PC & chrome, the `onClickItem` callback trigger after `onSwipeEnd` called if the swipe distance is not enough to goto next/previous page. 

see the demo: https://codesandbox.io/s/react-responsive-carousel-06me4

I see there is a `cancelClick` in the code, I think it should to be set false when swipe end with a delay of transitionDuration 
https://github.com/leandrowd/react-responsive-carousel/blob/dae409dba878adc0001d9eb15b647914e05b8119/src/components/Carousel.tsx#L459-L466

something like 
```
setTimeout(() => {
     _this.setState({ cancelClick: true });
}, _this.props.transitionTime);
```

**Comment by saurabhkacholiya** [comment]
@xzysun  I am facing the same issue. were you able to solve this?
