### ISSUE TITLE
i keep getting this issue

### ISSUE THREAD

**Issue by Tenoywil** [leandrowd/react-responsive-carousel#470]
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: Thumbs

**Comment by k0o** [comment]
Me too, have you found a solution?

**Comment by k0o** [comment]
up!

**Comment by jleider** [comment]
This is a duplicate of #454
