### ISSUE TITLE
In centered mode is there a way to customize how much width does the centered slide take up?

### ISSUE THREAD

**Issue by la55u** [leandrowd/react-responsive-carousel#471]
I would like to have the centered (active) slide to be slightly less wide, around 60%, and and two slides on the left and right to fill the remaining space symmetrically. Thank you

**Comment by LarisaMagdalenaCalin** [comment]
I have the same issue. Have you found a solution?

**Comment by la55u** [comment]
I found out later there is a `centerSlidePercentage` prop available. Would be nice to have a list of all available props somewhere.

**Comment by CollierCZ** [comment]
The prop is listed in the [Storybook for center mode](http://react-responsive-carousel.js.org/storybook/?path=/story/01-basic--center-mode).
