### ISSUE TITLE
Mixing img tag and video tag 

### ISSUE THREAD

**Issue by NavehMevorach** [leandrowd/react-responsive-carousel#473]
I am trying to create a Carousel of images and embedded Youtube videos (the first item is a youtube video and the rest are images) I am using the React Responsive Carusel npm package but I can't find a way to create the carousel I want without bugs.

I saw a solution over here but it's only for videos.

Here is my code at the moment:
```
import React from 'react'
import 'react-responsive-carousel/lib/styles/carousel.min.css' // requires a loader
import { Carousel } from 'react-responsive-carousel'
import ReactPlayer from 'react-player'
const ModalImagesPreview = () => {
    
  return (
    <div>
      <Carousel>
        <div>
          <ReactPlayer
            url='https://www.youtube.com/watch?v=ysz5S6PUM-U'
            volume='1'
            muted
            width='100%'
            playing={true}
          />
        </div>
        <div>
          <img src='https://cdn.dribbble.com/users/2146089/screenshots/12387473/media/bf9ffb522fe68ba57ebdc62bc3f16cc5.png' />
        </div>
        <div>
          <img src='https://cdn.dribbble.com/users/427857/screenshots/12318706/media/f30f662dbf160022412812881b2afb43.jpg' />
        </div>
      </Carousel>
    </div>
  )
}

export default ModalImagesPreview
```

**Comment by leandrowd** [comment]
Disabling thumbs or passing a custom renderThumbs prop should help.  Have you tried any of that?

**Comment by NavehMevorach** [comment]
> Disabling thumbs or passing a custom renderThumbs prop should help. Have you tried any of that?

Thanks! I used renderTuhmbs and it worked! 
The youtube video isn't in the correct height but I guess it easily can be solved with CSS or the height prop

**Comment by apoorva-shah** [comment]
Hello @leandrowd 
My video is rendered in html via videojs.

So how can I take that video in slider alongwith images?

I am able to mix youtube videos and images but not my custom video html.

Can you please suggest?
