### ISSUE TITLE
When Im using a vertical image the carousel height gets that image height. Where I should put the height prop?

### ISSUE THREAD

**Issue by NavehMevorach** [leandrowd/react-responsive-carousel#474]

**Comment by Orient87** [comment]
I have the same problem, I am using Next.js. When scrolling horizontally, everything works well. When scrolling vertically, at the first load, the container with the .axis-vertical.slider-wrapper classes has a height of 1px, when the browser window is resized, the height becomes 25px. The height of the card is 97px and it is hidden. How can you set the height of the carousel when scrolling vertically? When I try to set the height in my style.css for the carousel classes it doesn't work. Problem in all browsers.
