### ISSUE TITLE
showthumbs does not work when custom Image tag is used 

### ISSUE THREAD

**Issue by tarun1992** [leandrowd/react-responsive-carousel#481]
Hi, I am using a "cloudinary" CDN to render images in the carousel. 
The tag is - 
    ` <Carousel showThumbs={false} showArrows={true} async >
        <Image cloudName="sample" publicId="image.jpg" >
            <Transformation quality="auto:good" width="679" crop="scale" />
        </Image>
    </Carousel>`

The above sample code works but when I try to show thumbs by showThumbs={true}, the thumbs don't appear. 
As soon as I change the code with `<img src="images.jpg"/>` It works perfectly.

The issue can be checked on the URL - https://bikersdunia-ocl7skiff.vercel.app/royal-enfield-350

Any help would be appreciated.

**Comment by anandarizki** [comment]
Found this warning in the console:
`Note that it's not possible to get images rendered inside custom components.`
