### ISSUE TITLE
Images are not rendering

### ISSUE THREAD

**Issue by PatrikKozak** [leandrowd/react-responsive-carousel#482]
The code is identical to your 'Usage' example and none of my own images are rendering, only showing a small box. Could the issue be with my images and where they are placed in my files?

**Comment by navneet-kumar** [comment]
Can you share your snippet, usually this happens when you haven't imported the CSS.

`import 'react-responsive-carousel/lib/styles/carousel.min.css';`

**Comment by SuharshTyagii** [comment]
Hey man, I too was having trouble with putting images, but it turns out, only images that are put in the 'public' folder are working. So move your images to there. Or host them on a server and put it's link in the src.
