### ISSUE TITLE
First and Last Slides are duplicated when Carousel is made infinate.

### ISSUE THREAD

**Issue by weignerg** [leandrowd/react-responsive-carousel#485]
Screen readers read the same first and last carousel list items twice.

This was also mentioned in a previous issue a while back but closed out for some reason.
https://github.com/leandrowd/react-responsive-carousel/issues/395#issue-557528643

**Comment by apoorva-shah** [comment]
Hello @leandrowd,

Is there any way infinite=true can work without duplication of li?

Due to that issue my last video (using videojs) is not loading.

Thanks

**Comment by scalablecodes** [comment]
This  issue is back
