### ISSUE TITLE
How detect item a item change?

### ISSUE THREAD

**Issue by akiosTerr** [leandrowd/react-responsive-carousel#493]
How can I detect if the image was changed/swiped? also how do I know which image was selected?

is there a ready function/prop to know that ?

**Comment by gongjoonamu** [comment]
You can pass a callback to the `onChange` prop of the Carousel. When a change (scrolling the carousel, using directional buttons, selecting a thumb, etc) occurs that changes which item is selected, the `onChange` will be triggered and provide your callback function with both the index and item.

Here's the code: https://github.com/leandrowd/react-responsive-carousel/blob/6378163876ce3fa4c67a5ef7634eff542d2a6a51/src/components/Carousel.tsx#L37

And here is an example of how you can use the `onChange` and `useState` to keep track in your wrapper component what index is selected. Then based on this value you can get from your slides what the selected item/image is by accessing it in the array based on this index. 

```
import { Carousel } from 'react-responsive-carousel';
import 'react-responsive-carousel/lib/styles/carousel.min.css'; 

export const MyCarouselExample = ({slides}: {slides: ReactChild[]}) => {
    const [ currentSlideIndex, setCurrentSlideIndex] = useState<number>(0);
    
    return <Carousel onChange={(index) => setCurrentSlideIndex(index)}>{slides}</Carousel>
}
```

Based on this example, I would know that `slides[currentSlideIndex]` is the image/item that is currently selected.
