### ISSUE TITLE
Unable to remove the blackspace around the youtube carousel.

### ISSUE THREAD

**Issue by prajwolrg** [leandrowd/react-responsive-carousel#499]
I am copying the implementation as in: [StoryBook]( http://react-responsive-carousel.js.org/storybook/?path=/story/02-advanced--youtube-autoplay-with-custom-thumbs)

![image](https://user-images.githubusercontent.com/18223366/92306501-425e1a00-efaf-11ea-9eed-86526beb3dd5.png)

However I don't want the blackbox  surrounding the youtube videos on either side. Is ther any solution?

**Comment by lgarridoj** [comment]
In an images gallery I changed the value of the `background` property to `transparent` (default value is `#000`). It might work for videos too.

**Comment by abrahamAlonzo** [comment]
repeated from https://github.com/leandrowd/react-responsive-carousel/issues/316

`.carousel .slide{ background: none; }`

do the job
