### ISSUE TITLE
Accessibility issue: ARIA role button is not allowed for given element <li>

### ISSUE THREAD

**Issue by susiekims** [leandrowd/react-responsive-carousel#504]
Both the `thumbs` and `indicators` are causing various accessibility issues because of `role="button"` on the `li` element.

Tested with Axe v4.5.3 and Storybook 

**Axe**:
![image](https://user-images.githubusercontent.com/30587540/93130819-14f52880-f6a1-11ea-82bf-de6090e0fb1a.png)
![image](https://user-images.githubusercontent.com/30587540/93130630-d1022380-f6a0-11ea-92c8-816dc4516847.png)

**Storybook**:
![image](https://user-images.githubusercontent.com/30587540/93130654-db242200-f6a0-11ea-9258-1771ef4007b8.png)
![image](https://user-images.githubusercontent.com/30587540/93130674-e11a0300-f6a0-11ea-8043-cc11b3af25a6.png)

**Comment by AleC77** [comment]
Any update for this?

**Comment by AleC77** [comment]
@susiekims did you find a solution for this issue?
