### ISSUE TITLE
How to stop carousel scaling to the max height of content?

### ISSUE THREAD

**Issue by UPLukeet** [leandrowd/react-responsive-carousel#505]
I have set up a carousel with a display flex:1 to make it take up as much height as available to it which works as intended. but whenever I try and set the content to be 100% instead of the content scaling to fit the size of the carousel, the carousel will instead scale to the 100% of the size of the content in, how do I fix this you can see the size the carousel should be when setting a height for the div in question(.image-iframeContainer).

sandbox link
https://codesandbox.io/s/sleepy-sunset-jqjst?file=/src/styles.scss:478-500

**Comment by cbenning** [comment]
Same question. I want my carousel to be a fixed size, and the image inside to scale to fit the space.

**Comment by UPLukeet** [comment]
Well I managed to fix this issue the answer is on this StackOverflow my answer has a sandbox aswell you can fiddle with and see if the answer works for you, https://stackoverflow.com/questions/63957956/how-to-stop-images-within-a-flexbox-container-ignoring-the-heigth-set-by-parent
let me know if this helps you :)
