### ISSUE TITLE
Is useKeyboardArrows prop supported.

### ISSUE THREAD

**Issue by Sumit2105** [leandrowd/react-responsive-carousel#514]
I want an ability to navigate through arrows of the keyboard. In many of the documentation, I can see useKeyboardArrows, Provides the ability to do the same. But this doesn't seem to work for me.

**Comment by nightflash** [comment]
For some reason, you have to click on the image before kb navigation will work.

**Comment by blainegarrett** [comment]
Is it possible to expose a ref to trigger the touch event to give the carousel focus?
In presentation mode, it would be great to just hit the arrow keys w/o first having to interact with the component. 
There doesn't seem to be any public refs available.

**Comment by leandrowd** [comment]
Please create a pull request with that and I'm happy to publish it...

**Comment by leandrowd** [comment]
All done, published as 3.2.11 - thanks for the contribution.
