### ISSUE TITLE
How can I use the carousel as home page background?

### ISSUE THREAD

**Issue by AdityaSaroj** [leandrowd/react-responsive-carousel#516]
I have made a Background component with only React Responsive Carousel containing four video slides on autoplay. How can I use it as the background?

My App.js has three components:
Background
TopNav
LeftNav

 I tried changing the carousel style to 
  height: 100vh;
  width: 100vw;
  position: fixed;
  top: 0;
  left: 0;
in carousel.css.

But it does not work. Any ideas?

**Comment by blainegarrett** [comment]
What about it does not work?
