### ISSUE TITLE
Cannot read property 'x' of null

### ISSUE THREAD

**Issue by LokendraSYFnp** [leandrowd/react-responsive-carousel#518]
Getting Cannot read property 'x' of null in the following code in the line      var i = r - this.moveStart.x;.

key: "_handleSwipeMove",
          value: function e(t) {
            var n = d(t),
              r = n.x,
              o = n.y;
            var i = r - this.moveStart.x;
            var a = o - this.moveStart.y;
            this.moving = true;
            var u = this.props.onSwipeMove({
              x: i,
              y: a
            }, t);
            if (u) {
              t.preventDefault()
            }
            this.movePosition = {
              deltaX: i,
              deltaY: a
            }
          }
        }

Using react-responsive-carousel": "^3.1.30".

**Comment by renancleyson-dev** [comment]
I didn't really understand your comment. What are you trying to achieve? Can you try to provide me a reproduction of your issue by forking [this sandbox](https://codesandbox.io/s/cool-pond-jgtvk)?
