### ISSUE TITLE
Please provide a additional prop for the thumbnail height as thumbnail width

### ISSUE THREAD

**Issue by Mr-Usman** [leandrowd/react-responsive-carousel#519]
Hi, this is an amazing tool to work with!
I just want to say please add a prop for setting the thumbnail height for different size of images.
The Reason for rising this is an issue because it looks weird as it's breaking the sequence for displaying all images in the same pattern.

Regards.

**Comment by renancleyson-dev** [comment]
I think this is what the `dynamicHeight` prop does. Here's an example from the storybook: http://react-responsive-carousel.js.org/storybook/?path=/story/01-basic--dynamic-height-images
