### ISSUE TITLE
How do I use renderIndicator

### ISSUE THREAD

**Issue by MiguelMachado-dev** [leandrowd/react-responsive-carousel#523]
Hey there
In a project I want to render the [indicators](https://github.com/leandrowd/react-responsive-carousel#indicators) with numbers, not boxes, so, how can I use this props on my Carousel?

```jsx
const arrayTest = ["/home/banner.png", "/home/banner.png"];

<Carousel
  showThumbs={false}
  showStatus={false}
  showIndicators={false}
  infiniteLoop
>
  {arrayTest &&
    arrayTest.map((image, index) => (
      <Item key={index}>
        <img src={image} />
      </Item>
    ))}
</Carousel>
```

**Comment by Vitali883** [comment]
`
const renderIndicator = (clickFn, isSelected, index, label) => {
	return (
		<div
			onClick={clickFn}
			className="my-own-indicator"
		/>
	);	
};

return (
	<Carousel
	    renderIndicator={renderIndicator}
	>
	    {items}
	</Carousel>
);
`
Simple example

**Comment by renancleyson-dev** [comment]
Here's an example of what you can do:
```javascript
const indicatorStyles = {
  display: 'inline-block',
  marginRight: '10px',
  color: '#fff',
  cursor: 'pointer',
};

const arrayTest = ["/home/banner.png", "/home/banner.png"];

// on component
<Carousel
  showThumbs={false}
  showStatus={false}
  infiniteLoop
  // gives it a component
  renderIndicator={(
    onClickHandler: (e: React.MouseEvent | React.KeyboardEvent) => void,
    isSelected: boolean,
    index: number,
    label: string
  ) => (
    // it will render inside an ul element
    <li
      style={{ ...indicatorStyles, opacity: isSelected ? '1' : '0.7' }}
      onClick={onClickHandler}
      onKeyDown={onClickHandler}
      value={index}
      key={index}
      role="button"
      tabIndex={0}
      aria-label={`${label} ${index + 1}`}
    >
      {/* render the number instead of a box*/}
      {index + 1}
    </li>
  )}
>
{arrayTest &&
    arrayTest.map((image, index) => (
      <Item key={index}>
        <img src={image} />
      </Item>
    ))}
</Carousel>
```
I removed the line  ```ShowIndicators={false}``` since the flag should be true to render the indicators.

I am not sure, though, if your issue was not know how to render it or the documentation that was hard to understand.

**Comment by Xuffasch** [comment]
Hello,

I was wondering if we need to rewrite the whole renderButton function for an override of its style.
I'd like to just change the colour of the indicator to have a better contrast with my pictures.

I'm not sure how to the code example in Storybook, especially the function withCustomStatusButtonsAndIndicators().
