### ISSUE TITLE
[BUG] Timeout memory leak on unmount

### ISSUE THREAD

**Issue by jaipe** [leandrowd/react-responsive-carousel#524]
### Description

**I noticed #151 references a fix for a similar issue, but it still seems to be a problem.**

When the Carousel unmounts and then remounts, `onChange` handlers fire twice and a `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.  at Carousel` error shows.

### Notes

After debugging, I can see that the timeout is only cleared if `this.state.initialized` is true. But `setupAutoPlay` is called before the `initialized` state has been (asynchronously) set to true. I assume this is leaving an interval where an unmount can happen without a cleanup.

### Repro

https://codesandbox.io/s/busy-shamir-3tpx7?file=/src/App.jsx

### Potential Fix

The following diff seems to address this (it only calls bindEvents and setupAutoPlay after the `initialized` state has been applied). I can PR this if you're happy with it:

```diff
diff --git a/node_modules/react-responsive-carousel/lib/js/components/Carousel.js b/node_modules/react-responsive-carousel/lib/js/components/Carousel.js
index 329affd..251ea3c 100644
--- a/node_modules/react-responsive-carousel/lib/js/components/Carousel.js
+++ b/node_modules/react-responsive-carousel/lib/js/components/Carousel.js
@@ -537,17 +537,17 @@ var Carousel = /*#__PURE__*/function (_React$Component) {
     value: function setupCarousel() {
       var _this2 = this;
 
-      this.bindEvents();
-
-      if (this.state.autoPlay && _react.Children.count(this.props.children) > 1) {
-        this.setupAutoPlay();
-      }
-
       this.setState({
         initialized: true
       }, function () {
         var initialImage = _this2.getInitialImage();
 
+        _this2.bindEvents();
+
+        if (_this2.state.autoPlay && _react.Children.count(_this2.props.children) > 1) {
+          _this2.setupAutoPlay();
+        }
+
         if (initialImage && !initialImage.complete) {
           // if it's a carousel of images, we set the mount state after the first image is loaded
           initialImage.addEventListener('load', _this2.setMountState);

```

**Comment by brightzoe** [comment]
I have the same issue.
In my shallow opinion,you are right. Why don't PR?

**Comment by RatherSlowTurtle** [comment]
> I have the same issue.
> In my shallow opinion,you are right. Why don't PR?

I can do, if it'll help. I was waiting for a reply from the repo owners before making a PR.

**Comment by RatherSlowTurtle** [comment]
@brightzoe Created a PR. Would you be able to confirm if the fix works ok for you? It seems to do it for me. Thanks.

**Comment by RatherSlowTurtle** [comment]
> @brightzoe Created a PR. Would you be able to confirm if the fix works ok for you? It seems to do it for me. Thanks.

Actually, after playing with this a little more, it seems to fix some issues, but it seems to cause a problem with the wrap-around/loop logic. Could potentially be related to async state in `moveTo` (maybe [this](https://github.com/RatherSlowTurtle/react-responsive-carousel/blob/3dfb406756803377b7c63c7b3e86932d8a746118/src/components/Carousel.tsx#L592) function could get the state from the callback function instead of directly from `this.state.selectedItem`). It's a big change to alter that though, so not sure. I'll decline the PR for now, unless anyone has any other ideas.
