### ISSUE TITLE
Timer does not reset when the carousel image is changed through indicators

### ISSUE THREAD

**Issue by roboGOD** [leandrowd/react-responsive-carousel#525]
## Issue

Timer does not reset when the carousel image is changed through indicators in case `stopOnHover` is false.

## Steps to reproduce

1. Create a basic carousel with `autoPlay` as `true` and `stopOnHover` as `false`.
2. Change the image through the indicators.

**Actual**: If the image is about to change with `autoPlay` and we change the image through the indicators, the timer does not reset and sometimes the image automatically changes immediately after it is changed through the indicators. So, the user is not able to see the image and has to change again.

**Expected**: The timer should reset when the image is changed through the indicators.

## Screengrab

![carousel_issue_1](https://user-images.githubusercontent.com/35372329/99245674-fbe82f80-2829-11eb-989c-bc02a94e56ce.gif)

## Links

[Code Sandbox](https://codesandbox.io/s/adoring-payne-wpdcw?file=/src/Carousel.js)

**Comment by Vitali883** [comment]
Same issue. Fixed?

**Comment by roboGOD** [comment]
> Same issue. Fixed?

I fixed it by manually calling the ```resetAutoPlay``` function in ```onChange``` callback using the ```ref``` of the Carousel. Sample code below.

1. Create a ref:

```const carouselRef = React.useRef(null);```
  
2. Pass the ref in the Carousel and call the resetAutoPlay function in onChange:

```
    <Carousel
      ref={carouselRef}
      stopOnHover={false}
      autoPlay
      onChange={() => {
        if (carouselRef.current) {
          carouselRef.current.resetAutoPlay();
        }
      }}
    >
       ...
    </Carousel>
```

**Comment by Vitali883** [comment]
Thank you! Works for me!
