### ISSUE TITLE
Slide overlap on closing pop up

### ISSUE THREAD

**Issue by CATLN** [leandrowd/react-responsive-carousel#529]
I have a link on More Information which gives pop up and when closes the pop up window the slide is as below screen
![image](https://user-images.githubusercontent.com/65340344/101167632-3b06e500-3660-11eb-9e9c-a3faf69665ac.png)

Below is the code implemented

```
<Carousel width="100%"   className={styles.carousel} showStatus={false} 
        autoPlay={this.state.autoPlay} showThumbs={false} infiniteLoop={true} interval={4000}
        showIndicators={false} emulateTouch={true} stopOnHover={true} 
        showArrows={false}  >
        {items}
          
      </Carousel>
```

**Comment by sashberd** [comment]
I have same behaviour as for ltr and rtl
