### ISSUE TITLE
Setting selectedItem prop triggers onChange multiple times with "controlled" value

### ISSUE THREAD

**Issue by blainegarrett** [leandrowd/react-responsive-carousel#531]
This is not a bug per se, but worth noting to save some debugging time for someone potentially. I don't believe there is a change to the codebase to be made.

### The "Issue"
My use case is that I have a list of thumbnails as an image gallery external to the Carousel. When a thumbnail is clicked, it launches the carousel inside of a fullscreen Material-UI modal. The modal and child Carousel are wrapped in a `ModalLightbox` component that maintains internal state to, among other things, tell the Carousel which slide to start with via `selectedItem` prop. However, when using the onChange event to set this state (and thus change the value of `selectedItem`), things get weird - onChange is called multiple times even though the Carousel doesn't appear to actually change slides. After debugging a bunch, the solution was to *not* conceptually treat the Carousel as a [controlled input component](https://reactjs.org/docs/forms.html#controlled-components) and to simply treat the Carousel `selectedItem` prop as the initial slide to show and nothing more.

Given the following
```
 // ModalLightbox
  const [activeSlidePos, setActiveSlidePos] = React.useState(props.activeSlide);
  const slideChangeHandler = (pos) => setActiveSlidePos(pos);
  
  // Update the activeSlidePos when the activeSlide prop changes externally
  React.useEffect(() => {
    if (activeSlidePos != props.activeSlide) {
      setActiveSlidePos(props.activeSlide);
    }
  }, [props.activeSlide]);
```

#### Bad Implementation: selectedItem prop being controlled by state
If the Carousel's `selectedItem` prop is controlled by the state's `activeSlidePosition` as follows, the onChange handler will be triggered at least twice - once for the actual change (eg. clicking right arrow) and another from within the `componentDidUpdate` call stack. Specifically, [this line](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.tsx#L214) which calls `moveTo`, which calls `selectItem`, which calls the this.props.onChange handler again. The `index` argument to the this.props.onChange is different between the two calls. I couldn't exactly pinpoint why, but the net result is that the Carousel would appear to not actually change the slide as the selectedItem. 

```
<Carousel onChange={slideChangeHandler} selectedItem={activeSlidePos}>...</Carousel>
```

#### Good Implementation: Controlling selectedItem via initial prop vs state.
Since the Carousel merely uses the `selectedItem` prop as an initial starting point and can independently navigate, simply use `selectedItem` as the position of the initial slide to show and do not maintain the value from onChange. Now `selectedItem` is decoupled and onChange can be independently used to keep track of the active slide outside of the `Carousel` component.
```
<Carousel onChange={slideChangeHandler} selectedItem={props.activeSlide}>...</Carousel>
```

With the later approach, the slide to show can be manually set externally (`props.activeSlide`) and the actual currently active slide in Carousel can be kept track of in the state. 

### Conclusion
If you treat the Carousel component like a controlled form input component, you're going to have a bad time.

**Comment by renancleyson-dev** [comment]
It seems to me to be kind of a duplication of #204. The [comment of kitfit-dave](https://github.com/leandrowd/react-responsive-carousel/issues/204#issuecomment-437848493) explains very well what is the problem and how we can solve it.
