### ISSUE TITLE
Position Thumbnails slider Above rendered view

### ISSUE THREAD

**Issue by gregStevenard** [leandrowd/react-responsive-carousel#539]
This library is great, and indeed, very customizable. But i'm wondering if there is a solution to place the thumbnails above rather than below. I've looked through the existing issues and couldn't find anything related to this. 

Maybe adding a prop `{positionThumbnail:'above|default'}` would be great?

**Comment by leandrowd** [comment]
You can provide your own css customising the layout as your prefer.

**Comment by gregStevenard** [comment]
Seems like conditionally rendering  `{this.renderThumbs()} ` in [Caroussel.tsx](https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Carousel.tsx#L912) above the rendered view would be much more efficient. Which would allow proper positioning with a config like : `{positionThumbnail:'above'}`

I'm not sure how css would help to move the DOM semantic.

**Comment by gregStevenard** [comment]
Something like this:

```
<div className={klass.ROOT(this.props.className)} ref={this.setCarouselWrapperRef} tabIndex={0}>
                {this.props.positionThumbnails == 'above' && this.renderThumbs()}
                <div className={klass.CAROUSEL(true)} style={{ width: this.props.width }}>
                   {...}
                </div>
                {this.props.positionThumbnails != 'above' && this.renderThumbs()}
            </div>
```

**Comment by leandrowd** [comment]
Feel free to create a PR with the changes required (+ tests and examples)...
