### ISSUE TITLE
Add looping (circular) option

### ISSUE THREAD

**Issue by leandrooriente** [leandrowd/react-responsive-carousel#55]
Add an option to enable loop (circular) of carousel. When user get to the carousel end bring him back to first image.

_Parabéns pelo componente_ 😄

**Comment by leandrooriente** [comment]
I'll try do a pull request soon

**Comment by leandrowd** [comment]
Cool. That would be nice! Let me know if you need help getting started... cheers

**Comment by leandrowd** [comment]
feature added as part of#57

**Comment by leandrowd** [comment]
feature added as part of #57
