### ISSUE TITLE
stopOnHover prop does nothing

### ISSUE THREAD

**Issue by PatrickBokhove** [leandrowd/react-responsive-carousel#552]
Whether you set the prop to `true`, `false` or don't use the prop at all, the autoPlay carousel will always stop when hovering.

**Comment by renancleyson-dev** [comment]
I couldn't reproduce the error, it's not stopping with the flag set to false on this example: https://codesandbox.io/s/competent-breeze-sfn3p?file=/src/Carousel.js

**Comment by PatrickBokhove** [comment]
I think i have found the issue. After adding the stopOnHover property and saving, the browser will hotreload and the property will have no effect on the carousel. However, after hard reloading the page, stopOnHover will actually work as intended. So i guess it might be an instancing issue on development?

You can check it out by adding/removing the stopOnHover prop [here](https://codesandbox.io/s/smoosh-moon-1mxot?file=/src/Carousel.js) and letting the browser hotreload after editing.

**Comment by renancleyson-dev** [comment]
I don't know if we are doing the same thing, but it's still working for me.

![GIF-210208_122529](https://user-images.githubusercontent.com/43624243/107241001-4e8c4e80-6a09-11eb-80f0-588021274eb4.gif)

**Comment by PatrickBokhove** [comment]
It is still occasionally happening on my local environment when hotreloading, but i'm having a hard time trying to reproduce it in an online sandbox. I'm closing the issue for now, as it seems to be fixed after a hard reload. I'll open a new ticket in the future when i find the exact issue and the steps to reproduce it.
