### ISSUE TITLE
Why Carusel does not accept Next.js Image?

### ISSUE THREAD

**Issue by j4nos** [leandrowd/react-responsive-carousel#560]
We use `react-responsive-carousel` in our `Next.js` project. When we replaced `img` with `Image` to optimize thumbnail image size, thumbnails disappeared. Do you know why?

**Comment by leandrowd** [comment]
The carousel looks for img tags to create the thumbs. If there are custom tags, use renderThumbs to generate your thumbs.

https://github.com/leandrowd/react-responsive-carousel#thumbs

**Comment by Leif-W** [comment]
An example of usage would be helpful.  Where to put `renderThumbs`?  Do we need thumbs if `showThumbs={false}`?  And what about `renderItem`, do we use that instead?

Next.js lint doesn't like `<img>` tags and insists upon using `<Image>`.  I'll try to get this working later and update comment with an example.

**Comment by FluidSense** [comment]
Any luck @Leif-W?
I would like to use `next/image` as well, but have toggled the lint rule regarding `no-img-element` off for now.

**Comment by Leif-W** [comment]
Forgot about this.  I got react-responsove-carousel to use the Next.js Image component easily, but then it broke all my styles, and I set it aside to work on other things.

In my example code, I have a Banner component which holds the `<Carousel>`, with some TailwindCSS utility classes, and some styles and applied TailwindCSS in a global CSS file.  But rather than put raw `<img>` tags inside the `<Carousel>` tag, I made a `<Slide>` sub component.  I copy/pasted the `customRenderItem()` function definition and `renderItem` property name and value from the docs, and it seems to have worked. No lint errors, and `<Carousel>` was happy.  But again, I had an issue with styling and hadn't gotten around to debugging yet.  I just trimmed down the example and put some crude style here for demonstration only.  I have thumbs turned off, but if using them, I think it is a similar custom render function.

```
import {Carousel} from 'react-responsive-carousel';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import Slide from '../components/Slide';

const Banner = () => {
    const customRenderItem = (item, props) => <item.type {...item.props} {...props} />;

    return (
        <div className='relative'>
            <Carousel
                renderItem={customRenderItem}
                showThumbs={false}
            >
                <Slide
                    key='0'
                    image='https://site.tld/path/file0.jpg'
                    title='File 0'
                />
                <Slide
                    key='1'
                    image='https://site.tld/path/file1.jpg'
                    title='File 1'
                />
                <Slide
                    key='2'
                    image='https://site.tld/path/file2.jpg'
                    title='File 2'
                />
            </Carousel>
        </div>
    );
};

export default Banner;
```

**Comment by usamairfanteciz** [comment]
I am also trying to use next.js Image component but unable to use it as the thumbs are getting disappeared from the app.

**Comment by UsamaIrfan** [comment]
I have fixed the issue using the renderThumbs property. I am using a combination of tailwindCSS and Next.js. My solution is as follows.

```javascript
  <Carousel
    axis="vertical"
    infiniteLoop={true}
    autoPlay={true}
    swipeable={true}
    renderThumbs={() =>
      product.images.map((img, idx) => (
        <div key={idx} className="w-full h-20 relative">
          <Image
            src={img}
            layout="fill"
            objectFit="contain"
            alt="logo"
          ></Image>
        </div>
      ))
    }
  >
    {product.images.length !== 0 &&
      product.images.map((img, idx) => (
        <Image
          key={idx}
          src={img}
          alt={`${product.title} preview ${idx}`}
          layout="responsive"
          width={650}
          height={650}
          priority={idx === 0}
        ></Image>
      ))}
  </Carousel>
```

My product.images is just an array containing links in the following format.

`["examplelink.com", "examplelink.com"]`


This worked perfectly fine for me.

**Comment by cha2hyun** [comment]
+1

**Comment by btramel** [comment]
This worked for me!

**Comment by jay-stance** [comment]
I am getting this error while using it my next js application

Server Error
TypeError: Super expression must either be null or a function, not undefined

This error happened while generating the page. Any console logs will be displayed in the terminal window.

Here is the image of my code

<img width="1021" alt="image" src="https://github.com/leandrowd/react-responsive-carousel/assets/68084679/7d6c54f1-0e46-4774-8426-ad4e5664ccf9">

**Comment by Leif-W** [comment]
> I am getting this error while using it my next js application
> 
> Server Error TypeError: Super expression must either be null or a function, not undefined

I think it's unrelated.  Look at #738.  Someone said putting `'use client';` at the start of file may help.  I have no idea.

**Comment by Kaustubhx** [comment]
> > I am getting this error while using it my next js application
> > Server Error TypeError: Super expression must either be null or a function, not undefined
> 
> I think it's unrelated. Look at #738. Someone said putting `'use client';` at the start of file may help. I have no idea.

Yeah, I tried adding the 'use client' directive it works just fine as it should.

**Comment by jarrod-finnovate** [comment]
For anyone that stumbles across this in the future, I was able to make a responsive image carousel using the following:

### Image Carousel component
```"use client";

import "react-responsive-carousel/lib/styles/carousel.min.css";
import React from "react";
import { Carousel } from "react-responsive-carousel";
import Image from "next/image";
import "./styles/imageCarousel.scss";

type ImageCarouselProps = {
  images: string[];
};

const ImageCarousel = ({ images }: ImageCarouselProps) => {
  return (
    <Carousel
      infiniteLoop
      showThumbs={false}
      showStatus={false}
      className="image-carousel"
    >
      {images.map((image, i) => (
        <div
          className="image-carousel__image-container"
          key={`carousel-img-${i}`}
        >
          <Image
            src={image}
            alt={`carousel image ${i}`}
            fill
            sizes="100vh"
            style={{
              objectFit: "cover",
            }}
          />
        </div>
      ))}
    </Carousel>
  );
};
```

### SCSS

```
@use "/src/styles/border-radius.scss" as *;
@use "/src/styles/breakpoints.scss" as *;

.image-carousel {
  position: relative;
  width: 100%;
  border-radius: $border-radius-700;
  height: 40rem;
  overflow: hidden;

  &__image-container {
    position: relative;
    height: 40rem;
  }
}

@media screen and (max-width: $breakpoint-200) {
  .image-carousel {
    height: 20rem;
  }

  .image-carousel__image-container {
    height: 20rem;
  }
}

```

The important things here are making sure the container (image-carousel__image-container) is position relative with a width/height and that the Image tag has the fill, sizes and objectFit=cover properties.
