### ISSUE TITLE
Editable Carousel

### ISSUE THREAD

**Issue by Fox4148** [leandrowd/react-responsive-carousel#575]
Sort-order of the carousel editable in two ways;
    - Draggeable thumbs, onMouseDrop should trigger an update for the order
       of the images
    - The Carousel status, the first shown number should be an input with an 
       onChange event

Feature request
@leandrowd edited for clarity

**Comment by leandrowd** [comment]
Care to elaborate?

**Comment by Fox4148** [comment]
Thumbs with a => draggeable prop structured somewhat like that:
draggeable={{
   value:bool
}}
 -> set to drag within container

**Comment by Fox4148** [comment]
[https://github.com/Fox4148/react-responsive-carousel/commit/cd32009fd7ab33d2170a56282fd9f91c1d34b512](url)
