### ISSUE TITLE
autoPlay restart after changing slide

### ISSUE THREAD

**Issue by mbret** [leandrowd/react-responsive-carousel#582]
When disabling autoplay by using `autoPlay={false}`, it does reset back to true after switching one slide. How can we disable it completely ?

**Comment by cdash04** [comment]
I know, so annoying. In the first place the package should have  come by default without any behaviour...

**Comment by zyc** [comment]
Same problem here.

I've tried this workaround but didn't work too:

```
const [autoPlay, setAutoPlay] = useState(false);

<Carousel
        autoPlay={autoPlay}
        onSwipeEnd={() => setAutoPlay(false)}
        onChange={() => setAutoPlay(false)}}
>
```

**Comment by renancleyson-dev** [comment]
There's no workaround, sorry :(
But you guys can use any version of the carousel before 3.2.12 while my fix isn't published.
