### ISSUE TITLE
Make Typescript types available

### ISSUE THREAD

**Issue by eliasm307** [leandrowd/react-responsive-carousel#585]
First of all, this is a great package, thanks for working on this.

My issue is that I am using this with typescript and I can see there are types defined [here](https://github.com/leandrowd/react-responsive-carousel/blob/59ad159f573f2ba77c55b8d7b535bf81b981616d/src/components/Carousel/types.ts) however I cant seem to access these, atleast thats what VS code says, see below. 
![image](https://user-images.githubusercontent.com/13420359/113365308-bc8c2c80-934d-11eb-9ae4-2ce2ba7dd486.png)

I am trying to define the carousel props and as there are quite a few, I am splitting these up and defining them individually then giving them all to the carousel. When defining the props separately in typescript, it would be good if the types could be easily imported from the package and used as required. I can see the main Readme for this repo describes a few of the types for the props if defined individually, why not actually implement this into the package as exported types? e.g. rendering thumbs can be customised by defining props with the following function signatures, it would be good if I could just import a ThumbRenderer function signature type to assign to the custom function I make instead of having to copy this from the docs and implement it manually.
![image](https://user-images.githubusercontent.com/13420359/113365521-69ff4000-934e-11eb-8ee0-db91434f38fb.png)

I would be willing to work on this if the maintainers agree.

**Comment by elramus** [comment]
Yeah, running into this too. Here's the workaround I'm doing:
```
import React, { ComponentProps } from "react"

import { Carousel, Thumbs } from "react-responsive-carousel"

export type CarouselProps = ComponentProps<typeof Carousel>
export type ThumbsProps = ComponentProps<typeof Thumbs>
```

**Comment by yasserzakyw** [comment]
Face the same issue.
I had to be specific with my import path. 

`import { CarouselProps } from 'react-responsive-carousel/lib/ts/components/Carousel/types';`

Works fine now!
