### ISSUE TITLE
renderItem still renders empty slide despite being fed a null value

### ISSUE THREAD

**Issue by tankh99** [leandrowd/react-responsive-carousel#589]
So I'm trying to create a carousel that conditionally shows a video at the first slide, and then images subsequently after. But the renderItem prop keeps on registering a null value as a slide, and there's no way for me to not render the null slide.

```
const customRenderItem = (item: any, props: any) => {
        if(item){
            const Element = item.type
            return <Element {...item.props} {...props} />
        } else{
            return false
        }
    }

    const getVideoThumb = (videoId: string) => ` http://i3.ytimg.com/vi/${videoId}/hqdefault.jpg`;
    // http://i3.ytimg.com/vi/s4evmpyF7Dg/hqdefault.jpg
    const getVideoId = (url: string) => {
        return url.substr('https://youtu.be/'.length, url.length);
    }

    const customRenderThumb = (children: any) =>{
        const mappedThumbs: any = []
        children.map((item: any, index: number) => {
            if(item){
                if(item.length){
                    const items = item.map((image: any, index: number) => {
                        mappedThumbs.push(<img key={index} src={image.props.children.props.src}/>)
                    })
                    return items
                } else {
                    const videoId = getVideoId(item.props.url);
                    mappedThumbs.push(<img key={index} src={getVideoThumb(videoId)} />)
                }
            }
            
        });
        return mappedThumbs
    }
    
```

Here is the code for the carousel

```
<Carousel 
    renderItem={customRenderItem}
    renderThumbs={customRenderThumb}>
        {videoLink &&
            <YoutubeSlide 
            key={"video"}
            url={videoLink}/>
        }
        {images && images.map((image: any, index: number) => {
            return (
                <div key={index} 
                    className="slide-image">
                    <img src={require(`assets/images/${image}`).default} 
                    className={`project-page-image ${isMobile ? 'mobile-slide-image' : ''}`} alt="page image"/>
                </div>
            )
        })}
</Carousel>
```
### Issue
What happens in the above code is that the YoutubeSlide component is supposed to generate on the condition that videoLink is not null. But when videoLink is null, what happens is that a blank slide will be generated at the very start of the carousel, resulting in a mismatch of slides under slide thumbs. 

The picture below shows 4 slides, when there are in fact, only 3 images.

![image](https://user-images.githubusercontent.com/56617918/114388222-fe2a9c00-9bc5-11eb-9802-98249616a9fc.png)

### Possible Fix
Make it possible to not render certain slides by returning false

**Comment by gongjoonamu** [comment]
I ran into this issue as well and addressed it by first creating an array of components that will make up the carousel slides.


I created a hook to create the array of different components based on whatever conditions. Your falsy condition can just spread an empty array aka array stays in tact no need to deal with the nulls. Here's an example of the code:
```

const useGetSlides = ({data} : {data: DataType}) : ReactChild[] => {
if (data) {
        return [
            <FirstSlideComponent
                key={`${data.id}_first_slide`}/>,
            ...data.mediaIds.map((mId) => <MediaSlide key={`${mId}_media`} />),
            ...(addThisComponent
                ? [
                      <SecondSlideComponent
                          key={`${data.id}_second_slide`} />,
                  ]
                : []),
        ];
    }
    
   }
```

Here's what it looks like when I use the hook and pass to Carousel
```

export const MyComponent = ({data}:{data: DataType}) => {

const slides = useGetSlides(data);

const childrenToRender: ReactChild[] = (children && Array.isArray(children) ? children : [children]).filter(
            (c) => c,
        ) as unknown as ReactChild[];
        return (
                <Carousel>
                    {childrenToRender}
                </Carousel>
        );
        
       }
```

Hope that helps!

**Comment by leandrowd** [comment]
There is a misconception that the carousel should deal with null values. I strongly advise against anything that expects that. It a lot easier for the dev to filter out null values before inputing them. The carousel will provide the index of clicked items in callbacks and if the carousel was to remove null items, the index would be different from the input. The same goes for thumbs, indicators and other capabilities.
