### ISSUE TITLE
When I turn off autoplay, slide for 3 seconds and automatically slide again

### ISSUE THREAD

**Issue by huang-guanhua** [leandrowd/react-responsive-carousel#590]
<Carousel
            autoPlay={false}
            showStatus={false}
            showIndicators={false}
            showThumbs={false}
            showArrows={false}
            infiniteLoop={false}
            swipeScrollTolerance={50}
            onChange={this.updateCurrentSlide}
            selectedItem={currentSlide}
          >

**Comment by huang-guanhua** [comment]
react-responsive-carousel": "^3.2.18",

**Comment by frankjwu** [comment]
Assume you found this already, but I was having the same issue and turns out this is broken as of 3.2.12. See #562
