### ISSUE TITLE
autoPlay false not working on mobile device

### ISSUE THREAD

**Issue by kishor82** [leandrowd/react-responsive-carousel#595]
i have set autoPlay props to false , it's only working on desktop.
version : "^3.2.18"

**Comment by SUCHiDEV** [comment]
Confirmed

**Comment by Malikx-Alee** [comment]
Is their any updated related to this issue?

**Comment by Finesse** [comment]
It's false by default. Use `interval={1e11}` to stop unwanted automatic slide changes.
