### ISSUE TITLE
autoplay happens when swiping carousel

### ISSUE THREAD

**Issue by IndraSubagja** [leandrowd/react-responsive-carousel#596]
When I set autoplay to false and swipe it, I noticed that the carousel swipe automatically once based on interval's time.
Version: 3.2.18

**Comment by SUCHiDEV** [comment]
Confirmed

**Comment by bryan-hunter** [comment]
the odds of me looking into this 5 hrs after your fix.. thanks for saving me a lot of time! :)

**Comment by ryoboua** [comment]
Any ETA on when this fix will be merged in?

**Comment by Paxatax** [comment]
Confirmed. It's quite an annoying bug. I'd hugely appreciate a quick fix on this!

**Comment by ramonmostert** [comment]
I just downgraded to @3.2.10 which doesn't have this bug, hope it's any help for the time being.

**Comment by flikQ** [comment]
> I just downgraded to @3.2.10 which doesn't have this bug, hope it's any help for the time being.

Issue still happens for me on 3.2.10.

Any idea when this will be merged @leandrowd ?

**Comment by leandrowd** [comment]
Sorry guys, I will only be able to look into anything related to this repo in 2 weeks.

**Comment by flikQ** [comment]
> Sorry guys, I will only be able to look into anything related to this repo in 2 weeks.

Can you give someone else ability to accept PRs please?

**Comment by Finesse** [comment]
Set the `interval` prop to `1e11` to circumvent the bug.

**Comment by NizNsm** [comment]
Seems there are no fixes yet, so I managed it by doing this trick, find the second-page dot selector, initiate a click when component did mount, with a setTimeout() of 3000
