### ISSUE TITLE
classNames is not in dependencies

### ISSUE THREAD

**Issue by clementdubois** [leandrowd/react-responsive-carousel#6]
The classname package is in devDependencies and therefore is present when the carousel is required and make it break

**Comment by leandrowd** [comment]
This was fixed and the version 0.1.3 was published on [npm](https://www.npmjs.com/package/react-responsive-carousel).

Thanks for letting me know ;)

**Comment by leandrowd** [comment]
This was fixed and the version 0.1.3 was published on [npm](https://www.npmjs.com/package/react-responsive-carousel).

Thanks for letting me know ;)

**Comment by leandrowd** [comment]
This was fixed and the version 0.1.3 was published on [npm](https://www.npmjs.com/package/react-responsive-carousel).

Thanks for letting me know ;)
