### ISSUE TITLE
Thumb enabled throws error in console

### ISSUE THREAD

**Issue by EmilisKakanis** [leandrowd/react-responsive-carousel#606]
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: Thumbs

**Comment by BrenniusXIV** [comment]
I am also getting this error with my development server, although once deployed to gh-pages, the carousel works as intended.
