### ISSUE TITLE
Buggy swipe with centerSlidePercentage

### ISSUE THREAD

**Issue by liroliro** [leandrowd/react-responsive-carousel#608]
When using values lower than 100, the animation seems to glitch out and jump between small and large values. 
This can be recreated at: http://react-responsive-carousel.js.org/storybook/?path=/story/01-basic--center-mode.

https://user-images.githubusercontent.com/58325628/121216655-65409600-c881-11eb-957b-e5129351e59a.mp4

**Comment by Wilson-Lim** [comment]
Hi any fix on this ?

**Comment by liroliro** [comment]
> Hi any fix on this ?

I haven't found a solution, and is still waiting for a reply from the dev team.

**Comment by NellyHaglund** [comment]
Any update on this one?
