### ISSUE TITLE
Swiping left doesnt work.

### ISSUE THREAD

**Issue by TheBeautyPeanuts** [leandrowd/react-responsive-carousel#609]
i've updated this package to 3.2.18 since the autoplay had a bug and got fixed. but seems like there's a new bug about the swiping to left.

my config on my carousel is the following =>

    const getCarouselConfigProps = () => ({
      showArrows: false,
      showStatus: false,
      showIndicators: false,
      showThumbs: false,
      useKeyboardArrows: false,
      autoPlay: false,
      stopOnHover: false,
      swipeable: true,
      dynamicHeight: true,
      emulateTouch: true,
      autoFocus: false,
      selectedItem: 0,
      interval: 0,
      transitionTime: 500,
      swipeScrollTolerance: 0,
      centerMode: true,
      infiniteLoop: false,
      centerSlidePercentage: 100,
    });
    export default getCarouselConfigProps;

My carousel components receive it like this =>

    <Carousel {...getArticleCarouselConfigProps}>
      {item}
    </Carousel>

So when i load my page, everything is fine but whenever i try to swipe to go to the previous slide. it just bump to the next slide instead of the previous one.

Anyone could help me out on this problem pls ?

**Comment by Finesse** [comment]
Your `interval: 0` setting makes the slider switch to the next slide immediately after you switch a slide even though `autoFocus: false`. This is a bug.

Set `interval: 1e11` to circumvent the bug.
