### ISSUE TITLE
This JSX tag's 'children' prop expects type 'ReactChild[] & ReactNode' which requires multiple children, but only a single child was provided.ts(2745)

### ISSUE THREAD

**Issue by WalleksMR** [leandrowd/react-responsive-carousel#610]
<h4 align="center">
  ...which requires multiple children, but only a single child was provided
</h4>

Hi dier, 

Did I into a problem when adding just one element to the slide.
<img alt="Podcastr" src="https://i.imgur.com/kYl7w9e.png" width="800" />

<h4 align="center">
  Describe the possible solution
</h4>

The solution I finded is adding was 
```ts
 children?: React.ReactChild | React.ReactChild[];
```
in the types of Carousel.d.ts interface Props.

<img alt="Podcastr" src="https://i.imgur.com/pVSY3hl.png" width="800" />

**Comment by dekguh** [comment]
i think you must add two child element like this
<Carousel>
    <div>child 1</div>
    <div>child 2</div>
</Carousel>

**Comment by WalleksMR** [comment]
Thanks very much @sauravhiremath, did works :D
