### ISSUE TITLE
Swiping on mobile causes blinking and is not moving smoothly

### ISSUE THREAD

**Issue by tommy92** [leandrowd/react-responsive-carousel#613]
While swiping on iOS Chrome(v91.0.4472.80) images are blinking. Moreover, when slide changes it does not seem to move smoothly.
It does not occur on Safari for example.

Below you can see how it looks on yours Storybook with base example.

https://user-images.githubusercontent.com/2852907/122538349-be00f300-d026-11eb-9095-4d88d5e38e90.MP4

**Comment by kelun-zhang** [comment]
Same issue here.
