### ISSUE TITLE
Everything works except there is no slide animation.. The next slide just instantly appears.

### ISSUE THREAD

**Issue by RickRyan26** [leandrowd/react-responsive-carousel#614]
Even when I copy the demo code exactly from codesandbox and paste it in my Nextjs application, there is no animation between slides. The next slide just instantly appears and replaces the last one. Is there anything know that would cause this?? Thank you!!

**Comment by Finesse** [comment]
Check the CSS code of the `ul.slider` element. It uses CSS transition to animate the slide switches. Probably, your website CSS code overwrites the transition.
