### ISSUE TITLE
Mapping over Images from Sanity CMS

### ISSUE THREAD

**Issue by jflores353** [leandrowd/react-responsive-carousel#616]
I am experiencing an issue with autoPlay not starting with my images connected through Sanity CMS. I included the prop autoPlay and have also tried setting autoPlay={true} without any luck. When I click on the arrows to show the next image then autoPlay takes over as usual. Just can't get it to start on its own. Any suggestions? Much thanks for carousel

**Comment by BrunoTCouto** [comment]
Having the same issue
