### ISSUE TITLE
Additional render props?

### ISSUE THREAD

**Issue by Frexuz** [leandrowd/react-responsive-carousel#618]
`renderArrowPrev` and `renderArrowNext`, only render the carousel's arrows. Is there any plans to enable props for these in for the arrows in the thumbnail row?

The same goes for the status. The `statusFormatter` is not enough.

We prefer not to write css, as we already have react components for everything.

**Comment by leandrowd** [comment]
This is not actively developed anymore so no plans to implement it but contributions are welcome. Feel free to propose the changes in a pull request.
