### ISSUE TITLE
When we keep thumb or finger on touch device it should pause auto scroll.

### ISSUE THREAD

**Issue by pankaj-onerent** [leandrowd/react-responsive-carousel#63]
1. When we keep thumb or finger on touch device it should pause auto scroll.
2. It should also reset the time for auto move to next when user manually change the slide.
3. When we  scroll the page vertically even though it move to the next slide.
4. When we use up and down keys even though it changes the slide.

**Comment by leandrowd** [comment]
Sounds good. PRs welcome

**Comment by leandrowd** [comment]
Hi @pankaj-onerent, the latest version introduced the features you requested. Please check it out!

Cheers!
