### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by CirilloKonstantini** [leandrowd/react-responsive-carousel#634]
TS2607: JSX element class does not support attributes because it does not have a 'props' property.
TS2786: 'Carousel' cannot be used as a JSX component.   Its instance type 'Carousel' is not a valid JSX element.     Type 'Carousel' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

**Comment by mckinnsb** [comment]
Also seeing this error when I switched to PNP on Yarn 2

**Comment by mckinnsb** [comment]
Yeah; I just did a cursory review of the `index.d.ts` file produced for Carousel, and it's not just missing elements from `ElementClass`, it's also missing definitions for a lot of the public interface; examples include `showArrows/showThumbs/showStatus`

**Comment by mckinnsb** [comment]
(This is on 3.2.20)

**Comment by mckinnsb** [comment]
These are present on `CarouselProps` but for some reason are not being evaluated correctly

**Comment by Kirill20123** [comment]
I think there is a mistake in export interface or type in index.d.ts. I disabled the error by importing from carousel/js sorry i'm writing from phone

**Comment by mckinnsb** [comment]
```
JSX element class does not support attributes because it does not have a 'props' property.
```
I'm guessing it has something to do with this?

**Comment by mckinnsb** [comment]
@Kirill20123 not sure if I understood you; what was the workaround here?

**Comment by FIlS-5** [comment]
I have been experiencing this same issue and still have no resolution on it yet. Please HELP!!

**Comment by FIlS-5** [comment]
> ```
> JSX element class does not support attributes because it does not have a 'props' property.
> ```
> 
> I'm guessing it has something to do with this?

Having the same issue; have you been able to rectify this?

**Comment by Kirill20123** [comment]
@FIlS-5 no i haven't

**Comment by Kirill20123** [comment]
@mckinnsb i dont have the right workaround, you can disable typescript error with importing carousel like this
`import { Carousel } from 'react-responsive-carousel/lib/js'`

but you won't be able to get typescript help

**Comment by bosteelsd** [comment]
Having the same issue on my project, a fix coming ?

**Comment by Kirill20123** [comment]
> Having the same issue on my project, a fix coming ? 

import { Carousel } from 'react-responsive-carousel/lib/js'

Try this import

**Comment by shennan** [comment]
This seems to happen for me when I'm in a Yarn workspace and add a `"nohoist"` field to the root workspace `package.json`. 

This could just be my specific case but I get the error when I added React and ReactDOM as a "nohoist" package:

```
...
"workspaces": {
  "packages": [
    "some-folder",
    "some-other-folder"
  ],
  "nohoist": [
    "**/react",
    "**/react/**",
    "**/react-dom",
    "**/react-dom/**"
  ]
}
...
```
