### ISSUE TITLE
Is Possible Placing Custom Component Between Thumbs and Image Sliders

### ISSUE THREAD

**Issue by nandayonah** [leandrowd/react-responsive-carousel#638]
I try to use `renderThumbs` but it looks not what I wanted to be, how could I place my component between thumbs and image slider, below is the image that I want to achieve.

![Screenshot 2021-08-19 172454](https://user-images.githubusercontent.com/44917664/130053185-5fd92f9d-da54-448b-8de6-515c8123502c.png)

```javascript
<Carousel
  showArrows={true}
  showThumbs={true}
  autoPlay={true}
  infiniteLoop={true}
  interval={5000}
  showStatus={false}
  transitionTime={1000}
  swipeable={true}
  thumbWidth={50}>
  {productDetail.data &&
    imageProduct.map((data, idx: number) => {
      return (
        <div key={idx}>
          <img className="d-block w-100" src={data.file} alt={data.media_type} />
        </div>
      );
    })}
</Carousel>
<CustomBadgeProductDetailView
  label={productDetail?.data?.custom_badge}
  startDate={productDetail?.data?.custom_badge_from_date}
  endDate={productDetail?.data?.custom_badge_to_date}
/>
```

**Comment by zarkovvv** [comment]
A workaround is executing a script:

`const dots = document.getElementsByClassName('control-dots')[0]; //carousel-status
    const status = document.getElementsByClassName('carousel-status')[0];
    const parent = dots.parentNode;
    parent.insertBefore(dots, status);`

and a custom css for dots:

`.control-dots {
  position: relative !important;
}`
