### ISSUE TITLE
Slides not clickable with fade animation

### ISSUE THREAD

**Issue by metawort** [leandrowd/react-responsive-carousel#639]
**Describe the bug**
When I use `animationHandler="fade"`, the slides (and all of their child elements) can not be clicked.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-responsive-carousel-forked-lswy0
2. Try to click on the link in the slide's legend
3. See that you can't click it

**Expected behavior**
The slide and it's children should be interactive and the currently selected slide should be on top.

**Example**
https://codesandbox.io/s/react-responsive-carousel-forked-lswy0

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5.2
 - Browser: Chrome
 - Version: 92.0.4515.159

**Additional context**
To make the fading transition work, I had to use the workaround described here: https://github.com/leandrowd/react-responsive-carousel/issues/593#issuecomment-878349792

**Comment by rodsouto** [comment]
an easy fix to put the selected slide on top:

```css
.carousel.carousel-slider li.slide.selected {
    z-index: 0 !important;
}
```
