### ISSUE TITLE
Compatibilty with Next JS

### ISSUE THREAD

**Issue by akarX23** [leandrowd/react-responsive-carousel#646]
Thumbs are not visible when using the component with Next JS. I think it may be due to SSR. Please help me out here. I have used this library peacefully in other React projects. I am also using Material UI and Tailwind in this project.

**Comment by arwaali96** [comment]
It works for me when using Next.js only when the source (src) for the image is a link.

**Comment by ghpranav** [comment]
If possible please add support for the custom [Image](https://nextjs.org/docs/api-reference/next/image) component of NextJS as well for generating thumbs

**Comment by rilrom** [comment]
@ghpranav Its possible to use the NextJS image component by utilising the renderThumbs prop.

```
function renderThumbs(children) {
    return children.map((item, index) => {
      return (
        <Image
          className={classes.image}
          objectFit="cover"
          src={item.props.children.props.src}
          width={144}
          height={144}
          key={item.props.children.key}
        />
      );
    });
  }
  ```
  
  You've just got to check where the image source is located in the function parameter.

**Comment by dulquerirfan** [comment]
I have used in next js. It is working properly on local host when i deploy to vercel it is not working properly
