### ISSUE TITLE
Two images showing in a single view

### ISSUE THREAD

**Issue by tdammy92** [leandrowd/react-responsive-carousel#652]
Have used this package severally, had no issues with it, but i used it on a project am working on and noticed two images are showing in a single slide. please i need help with it..

i thought it was my styling, but commented all out and still d same. am not reporting a bug, just need and extra pair of eyes. thank you.

![image](https://user-images.githubusercontent.com/51160790/134816966-a9728e20-fceb-48c7-8757-84f8423b7729.png)

code >>

function DesktopSlider() {
	return (
		<div className='slider__content'>
			<Carousel
				infiniteLoop={true}
				autoPlay={true}
				showIndicators={true}
				showThumbs={false}
				width='100%'
		
				
			>
				<div className='slideImage__item'>
					<img src={Image1} className='slideImage' alt='slide' />
					<p >
						Analysing Youth Restiveness, Electoral violence and security
						challenges
					</p>
				</div>
				<div className='slideImage__item'>
					<img src={Image3} className='slideImage' alt='slide' />
					<p>
						Shaping the mindset and developing the atitudes tolerance in the
						next generation
					</p>
				</div>
				<div className='slideImage__item'>
					<img src={Image4} className='slideImage' alt='slide' />
					<p>Advancing Women and youth in peace building</p>
				</div>
				
			</Carousel>
		</div>
	);
}

**Comment by rilrom** [comment]
Could you please provide the all the custom styles you are using. You mention no change after commenting them out but would be a good idea to double check.
