### ISSUE TITLE
Vertical scroll of page is disabled when I touch inside carousel

### ISSUE THREAD

**Issue by ktjd123** [leandrowd/react-responsive-carousel#662]
**DISCLAIMER** 
This repo is not actively maintained by the owner. It depends mostly on contributions. Feel free to fork or to raise a PR and we will review when possible.

**Describe the bug**
Vertical scroll of page is disabled when I touch inside carousel.

When you try to scroll page vertically, with touch inside carousel, It disables vertical scroll

**To Reproduce**
1. Mobile page(vertical) with multiple carousel (horizontal)

**Expected behavior**
Vertical scroll for page should work.

**Smartphone (please complete the following information):**
Iphone 13 pro
15.0.2

**Additional context**
Always appreciate your works.

**Comment by alexitelman** [comment]
I'm having the same issue, did you figure out how to fix it?

**Comment by skoskipaa** [comment]
I ran into the same issue after updating to 3.2.22 but got it fixed by setting `preventMovementUntilSwipeScrollTolerance={true}`.

**Comment by alexitelman** [comment]
Thanks, this works for me too, plus setting the swipeScrollTolerance to 30, so that it doesn't swipe while scrolling.
