### ISSUE TITLE
Unable to make iframe fill Carousel Width

### ISSUE THREAD

**Issue by stephen-ip** [leandrowd/react-responsive-carousel#663]
I am trying to make an iframe Carousel, but each iframe element I put into the carousel div does not fill the carousel's width. I tried putting an img into the div instead of an iframe and the img automatically fills the entire width, but with the iframe, it just gets squished. I have tried setting the div's width to max-content, but then part of the iframe is then pushed into the next carousel's view, and it is not centered. I also tried manually shifting the left margin back so it would not interfere with the next carousel iframe's view but then part of the iframe is not interactive. Is there a quick and clean way to just simply make the iframe fill the remaining red space in its view? I have attached pics of my problem and code below. Any help would be greatly appreciated. Thanks
![c1620374376e7765d6fad6fd54bf152c](https://user-images.githubusercontent.com/91226924/146858636-cefdd8e8-e9e5-4b58-94c5-f8a71dfb8a4e.png)
![811b327f26f67d2872fc4d0f09b2acf9](https://user-images.githubusercontent.com/91226924/146858640-1f99386a-325b-4934-bdb7-86b896f74175.png)
![79438e8924a0a4435ea5f4d9611f4745](https://user-images.githubusercontent.com/91226924/146858641-5f806848-4a30-4246-bd69-0ce73d296f9f.png)

**Comment by Guribeiro** [comment]
I achieved this just styling the iframe wrapper (in our case the `<div>` tag) with **width: 100%**
like this:
Try setting the styles on Iframe style, width and height props as well

```tsx
return (
  <div
    style={{
      height: '100vh',
      width: '100%',
    }}
  >
    <iframe
      width="100%"
      height="100%"
      style={{
        width: '100%',
        height: '100%',
        margin: '0 auto',
      }}
      src={mediaUrl}
      title={descricao}
      frameBorder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowFullScreen
    />
  </div>
);
```
