### ISSUE TITLE
transitionTime seems to be broken

### ISSUE THREAD

**Issue by Pagnito** [leandrowd/react-responsive-carousel#667]
Hi, I have the carousel running and everything works, except the transition time doesn't. When I specify transitionTime, it breaks the animation and just changes from slide to slide instantly.
```
    <Carousel
      autoPlay
      renderIndicator={couraselIndicator}
      showStatus={false}
      swipeable={true}
      showThumbs={false}
      animationHandler={'fade'}
      infiniteLoop={true}
      transitionTime={2}
    >
      {slides()}
    </Carousel>
```

**Comment by a526735a** [comment]
if you want 2 seconds as transition time, you have to use transitionTime={2000} since it is in milli-second unit

**Comment by ice1080** [comment]
As a note @toey-sup , the docs don't specify the unit. Not too difficult to test and figure it out, just mentioning. 
https://github.com/leandrowd/react-responsive-carousel
