### ISSUE TITLE
Accessibility bug with interactive nested children

### ISSUE THREAD

**Issue by tnadolski-ellucian** [leandrowd/react-responsive-carousel#680]
When a node is passed into Carousel, that has interactive children, you can tab through those children without advancing the slide.
This gets you into a state where two slides are shown at once. You can see this from the storybook youtube example, if you tab through the elements in the video, you'll advance partially to the next slide

Picture for the behavior:
![Screen Shot 2022-02-23 at 6 47 48 AM](https://user-images.githubusercontent.com/58561705/155314091-f288c0c8-4495-41a3-a6e7-34de10691941.png)

**Comment by tnadolski-ellucian** [comment]
If anyone has a solid work around, let me know!
I was playing a bit with the inert polyfill, but it doesn't seem consistent.
It's also not as simple as just adding tabIndex -1 to non-active slides, because some children (such as buttons) will retain their tab focus.

**Comment by tharinducs7** [comment]
Still the issue is there

**Comment by halain** [comment]
My workaround was to create a custom focus trap for slides and set tabindex= -1 to all taggables elements in not active slide and tabindex=0 to the active slide
