### ISSUE TITLE
Library seems to be broken

### ISSUE THREAD

**Issue by jacopo-degattis** [leandrowd/react-responsive-carousel#683]
I just downloaded the library and when I try to implement the component it seems like the carousel doesn't load CSS styles.

To reproduce:
1. Install the library with yarn
2. Try adding the component with images
3. See that CSS doesn't get loaded

Expected behaviour
The library should correctly show the slider

Screenshots
![Screenshot 2022-03-17 at 12 47 49](https://user-images.githubusercontent.com/86744469/158802286-11ae40f1-fb48-4c9d-875a-7a126de1362e.png)

**Comment by etse** [comment]
I did just download it myself, and everything works as expected. Are you sure your environment is setup correctly with a loader that loads the CSS? Using webpack and a css-loader I add `import "react-responsive-carousel/lib/styles/carousel.min.css";` to the top of my file and everything works as expected.
