### ISSUE TITLE
Slider should not depend on main.css

### ISSUE THREAD

**Issue by pke** [leandrowd/react-responsive-carousel#69]
It seems some styles are set in `main.css` instead of `carousel.css`. `main.css` resets margins and paddings for *all* elements and sets up header sizes and more. That's breaking changes for most apps.
Instead all styles relevant to the slider should be set in `carousel.css`. Especially styles for the sliders `ul` element.

**Comment by leandrowd** [comment]
Feel free to submit a PR.

**Comment by leandrowd** [comment]
Hi @pke, the latest version published to npm includes a fix for this problem. Please update and let me know how it goes.

**Comment by pke** [comment]
@leandrowd Thanks for the fix. Works.
