### ISSUE TITLE
[Feature Request] Infinite Loop Animation

### ISSUE THREAD

**Issue by TannerJuby1** [leandrowd/react-responsive-carousel#699]
I would like to suggest enhancing the `Infinite Loop` option to animate like an infinite loop instead of a reset.

It would be nice if this carousel continued to loop in the same direction like an actual infinite loop instead of just "resetting" by just reversing the animation backwards quickly

**Comment by ghost** [comment]
Facing same issue.

**Comment by realkth** [comment]
Using v3.2.21 will solve this issue.

**Comment by benthejack-vuw** [comment]
@realkth I've tried 3.2.21 and also the latest 3.2.23, neither seem to have an animation that continues in the same direction when it loops, rather there is a reset that scrolls through the entire list.

**Comment by sakshambhatt** [comment]
I am using v3.2.23, and yet the animation is resetting instead of beginning a new loop. Could you please tell if there is some other prop that needs to be passed along with infiniteLoop?
 @realkth

**Comment by justinledelson** [comment]
Thanks @realkth for the tip, that's working for now.

Would love an extra prop to control this behavior.

**Comment by EwanLyon** [comment]
Downgrading from v3.2.23 to v3.2.21 worked but this is some sort of regression in v3.2.22 since the resetting behaviour is in that as well.
