### ISSUE TITLE
classnames module missing from dependencies

### ISSUE THREAD

**Issue by edoloughlin** [leandrowd/react-responsive-carousel#7]
I get 

```
ERROR in ./~/react-responsive-carousel/cssClasses.js
Module not found: Error: Cannot resolve module 'classnames' in /Users/me/workspace/my-app/node_modules/react-responsive-carousel
 @ ./~/react-responsive-carousel/cssClasses.js 1:17-38
Warning: Task "webpack:development" failed. Use --force to continue.
```

I'm using react 0.3.13. If I do

```
npm install classnames --save
```

it fixes the problem.

**Comment by leandrowd** [comment]
This was fixed and the version 0.1.3 was published on [npm](https://www.npmjs.com/package/react-responsive-carousel).

Thanks for letting me know ;)

**Comment by leandrowd** [comment]
This was fixed and the version 0.1.3 was published on [npm](https://www.npmjs.com/package/react-responsive-carousel).

Thanks for letting me know ;)

**Comment by nisaar** [comment]
gf

**Comment by realtebo** [comment]
I am here becase on my very first run with react-formic I faced same error, classnames not defined, because it's not included in the deps

I see  in the page https://www.npmjs.com/package/react-formic . in the dependency tab there is no mention of classnames
