### ISSUE TITLE
Different sized slides

### ISSUE THREAD

**Issue by pke** [leandrowd/react-responsive-carousel#70]
I have one image in my slides that is wider then the rest of the images. This throws off the carousel as it seems to calculate the width of the carousel based on the max width of all items.

Whats the recommended way to instruct my `div` items be all the same size, namely the size of the carousel container?

**Comment by leandrowd** [comment]
If you set your div to be `max-width: 100%` it should work as it will be constrained by the `.slide`. Check the examples on http://react-responsive-carousel.js.org/storybook/ to see if it helps.

**Comment by leandrowd** [comment]
Hey @pke, I finally got some time to fix this issue. it's fixed and published to [npm](https://www.npmjs.com/package/react-responsive-carousel) (v.3.0.22).

Please update to the latest version and let me know if it solved your problem.

Feel free to reopen if you still have issues.

**Comment by pke** [comment]
Thanks, I'll try it next week
