### ISSUE TITLE
Initially displaying wrong item with version 3.2.22 and higher

### ISSUE THREAD

**Issue by MatusJurcak** [leandrowd/react-responsive-carousel#701]
**Describe the bug**
I have an array of pictures and when my page loads i dont see the first picture as i should, but i see the last one from the array. What is even more strange is that with autoplay on, when it moves to the next picture it shows the second one from array. When i move to another it works alright, the problem is just the initial item that is displayed and all of this happens to me only with version 3.2.22 and higher.

**Expected behavior**
I expected it to be behaving as in version 3.2.21 when the initial item being displayed is the first one from the array.

**Comment by ethanhoroschak** [comment]
this is happening to me as well - can we reopen this?
