### ISSUE TITLE
Disable ability to tab into content within a slide

### ISSUE THREAD

**Issue by JayBox325** [leandrowd/react-responsive-carousel#702]
**Describe the bug**
When tabbing through my website, I am finding that I can tab into content that is inside slides that aren't visible. Meaning that I get a weird half and half view when I've tabbed into the button on the next slide.

**To Reproduce**
1. Go to a page with a slider that has buttons within each slide.
2. Try to navigate the page with tabbing only.
4. Notice how the display looks wrong.

**Expected behavior**
Should only be able to tab into content that is currently visible then use the keyboard nav or the visible pagination to change the slides.

**Screenshots**
Had to cover a lot of the elements in the image due to NDA, but please note the blue border being around the 'slide selected' element and the red border around the not currently selected slide.

See how the browser has tried to tab into the next slide's button. (although the focus disappeared in the screenshot)
![Screenshot 2022-09-30 at 18 40 39](https://user-images.githubusercontent.com/13233809/193326808-66b80ea6-3009-4841-b0d1-f0138a191a3b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stalgiag** [comment]
This problem can also be seen in this [official example with Youtube videos](https://react-responsive-carousel.js.org/storybook/iframe.html?id=02-advanced--youtube-autoplay-with-custom-thumbs). As you continue tabbing you end up controlling videos that aren't in the currently 'selected' slide, causing them to shift over and breaking the interaction. This makes the component inaccessible to keyboard users.

**Comment by JayBox325** [comment]
This is still happening and should not be closed.

**Comment by JayBox325** [comment]
Poor. This should not be stale. Bump!
