### ISSUE TITLE
Last image in the carousel appears first when infinite loop is enabled

### ISSUE THREAD

**Issue by clicktodev** [leandrowd/react-responsive-carousel#705]
**DISCLAIMER** 
This repo is not actively maintained by the owner. It depends mostly on contributions. Feel free to fork or to raise a PR and we will review when possible.

**Describe the bug**
Setting infinite loop to true will cause the last image to be displayed first.

**To Reproduce**
1. set infiniteLoop prop to true

**Comment by cosmin-negoita** [comment]
I confirm this. Hopefully someone will fix!

**Comment by wiesys** [comment]
The same here.

**Comment by John-Oula** [comment]
Confirmed!

**Comment by bicky-tmg** [comment]
Setting the value of prop `selectedItem={-1}` worked for me. 🤷

**Comment by Ablionsibsankar** [comment]
Setting the value of prop selectedItem={0} is fine
