### ISSUE TITLE
With multiple items, carousel does not slide until index is changed to 2

### ISSUE THREAD

**Issue by Zainzzkk** [leandrowd/react-responsive-carousel#708]
**Describe the bug**
When using multiple items on the carousel using centerMode and centerSlidePercentage, when index is 1, it does not swipe to the next one until index is on 2 or higher, meaning the first click of the right arrow does nothing.

**To Reproduce**
1) Click on the next arrow
2) Carousel will not move one
3) Click again and carousel will shift

**Expected behavior**
The carousel should move one when pressing the right arrow

**Comment by Inchill** [comment]
I met the same problem.
