### ISSUE TITLE
Increase speed of slides

### ISSUE THREAD

**Issue by pke** [leandrowd/react-responsive-carousel#71]
Which style needs to be modified to make the transition between slides faster?

**Comment by leandrowd** [comment]
you can change this line: https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/_carousel.scss#L174

If you spend the time to make it dynamic, please submit a pull request :)

**Comment by leandrowd** [comment]
Hi @pke, I've introduced a new prop "transitionTime" which allows custom durations. Hopefully it fits your requirements. ;)

Please download the latest version from npm and let me know how it goes.  https://www.npmjs.com/package/react-responsive-carousel 

Smaller numbers will make faster transitions. Defaults to 350ms.

Cheers.
