### ISSUE TITLE
How to show captions under images?

### ISSUE THREAD

**Issue by SaadBazaz** [leandrowd/react-responsive-carousel#713]
**Describe the bug**
I want to show captions for each image, **underneath** the image.

**Screenshots**
Something like this:

<img width="418" alt="Screenshot 2022-12-03 at 1 48 35 PM" src="https://user-images.githubusercontent.com/51885228/205432710-212e9dce-b3d6-4f7b-9f10-5ef7567bc7fb.png">

I'm currently doing it by rendering captions in "renderIndicators", but it cuts off the bottom.

**Comment by icon2341** [comment]
I think you can just put a text tag underneath the img tag and put the two in a vertical flexbox
