### ISSUE TITLE
Not able to scroll vertically in mobile on thumbs

### ISSUE THREAD

**Issue by HiteshDatt** [leandrowd/react-responsive-carousel#717]
I was able to solve the issue by setting preventMovementUntilSwipeScrollTolerance={true} and swipeScrollTolerance={50}

_Originally posted by @lambdadev007 in https://github.com/leandrowd/react-responsive-carousel/issues/469#issuecomment-1148934349_

**Comment by HiteshDatt** [comment]
vertical swipe was fixed on the carousel element using the above-said properties, but the same behavior is seen on the thumbnails as well, any fix for that?

**Comment by rjomir** [comment]
same problem

**Comment by HiteshDatt** [comment]
Fixed in the following PR [https://github.com/leandrowd/react-responsive-carousel/pull/736](https://github.com/leandrowd/react-responsive-carousel/pull/736)

@leandrowd Please review, this fix works for me
