### ISSUE TITLE
autoPlay option does not update after re-render

### ISSUE THREAD

**Issue by jeffreznik** [leandrowd/react-responsive-carousel#72]
In my app, I have a Google map with clickable markers representing properties.  When a marker is clicked, the Carousel is updated with new images and props.  The autoPlay prop is true if there are 2 or more images, and false if there is only 1 image.

Reproduction steps:
1. Click on marker for property with 2+ images
2. Click on marker for property with 1 image

Expected result:
After step 1, Carousel autoplays.  After step 2, Carousel stays on the one and only image.

Actual:
After step 1, Carousel autoplays.  After step 2, Carousel continues to autoPlay past the first image into oblivion.

Note:
There are actually 2 bugs here:
1. As described above, autoPlay option should update on re-render to respect the new true/false value (it fails both ways)
2. autoPlay on a Carousel with a single image should not autoPlay at all.  Right now it will continue to autoPlay to infinity.

Code (my Carousel component which wraps react-responsive-carousel):

```jsx
import React from 'react'
import RRCarousel from 'react-responsive-carousel'

const Carousel = ({ images, axis='horizontal', showThumbs=true, showArrows=true, showStatus=true, autoPlay=true }) => {
  // TODO: add legend support, images should be array of objects... see react-responsive-carousel documentation
  let elements = <div key="none"><img src="/images/no-photo-available.gif" alt=""/></div>
  let infiniteLoop = false
  let showIndicators = false
  if (images.length) {
    elements = images.map((image, index) => <div key={index}><img src={image} alt=""/></div>)
    infiniteLoop = images.length > 1
    showIndicators = images.length > 1
  } else {
    autoPlay = false
  }
  console.log('infiniteLoop', infiniteLoop)
  console.log('autoPlay', autoPlay)
  return (
    <div className="carousel">
      <RRCarousel.Carousel
      axis={axis}
      showThumbs={showThumbs}
      showArrows={showArrows}
      showStatus={showStatus}
      showIndicators={showIndicators}
      autoPlay={autoPlay}
      infiniteLoop={infiniteLoop}
      >
        {elements}
      </RRCarousel.Carousel>
    </div>
  )
}

export default Carousel

```

The console.log statements accurately report the desired infiniteLoop/autoPlay values, but Carousel does not respect them.

**Comment by jeffreznik** [comment]
Found a workaround to this... if I put the default "no photo available" image tag into an array:

```jsx
let elements = [<div key="none"><img src="/images/no-photo-available.gif" alt=""/></div>]
```

Then it seems to detect the correct number of elements and stop autoPlaying.

**Comment by leandrowd** [comment]
Currently, autoplay is only configured on `componentDidMount`. The solution would be to call `setupAutoPlay` again if it changes (in `componentWillReceiveProps` or `componentDidUpdate` and `destroyAutoPlay` when required. If you can, you are more than welcome to submit a pull request. I can review and release but I don't really have time to fix it right now...

**Comment by leandrowd** [comment]
Hi @jeffreznik, I finally got some spare time and fixed this issue. It was published to [npm](https://www.npmjs.com/package/react-responsive-carousel) (v3.0.22).

Please update and let me know how it goes. 

Thanks.
