### ISSUE TITLE
Error: type should not be null (Using map function)

### ISSUE THREAD

**Issue by akuji1993** [leandrowd/react-responsive-carousel#73]
When I insert the package into my project and try to call it like this: 

```
import Carousel from 'react-responsive-carousel';
...
return (
<Carousel> 
     {galleryImages.map((imgUrl, i) =>
        <div>
              <img src={imgUrl}/>
        </div>
      )}
</Carousel>
);  
```

I get the following error: React.createElement: type should not be null, undefined, boolean, or number. The object is there, it just doesn't work. Any idea how to fix?

**Comment by akuji1993** [comment]
Alrighty, for everyone else having this error, apparently you HAVE to do 
`
import {Carousel} from 'react-responsive-carousel'; `

Sadly, this is followed by this error: TypeError: item.props.children.filter is not a function

**Comment by akuji1993** [comment]
Just FYI: Could be that this issue is created by something similar to this: https://github.com/FormidableLabs/nuka-carousel/issues/172

**Comment by leandrowd** [comment]
Closing as it was only a wrong import.

**Comment by plonko** [comment]
FYI I'm getting a similar issue now..
"TypeError: Cannot read property 'type' of null at"

This traces back to Thumbs.js.
https://github.com/leandrowd/react-responsive-carousel/blob/master/src/components/Thumbs.js#L112

It refuses to see <img /> as a type

My code: 
```
                <Carousel infiniteLoop showIndicators={false} showStatus={false} >
                    {(data.product.previews) && data.product.previews.map((preview, idx) => (
                        (preview.type === 'file' && idx == 2) ? (
                            <img src='http://www.pepitastore.com/public/assets/1614900/sample/2cab9e6a2028e96fcef90c44ec66f7c7.jpg' />
                        )
                        :
                        (false)
                    ))}
                </Carousel>
```

driving me bananas. 🍌

**Comment by akuji1993** [comment]
Have you tried putting braces around your arrow function in map and debugged what actually is in the preview object? Are you sure you provide it with the correct values? Also I'm not sure about using the ? operator here and providing a false in the case it's not what you think it is. I'd try to find a better way around this.

**Comment by plonko** [comment]
@akuji1993 Ok thanks. I cleaned up my test case and yeah false isn't what I want. It seems you can't return any falsey value in that loop without react-responsive-carousel blowing up though, I'm not sure that's right. You should be able to drop stuff that you don't want within the loop. 

Thanks for the input! :)

**Comment by akuji1993** [comment]
I agree that it should have a fallback behaviour, but I can also understand not supporting this in the way that you expected it would. Happy to hear that you found the issue though!
