### ISSUE TITLE
Thumb Images Can't Be Shown?

### ISSUE THREAD

**Issue by JimLynchCodes** [leandrowd/react-responsive-carousel#732]
I think there is a problem with how these thumb images work.

Certain times we need to wrap images in divs in order for css to work properly.

For example:
```jsx
<div className="sm:hidden">
   <img src={imgPathS} />
</div>

<div className="hidden sm:inline-flex">
   <img src={imgPathM} />
</div>
```

This code will not properly render the thumbs.

If I add the styles to the images directly, both images are shown on all screen sizes.

There is no possibly way to show the thumbs and correctly show images here.

**Comment by JackHammer29** [comment]
I also have this issue if using Next Image vs just using <img> tags

**Comment by BradNut** [comment]
@JackHammer29 Were you able to figure out how to accomplish this with Next Image?
