### ISSUE TITLE
Autoscroll Mouse Down Expected Behavior?

### ISSUE THREAD

**Issue by JimLynchCodes** [leandrowd/react-responsive-carousel#733]
**Describe the bug**
I'm seeing inconsistent behavior and I'm wondering why...

**To Reproduce**

1. Create a Carousel with at least two images and "emulateTouch={true}" attribute.
2. Turn on "autoplay" 
3. Hover over Carousel with your desktop mouse. Notice how this stops the Carousel from spinning.
4. Grab the Carousel (using either desktop mouse or mobile thumb tap). Notice how the autoplay makes the Carousel slide jump out from underneath your thumb.  

**Expected behavior**
In my opinion, the autoplay movement should be prevented if the user's mouse is down, holding the slide.

**Example**
Provide enough code to reproduce the bug (fork from https://codesandbox.io/s/lp602ljjj7 and send your link)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Alreadywinner** [comment]
@leandrowd @JimLynchCodes  can I pick it solve ?
