### ISSUE TITLE
Next slide does not match with image size

### ISSUE THREAD

**Issue by akolopez** [leandrowd/react-responsive-carousel#74]
I'm using Carousel with just the basic settings, but the images get cropped when moving to the next slide. The first fits perfectly in the carousel frame. The next image has a bit of the next image spilling over on the right. Then the next image has more spilling over, etc.

This is how the code looks like.

```javascript
const Carousel = require('react-responsive-carousel').Carousel
import 'react-responsive-carousel/lib/styles/carousel.css';
import bar from './process-header.jpg'
class MyCarousel extends Component {
  render() {
    return (
      <Carousel>
        <div> <img src={ bar } /> </div>
        <div> <img src={ bar } /> </div>
        <div> <img src={ bar } /> </div>
        <div> <img src={ bar } /> </div>
      </Carousel>
    );
  }
};

export default MyCarousel;
```

**Comment by leandrowd** [comment]
Do you have a demo somewhere I can test?

**Comment by akolopez** [comment]
I created a quick [demo](https://github.com/akolopez/react-responsive-carousel-bug-demo) for you to check out.

**Comment by leandrowd** [comment]
Hey @akolopez, thanks for the demo. 

There was a problem when using a single child within a slide. I fixed and published to [npm](https://www.npmjs.com/package/react-responsive-carousel) (v.3.0.22).

Please update to the latest version and let me know if it solved your problem.

Feel free to reopen if you still have issues.
