### ISSUE TITLE
Initially displaying wrong item and skipping next item on autoplay

### ISSUE THREAD

**Issue by ethanhoroschak** [leandrowd/react-responsive-carousel#743]
**Describe the bug**
Same issue as https://github.com/leandrowd/react-responsive-carousel/issues/701 but that was closed for inactivity. 

I'm using carousel with autoplay and infiniteLoop to display an array of items. On first load the carousel displays the last item in the array instead of the first item and then skips the first item moving to the second item. After It goes through a full cycle, it behaves as expected.

**Expected behavior**
The carousel displays the first item in the list first and doesn't skip any items

**Additional context**
Full component props:
```
 <Carousel
        autoPlay
        centerMode
        infiniteLoop
        preventMovementUntilSwipeScrollTolerance
        centerSlidePercentage={100 / Math.round(width / 500)}
        emulateTouch={width < 1024}
        showArrows={false}
        showStatus={false}
        showThumbs={false}
        swipeScrollTolerance={50}
        swipeable={width < 1024}
        transitionTime={3000}
```

**Comment by R0kyzas** [comment]
Yeah, same problem. Seems bug with infiniteLoop. Any solution guys?
