### ISSUE TITLE
[Ui]: Change the banner to an icon

### ISSUE THREAD

**Issue by sumit639-code** [leandrowd/react-responsive-carousel#749]
![image](https://github.com/leandrowd/react-responsive-carousel/assets/63084040/b19f551c-a5e8-4436-bf5a-94c716a6526e)

The banner is odd to the ui it should be in the frame of icon.

**Comment by Bidhu1024** [comment]
Can @sumit639-code please explain  more about this issue how you want it so that i can work over it?
