### ISSUE TITLE
Add indicatorContainer props to ease indicator positioning

### ISSUE THREAD

**Issue by sierraleonez** [leandrowd/react-responsive-carousel#750]
Current behavior:
There are no props that override the display of the container from the indicator, only the indicator that can be overridden, and the default styling placed the indicator in the bottom center of the carousel.

![image](https://github.com/leandrowd/react-responsive-carousel/assets/72799975/c8bec6ba-9ec1-440c-a5e1-f274ca0892b0)
![image](https://github.com/leandrowd/react-responsive-carousel/assets/72799975/10e2c676-f4c7-4e41-a215-c15851653390)

Expected Behaviour:
I need to place my indicator at the end of the container, but as far as I know, there are only props to override the display of the indicator itself, but not the container.  I expect there will be a prop to customize the container of the indicator.

Expected UI:
![image](https://github.com/leandrowd/react-responsive-carousel/assets/72799975/1583eeab-2136-4ce8-a314-3a923f084086)

**Comment by thinhbg2812** [comment]
LOL
