### ISSUE TITLE
Android/Firefox : Swiping on the last image make the gallery bug

### ISSUE THREAD

**Issue by jacquesgiraudel** [leandrowd/react-responsive-carousel#756]
On a gallery with images only, when I reach the last image and try to make an additional swipe (like if there is an image after) : the gallery go back to the first image, and if i swipe next again : i see again the swipe from the last image to the first.

**Comment by tech-doctor** [comment]
I get the same issue here too, How can this be solved?

**Comment by tech-doctor** [comment]
> On a gallery with images only, when I reach the last image and try to make an additional swipe (like if there is an image after) : the gallery go back to the first image, and if i swipe next again : i see again the swipe from the last image to the first.

Downgrading the version works for me. Check 
https://github.com/leandrowd/react-responsive-carousel/issues/674#issuecomment-1353335379

**Comment by jacquesgiraudel** [comment]
Thanks
