### ISSUE TITLE
Getting This localhost page can’t be found on yarn start

### ISSUE THREAD

**Issue by yashk1998** [leandrowd/react-responsive-carousel#757]
I am trying to understand the source code and whenever I run yarn start, I get this below output 
![image](https://github.com/leandrowd/react-responsive-carousel/assets/33251900/78a52a7f-093b-4599-87e6-504098b85765)

but when I go to the browser to check for localhost, I get a different output: 
![image](https://github.com/leandrowd/react-responsive-carousel/assets/33251900/810f2976-de34-4b6a-82e8-3046bc283f24)

**Comment by AlanGreyjoy** [comment]
Sir, this is a Wendys.
