### ISSUE TITLE
There is no way to remove 'role' attribute out of li or change li to another HTML elements from 'renderThumbs' props

### ISSUE THREAD

**Issue by ningo-agilityio** [leandrowd/react-responsive-carousel#758]
Hi supporters/contributors,

When applying [react-responsive-carousel](https://github.com/leandrowd/react-responsive-carousel) into my landing page, the result is so great. However, there is no way to customize thumb which changes **li** to another HTML element. It seems that **li** is automatically generated from original source code.
The reason to proceed is that PageSpeed score reported low Accessibility scope due to **Values assigned to role="" are not valid ARIA roles**. Please check my below screenshot to get further details. 
![Screenshot 2024-01-25 at 15 15 39](https://github.com/leandrowd/react-responsive-carousel/assets/9548275/e80edb2c-2970-48a2-af2f-11b25e271983)
![Screenshot 2024-01-25 at 15 22 53](https://github.com/leandrowd/react-responsive-carousel/assets/9548275/8e49057a-d7e4-472d-a768-5c72ef56523b)

The **Accessibility** score is only 95 now. Therefore, could you check to expose one props to let us handle this task?

**Comment by justAnArthur** [comment]
+1
