### ISSUE TITLE
Unable to use this with react-static-boilerplate

### ISSUE THREAD

**Issue by ericlau-solid** [leandrowd/react-responsive-carousel#79]
I am attempting to use this, but all the examples contains either .scss (with doesn't exist) or .css in which inclusion does not result in working carousel at all (images all show up, rather than in carousel), and my css layout is distorted.

I am not sure then how should I import the css files... tried this and didn't work

import 'react-responsive-carousel/lib/styles/main.css';
import 'react-responsive-carousel/lib/styles/carousel.css';

**Comment by leandrowd** [comment]
Hi @ericlau-solid, do you have any error in the console/terminal?

I suspect it might be your css loader.

**Comment by ericlau-solid** [comment]
I thought that, but I was able to import other css. I use css loader extensively to import small custom css files without issue. I just can't import this project's css.

**Comment by ericlau-solid** [comment]
actually i think the issue is importing any css that sits in node_modules ... i can import my custom ones fine, but failing import on node_modules.

**Comment by leandrowd** [comment]
if you try `require('!style!css!react-responsive-carousel/lib/styles/carousel.css')`, does it work?

Could you paste the config of your css loader here?

**Comment by leandrowd** [comment]
Hey @ericlau-solid, did you sort this out?

**Comment by leandrowd** [comment]
If you still have problems, please have a look at https://github.com/webpack/webpack/issues/1789

I'm closing this as it's not really an issue with the component but with your webpack setup.

**Comment by juddey** [comment]
Leaving here for future Googlers. I am using `create-react-app`, and I added the following two lines to add the css to my component.

/* eslint import/no-webpack-loader-syntax: off */
import 'react-responsive-carousel/lib/styles/carousel.css'
