### ISSUE TITLE
How to stretch the carousel full container height

### ISSUE THREAD

**Issue by pke** [leandrowd/react-responsive-carousel#80]
It seems the carousel calcs its height based on the the content of each slide. However, some of my slides are less tall than others. I'd also like to align the dots at the bottom of the container and the swipe work across the whole container. Which items should I flex? Flexing the slides does not allow me to swipe on "empty" areas.

**Comment by leandrowd** [comment]
Hi @pke, have you tried adding the prop dynamicHeight?

**Comment by leandrowd** [comment]
Hi @pke, I'm closing this as `dynamicHeight` is the way to go. Feel free to re open if you have any problems.
