### ISSUE TITLE
Selected item changes on re-render

### ISSUE THREAD

**Issue by pke** [leandrowd/react-responsive-carousel#83]
If a redux action causes a re-render of the component that contains the carousel then the selected slide is set back to zero.

Lets say I am on the 4/6 slides and after 10 secs the redux state updates which causes a refresh of the parent component of the carousel. What you see is that the selected switches back to 0.

**Comment by leandrowd** [comment]
Hi @pke, the carousel doesn't know how to remember external state if it gets re-rendered. You will need to persist the actual selected item in your redux state. You can get it using the `onChange` callback and set it back using the `selectedItem` prop.

**Comment by leandrowd** [comment]
Closing as the solution for you problem is in the comment above. Feel free to re-open if you have any issues.
