### ISSUE TITLE
lib/has3d.js  fails in safari / cordova

### ISSUE THREAD

**Issue by marcusrognes** [leandrowd/react-responsive-carousel#86]
This line: [19](https://github.com/leandrowd/react-responsive-carousel/blob/master/lib/has3d.js#L19) `document.body.insertBefore(el, null);`
results in: `TypeError: null is not an object (evaluating 'document.body.insertBefore')`

**Comment by marcusrognes** [comment]
I might need to elaborate, it fails in cordova on ios. 
more specifically, it fails in meteor -> cordova -> ios

**Comment by marcusrognes** [comment]
I just realised that this is due to `document.body` not being "loaded" yet.
I would advice against doing any dom manipulation outside of the React component lifecycle.

**Comment by leandrowd** [comment]
Hi @marcusrognes, unfortunately I won't have time to fix this issue any time soon but feel free to submit a pull request with the fix and I'll gladly merge it and release.

Thanks.

**Comment by leandrowd** [comment]
Hi @marcusrognes, there was an unnecessary call for the has3d method which was causing your problem. I removed it but I can't check if it will solve your problem as I don't have a similar environment ready for tests. Would be nice if you could get the latest version and tell me if it works :)

Cheers

**Comment by leandrowd** [comment]
I'm closing this issue as per the comment above. Feel free to reopen if you have issues
