### ISSUE TITLE
Carousel#updateDimensions called before render?

### ISSUE THREAD

**Issue by edoloughlin** [leandrowd/react-responsive-carousel#9]
I'm getting 
```
Uncaught TypeError: Cannot read property 'getDOMNode' of undefined  (Carousel.js:97)
```

In Chrome 43.0.2357.65 beta (64-bit) on OS X 10.10.3. It seems `this.refs.itemsWrapper` is undefined.

**Comment by leandrowd** [comment]
This bug was fixed in the last version
