### ISSUE TITLE
 onChange is not defined

### ISSUE THREAD

**Issue by lordKnighton** [leandrowd/react-responsive-carousel#90]
trying to us Carousel in one components, but getting error `onChange` is not defined along with `onClickItem` & `onClickThumb`

Here Photos below: 
![screen shot 2017-03-15 at 7 09 44 pm](https://cloud.githubusercontent.com/assets/1773260/23978861/7835064c-09b3-11e7-867c-54e641d4e522.png)

![screen shot 2017-03-15 at 7 10 42 pm](https://cloud.githubusercontent.com/assets/1773260/23978865/7c41c9c8-09b3-11e7-8163-fb66d9b0ba17.png)

**Comment by leandrowd** [comment]
Hey @lordKnighton, I assume you copied that code from the example, right? In this case, you need to define the handlers for onChange, onClickItem and onClickThumb, or just delete them.
