### ISSUE TITLE
[SOLVED] ES6 problem type is invalid

### ISSUE THREAD

**Issue by ShineOfFire** [leandrowd/react-responsive-carousel#94]
Hi, i have a prolbem with your component, when i use it :
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by leandrowd** [comment]
Are you importing ` { Carousel } from "react-responsive-carousel"` ?

**Comment by ShineOfFire** [comment]
Yeah and i try it with minimal option like this for example : 

```javascript
import { Carousel } from 'react-responsive-carousel'

<Carousel>
     <div>hello</div>
     <div>wolrd</div>
</Carousel>
```
but not working ^^ the error :
* TypeError: Cannot read property 'length' of undefined
* Uncaught (in promise) TypeError: redirectLocation is not a function
* Uncaught TypeError: Cannot read property '__reactInternalInstance$pcr31vz8nl' of null

**Comment by leandrowd** [comment]
Good to know. Can I choose this issue then?

**Comment by leandrowd** [comment]
You can use showThumbs=false if you don't want use images.

**Comment by ShineOfFire** [comment]
Yeah close :) is good :p

**Comment by leandrowd** [comment]
Cheers
