### ISSUE TITLE
Is there a way to pass in styles as a prop to style indicators?

### ISSUE THREAD

**Issue by carakuei** [leandrowd/react-responsive-carousel#96]
Great Library! Love the storybook examples.

We @nfl use inline styles for our components and would rather not hot link to a stylesheet.

it would also apply to being able to pass styles for arrows, status, etc...

Thank you!

**Comment by leandrowd** [comment]
Hi @carakuei , I'm not actively using this component so I won't spend time refactoring it to use inline styles. Would you like to implement it yourself?

**Comment by carakuei** [comment]
thank you.
