### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by jasonogasian** [leandrowd/react-responsive-carousel#97]
I'm using the slider in the following configuration:
```

<Carousel
          axis="horizontal"
          dynamicHeight={ true }
          showThumbs={ false }
          showStatus={ false }
          showArrows={ true }
          onChange={ this.onChange }>
```

Each time I swipe I get a warning from Chrome (Version 56.0.2924.87 (64-bit)) with the message in the issue title.

**Comment by leandrowd** [comment]
Hi @jasonogasian, thanks for letting me know. Can you confirm that this is just a warning and everything is working fine? Not a lot of time to work on this right now but I will visit it as soon as possible.

**Comment by leandrowd** [comment]
Hey @jasonogasian, this warning has been fixed. Please update to the version `3.1.15`.

**Comment by jasonogasian** [comment]
Thanks! I'll pull the new version.
