### ISSUE TITLE
showThumbs={true} 

### ISSUE THREAD

**Issue by polmoneys** [leandrowd/react-responsive-carousel#98]
When true I get this 

![1](https://cloud.githubusercontent.com/assets/7026863/24865791/9a0e5e80-1e08-11e7-99fc-b144c65f8c6f.png)
![2](https://cloud.githubusercontent.com/assets/7026863/24865792/9a101374-1e08-11e7-8bdd-ab41188dee54.png)

When set to false I get no errors and renders fine. 

Tumbnails are required so can someone point me into the right direction ? The code is quite simple: 

```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { Carousel } from 'react-responsive-carousel';

const ImgSlider = ({ url }) =>{
  return(
  <div className="img-ctn" >
    <img src={url} className="img-responsive"/>
  </div>
);
}


class ProductSlider extends Component {

  render() {

    const {data} = this.props;

    return (
      <div>
           <Carousel showArrows={true} showThumbs={false}>
           {
             data.map((datum,idx) => <ImgSlider key={datum.id} url={datum.url}/>)
           }
            </Carousel>
      </div>
    )
  }
}
export default ProductSlider;
```

Gracias !

**Comment by leandrowd** [comment]
Hi @polmoneys, I suspect your array of images is empty. I will submit a fix soon but mean while you can just check if it's empty and not render or render a placeholder element.

Please, let me know if this is not the case.

Check this example of the carousel working without thumbs: http://react-responsive-carousel.js.org/storybook/?selectedKind=Carousel&selectedStory=no%20thumbs&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

**Comment by polmoneys** [comment]
The array is not empty as it renders fine all images when set to false.  If array was empty shouldn't I get this warning ?

```
// lib/components/Thumbs.js

  if (img.length) {
                console.warn(img, img.length, "No images found! Can't build the thumb list. If you don't need thumbs, set showThumbs={false} in the Carousel");
                return null;
            }
```

thanks @leandrowd for your time !

**Comment by leandrowd** [comment]
Hi @polmoneys, I believe the cause of your problems were the fact that the carousel was not supporting lazy loaded children. I've published a fix for that and I think it will solve your use case. 

Could you get the latest version `3.1.9` and let me know if it works now? 

Thanks.

**Comment by polmoneys** [comment]
Leandrowd thank you. 

As far as I can tell there are issues sith SSR but I'm not sure if the problem is on our end so feel free to close this issue if you feel like it. 

some screenshots (package.json, terminal and console) 

![3 1 9](https://cloud.githubusercontent.com/assets/7026863/25330559/5b2c4a6e-28e0-11e7-832a-442261e5377f.png)
![server-render-error](https://cloud.githubusercontent.com/assets/7026863/25330564/5f8ebe20-28e0-11e7-9afc-0b2c75cdf5db.png)
![console](https://cloud.githubusercontent.com/assets/7026863/25330571/63a5260c-28e0-11e7-9f51-9eeedb397017.png)

**Comment by leandrowd** [comment]
Would be possible to publish your code somewhere for debugging? Just a snippet and your base SSR setup...

**Comment by polmoneys** [comment]
this is our boilerplate http://github.com/TvrboPro/TvrboReact 

and the view + widget (switch to showThumbs={true} to trigger the errors above)
[code.zip](https://github.com/leandrowd/react-responsive-carousel/files/952227/code.zip)

hope helps

**Comment by leandrowd** [comment]
Hi @polmoneys, I haven't used your boilerplate to replicate the issue but have got the same warning when trying snapshot tests. I believe my fix will fix for your use case.

It's published as `3.1.11`, please update your version and try again and let me know how it goes.

Cheers.

**Comment by polmoneys** [comment]
seriously, thanks for caring. 
I'm afraid the fix ain't working for me, screenshot shows same error as before 

![ups](https://cloud.githubusercontent.com/assets/7026863/25490397/032e80fe-2b6d-11e7-9117-6986cf540881.png)

**Comment by leandrowd** [comment]
Hey @polmoneys, sorry, I can't reproduce this problem. If you want, feel free to fix the problem and send a PR. If you need any help let me know.

Cheers.

**Comment by leandrowd** [comment]
Hi @polmoneys, I finally found the problem. You were using a custom component to render the slides. The carousel can't find the image inside a custom component because it can't access component.props.children. I just published a version with better error handling to avoid the exception you got but you will need to change your code a little bit. 

Please, have a look at https://github.com/leandrowd/react-responsive-carousel/blob/master/TROUBLESHOOTING.md and update your carousel the version `3.1.3`.

**Comment by webakimbo** [comment]
Hi @leandrowd - related to this issue, it appears even if you customize your slide markup according to [the spec you noted above](https://github.com/leandrowd/react-responsive-carousel/blob/master/TROUBLESHOOTING.md), the plugin won't search any deeper for images than immediate children of the slide. Thumbnails simply don't show up for images nested deeper than that.

Simple working example [here](https://codesandbox.io/s/vq5x24l167).

In some cases you may need to build a carousel with a slightly more complex slide structure. The ability to control or define image/thumbnail location would be a useful enhancement. Thanks!

**Comment by fhrryDeveloper** [comment]
Hi Everyone.
I am using react-responsive-carousel now.
But I have a issue now.
I am making carousel-items by loop.
there is a condition and I used if statement.
But carousel shows all object item of array. If condition is match, it shows empty item. How can I remove empty item?
Here is source code:
<Carousel showStatus={false} showThumbs={false} showArrows={false}>
          {
            orders.length>0 ? (
              orders.map((order, index) => {
                if (props.period === order.period) {
                  return (
                    <div>test</div>
                  );
                }
              })
            ) : (
              <p className="no-orders">No Orders</p>
            ))
          }
